export const queryKeys = {
  uiFacade: ["strategist", "ui", "facade"] as const,
  uiWorkboard: (boardLabel: string) => ["strategist", "ui", "workboard", boardLabel] as const,
  probeHealthz: ["strategist", "probe", "healthz"] as const,
  probeLivez: ["strategist", "probe", "livez"] as const,
  probeReadyz: ["strategist", "probe", "readyz"] as const,
  readinessDeployment: ["strategist", "readiness", "deployment"] as const,
  probeApiRoot: ["strategist", "probe", "api-root"] as const,
  uiHealth: ["strategist", "ui", "health"] as const,
  uiEvidence: (searchRoot: string | undefined) => ["strategist", "ui", "evidence", searchRoot ?? ""] as const,
  uiOperatorActions: ["strategist", "ui", "operator-actions"] as const,
  uiOperatorCommandPolicy: (params: Record<string, unknown>) => ["strategist", "ui", "commands", "policy", params] as const,
  uiOperatorActionsFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "operator-actions", params] as const,
  uiEvidenceChain: ["strategist", "ui", "evidence-chain"] as const,
  uiEvidenceChainFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "evidence-chain", params] as const,
  uiTribunal: ["strategist", "ui", "tribunal"] as const,
  uiEvidenceBundles: ["strategist", "ui", "evidence-bundles"] as const,
  uiOperatorPackWorkbench: ["strategist", "ui", "packs", "workbench"] as const,
  uiPackDetail: (identity: string) => ["strategist", "ui", "packs", "detail", identity] as const,
  uiProviderHealth: ["strategist", "ui", "provider-health"] as const,
  uiProviderSetup: ["strategist", "ui", "provider-setup"] as const,
  uiMarketDataIntegrity: ["strategist", "ui", "market-data-integrity"] as const,
  uiMarketDataIntegrityFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "market-data-integrity", params] as const,
  uiDailyOperatorRunLatest: ["strategist", "ui", "daily-operator-run", "latest"] as const,
  uiResearchCompute: ["strategist", "ui", "research-compute"] as const,
  uiResearchComputeFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "research-compute", params] as const,
  uiProjectionRegistry: ["strategist", "ui", "projection-registry"] as const,
  uiProjectionRegistryFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "projection-registry", params] as const,
  uiSemanticRelease: ["strategist", "ui", "semantic-release"] as const,
  uiSemanticReleaseFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-release", params] as const,
  uiSemanticValidatorHandoff: ["strategist", "ui", "semantic-validator-handoff"] as const,
  uiSemanticValidatorHandoffFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", params] as const,
  uiSemanticValidatorHandoffLineage: ["strategist", "ui", "semantic-validator-handoff", "lineage"] as const,
  uiSemanticValidatorHandoffLineageFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "lineage", params] as const,
  uiSemanticValidatorHandoffRemediation: ["strategist", "ui", "semantic-validator-handoff", "remediation"] as const,
  uiSemanticValidatorHandoffRemediationFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "remediation", params] as const,
  uiSemanticValidatorHandoffReview: ["strategist", "ui", "semantic-validator-handoff", "review"] as const,
  uiSemanticValidatorHandoffReviewFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "review", params] as const,
  uiSemanticValidatorHandoffDecision: ["strategist", "ui", "semantic-validator-handoff", "decision"] as const,
  uiSemanticValidatorHandoffDecisionFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "decision", params] as const,
  uiSemanticValidatorHandoffSignoff: ["strategist", "ui", "semantic-validator-handoff", "signoff"] as const,
  uiSemanticValidatorHandoffSignoffFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "signoff", params] as const,
  uiSemanticValidatorHandoffCustody: ["strategist", "ui", "semantic-validator-handoff", "custody"] as const,
  uiSemanticValidatorHandoffCustodyFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "custody", params] as const,
  uiSemanticValidatorHandoffArchive: ["strategist", "ui", "semantic-validator-handoff", "archive"] as const,
  uiSemanticValidatorHandoffArchiveFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "archive", params] as const,
  uiSemanticValidatorHandoffClosure: ["strategist", "ui", "semantic-validator-handoff", "closure"] as const,
  uiSemanticValidatorHandoffClosureFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "closure", params] as const,
  uiSemanticValidatorHandoffContinuity: ["strategist", "ui", "semantic-validator-handoff", "continuity"] as const,
  uiSemanticValidatorHandoffContinuityFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "continuity", params] as const,
  uiSemanticValidatorHandoffRunbook: ["strategist", "ui", "semantic-validator-handoff", "runbook"] as const,
  uiSemanticValidatorHandoffRunbookFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "runbook", params] as const,
  uiSemanticValidatorHandoffExceptions: ["strategist", "ui", "semantic-validator-handoff", "exceptions"] as const,
  uiSemanticValidatorHandoffExceptionsFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "exceptions", params] as const,
  uiSemanticValidatorHandoffTimeline: ["strategist", "ui", "semantic-validator-handoff", "timeline"] as const,
  uiSemanticValidatorHandoffTimelineFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "timeline", params] as const,
  uiSemanticValidatorHandoffEvidenceGaps: ["strategist", "ui", "semantic-validator-handoff", "evidence-gaps"] as const,
  uiSemanticValidatorHandoffEvidenceGapsFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "evidence-gaps", params] as const,
  uiSemanticValidatorHandoffAuditPacket: ["strategist", "ui", "semantic-validator-handoff", "audit-packet"] as const,
  uiSemanticValidatorHandoffAuditPacketFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "audit-packet", params] as const,
  uiSemanticValidatorHandoffActionQueue: ["strategist", "ui", "semantic-validator-handoff", "action-queue"] as const,
  uiSemanticValidatorHandoffActionQueueFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "action-queue", params] as const,
  uiSemanticValidatorHandoffEscalationBoard: ["strategist", "ui", "semantic-validator-handoff", "escalation-board"] as const,
  uiSemanticValidatorHandoffEscalationBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "escalation-board", params] as const,
  uiSemanticValidatorHandoffResolutionPlan: ["strategist", "ui", "semantic-validator-handoff", "resolution-plan"] as const,
  uiSemanticValidatorHandoffResolutionPlanFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "resolution-plan", params] as const,
  uiSemanticValidatorHandoffClearanceGate: ["strategist", "ui", "semantic-validator-handoff", "clearance-gate"] as const,
  uiSemanticValidatorHandoffClearanceGateFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-gate", params] as const,
  uiSemanticValidatorHandoffClearanceDossier: ["strategist", "ui", "semantic-validator-handoff", "clearance-dossier"] as const,
  uiSemanticValidatorHandoffClearanceDossierFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-dossier", params] as const,
  uiSemanticValidatorHandoffClearanceChecklist: ["strategist", "ui", "semantic-validator-handoff", "clearance-checklist"] as const,
  uiSemanticValidatorHandoffClearanceChecklistFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-checklist", params] as const,
  uiSemanticValidatorHandoffClearanceEvidenceMatrix: ["strategist", "ui", "semantic-validator-handoff", "clearance-evidence-matrix"] as const,
  uiSemanticValidatorHandoffClearanceEvidenceMatrixFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-evidence-matrix", params] as const,
  uiSemanticValidatorHandoffClearanceCoverageBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-coverage-board"] as const,
  uiSemanticValidatorHandoffClearanceCoverageBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-coverage-board", params] as const,
  uiSemanticValidatorHandoffClearanceOperationsBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-operations-board"] as const,
  uiSemanticValidatorHandoffClearanceOperationsBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-operations-board", params] as const,
  uiSemanticValidatorHandoffClearanceActionRegister: ["strategist", "ui", "semantic-validator-handoff", "clearance-action-register"] as const,
  uiSemanticValidatorHandoffClearanceActionRegisterFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-action-register", params] as const,
  uiSemanticValidatorHandoffClearanceResolutionPlan: ["strategist", "ui", "semantic-validator-handoff", "clearance-resolution-plan"] as const,
  uiSemanticValidatorHandoffClearanceResolutionPlanFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-resolution-plan", params] as const,
  uiSemanticValidatorHandoffClearanceVerificationBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-verification-board"] as const,
  uiSemanticValidatorHandoffClearanceVerificationBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-verification-board", params] as const,
  uiSemanticValidatorHandoffClearanceCloseoutBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-closeout-board"] as const,
  uiSemanticValidatorHandoffClearanceCloseoutBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-closeout-board", params] as const,
  uiSemanticValidatorHandoffClearanceReviewDocket: ["strategist", "ui", "semantic-validator-handoff", "clearance-review-docket"] as const,
  uiSemanticValidatorHandoffClearanceReviewDocketFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-review-docket", params] as const,
  uiSemanticValidatorHandoffClearanceSignoffPacket: ["strategist", "ui", "semantic-validator-handoff", "clearance-signoff-packet"] as const,
  uiSemanticValidatorHandoffClearanceSignoffPacketFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-signoff-packet", params] as const,
  uiSemanticValidatorHandoffClearanceAcceptanceBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-acceptance-board"] as const,
  uiSemanticValidatorHandoffClearanceAcceptanceBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-acceptance-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseReadinessBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-readiness-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseReadinessBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-readiness-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleasePacket: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-packet"] as const,
  uiSemanticValidatorHandoffClearanceReleasePacketFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-packet", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseHandoffBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-handoff-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseHandoffBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-handoff-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseCustodyBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-custody-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseCustodyBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-custody-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseReceiptBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-receipt-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseReceiptBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-receipt-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseAcknowledgmentBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-acknowledgment-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseAcknowledgmentBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-acknowledgment-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseConfirmationBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-confirmation-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseConfirmationBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-confirmation-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseCompletionBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-completion-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseCompletionBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-completion-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseClosureBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-closure-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseClosureBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-closure-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseArchiveBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-archive-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseArchiveBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-archive-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseRetentionBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-retention-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseRetentionBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-retention-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseDispositionBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-disposition-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseDispositionBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-disposition-board", params] as const,
  uiSemanticValidatorHandoffClearanceReleaseDisposalBoard: ["strategist", "ui", "semantic-validator-handoff", "clearance-release-disposal-board"] as const,
  uiSemanticValidatorHandoffClearanceReleaseDisposalBoardFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "semantic-validator-handoff", "clearance-release-disposal-board", params] as const,
  uiStrategyBatchesLatest: ["strategist", "ui", "strategy-batches", "latest"] as const,
  uiStrategyBatchesList: ["strategist", "ui", "strategy-batches", "list"] as const,
  uiBacktestForensicsLatest: ["strategist", "ui", "backtest-forensics", "latest"] as const,
  uiBacktestForensicsFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "backtest-forensics", "latest", params] as const,
  uiPromotionReview: ["strategist", "ui", "promotion-review"] as const,
  uiPromotionReviewFiltered: (params: Record<string, unknown>) => ["strategist", "ui", "promotion-review", params] as const,
  uiPaperTrackingLatest: ["strategist", "ui", "paper-tracking", "latest"] as const,
  uiPaperTrackingDetail: (trackingId: string) =>
    ["strategist", "ui", "paper-tracking", "detail", trackingId] as const,
  uiPaperBrokerStatus: ["strategist", "ui", "paper-broker", "status"] as const,
  uiPaperExecutionLatest: ["strategist", "ui", "paper-execution", "latest"] as const,
  uiStrategyMemoryLatest: ["strategist", "ui", "strategy-memory", "latest"] as const,
  uiStrategyGraveyardLatest: ["strategist", "ui", "strategy-graveyard", "latest"] as const,
  uiStrategyIntakeLatest: ["strategist", "ui", "strategy-intake", "latest"] as const,
  uiStrategyThesisLatest: ["strategist", "ui", "strategy-thesis", "latest"] as const,
  uiStrategyThesisGenerationLatest: ["strategist", "ui", "strategy-thesis", "generation", "latest"] as const,
  uiShadowBookLatest: ["strategist", "ui", "shadow-book", "latest"] as const,
  uiResearchOsStatus: ["strategist", "ui", "research-os", "status"] as const,
  uiResearchOsClosureLatest: ["strategist", "ui", "research-os", "closure", "latest"] as const,
  uiResearchOsAttestationLatest: ["strategist", "ui", "research-os", "attestation", "latest"] as const,
  uiResearchOsBriefingLatest: ["strategist", "ui", "research-os", "briefing", "latest"] as const,
  uiResearchOsExportLatest: ["strategist", "ui", "research-os", "export", "latest"] as const,
  uiResearchOsRunLatest: ["strategist", "ui", "research-os", "run", "latest"] as const,
  uiResearchOsCatalogLatest: ["strategist", "ui", "research-os", "catalog", "latest"] as const,
  uiResearchOsDriftLatest: ["strategist", "ui", "research-os", "drift", "latest"] as const,
  uiResearchOsPolicyGateLatest: ["strategist", "ui", "research-os", "policy-gate", "latest"] as const,
  uiResearchOsExceptionLatest: ["strategist", "ui", "research-os", "exceptions", "latest"] as const,
  uiResearchOsRemediationLatest: ["strategist", "ui", "research-os", "remediation", "latest"] as const,
  uiResearchOsReleaseReadinessLatest: ["strategist", "ui", "research-os", "release-readiness", "latest"] as const,
  uiResearchOsHandoffLatest: ["strategist", "ui", "research-os", "handoff", "latest"] as const,
  uiResearchOsHandoffSignoffLatest: ["strategist", "ui", "research-os", "handoff-signoff", "latest"] as const,
  uiResearchOsReviewJournalLatest: ["strategist", "ui", "research-os", "review-journal", "latest"] as const,
  uiRuntime: (role: string) => ["strategist", "ui", "runtime", role] as const,
};
