export const queryKeys = {
  uiFacade: ["strategist", "ui", "facade"] as const,
  uiWorkboard: (boardLabel: string) => ["strategist", "ui", "workboard", boardLabel] as const,
  probeHealthz: ["strategist", "probe", "healthz"] as const,
  probeLivez: ["strategist", "probe", "livez"] as const,
  probeReadyz: ["strategist", "probe", "readyz"] as const,
  probeApiRoot: ["strategist", "probe", "api-root"] as const,
  uiHealth: ["strategist", "ui", "health"] as const,
  uiEvidence: (searchRoot: string | undefined) => ["strategist", "ui", "evidence", searchRoot ?? ""] as const,
  uiOperatorActions: ["strategist", "ui", "operator-actions"] as const,
  uiEvidenceChain: ["strategist", "ui", "evidence-chain"] as const,
  uiProviderHealth: ["strategist", "ui", "provider-health"] as const,
  uiProviderSetup: ["strategist", "ui", "provider-setup"] as const,
  uiDailyOperatorRunLatest: ["strategist", "ui", "daily-operator-run", "latest"] as const,
  uiResearchCompute: ["strategist", "ui", "research-compute"] as const,
  uiStrategyBatchesLatest: ["strategist", "ui", "strategy-batches", "latest"] as const,
  uiStrategyBatchesList: ["strategist", "ui", "strategy-batches", "list"] as const,
  uiBacktestForensicsLatest: ["strategist", "ui", "backtest-forensics", "latest"] as const,
  uiPaperTrackingLatest: ["strategist", "ui", "paper-tracking", "latest"] as const,
  uiPaperTrackingDetail: (trackingId: string) =>
    ["strategist", "ui", "paper-tracking", "detail", trackingId] as const,
  uiPaperBrokerStatus: ["strategist", "ui", "paper-broker", "status"] as const,
  uiPaperExecutionLatest: ["strategist", "ui", "paper-execution", "latest"] as const,
  uiStrategyMemoryLatest: ["strategist", "ui", "strategy-memory", "latest"] as const,
  uiStrategyGraveyardLatest: ["strategist", "ui", "strategy-graveyard", "latest"] as const,
  uiStrategyIntakeLatest: ["strategist", "ui", "strategy-intake", "latest"] as const,
  uiStrategyThesisLatest: ["strategist", "ui", "strategy-thesis", "latest"] as const,
  uiStrategyThesisGenerationLatest: ["strategist", "ui", "strategy-thesis", "generation", "latest"] as const,
  uiShadowBookLatest: ["strategist", "ui", "shadow-book", "latest"] as const,
  uiResearchOsStatus: ["strategist", "ui", "research-os", "status"] as const,
  uiResearchOsClosureLatest: ["strategist", "ui", "research-os", "closure", "latest"] as const,
  uiResearchOsAttestationLatest: ["strategist", "ui", "research-os", "attestation", "latest"] as const,
  uiResearchOsBriefingLatest: ["strategist", "ui", "research-os", "briefing", "latest"] as const,
  uiResearchOsExportLatest: ["strategist", "ui", "research-os", "export", "latest"] as const,
  uiResearchOsRunLatest: ["strategist", "ui", "research-os", "run", "latest"] as const,
  uiResearchOsCatalogLatest: ["strategist", "ui", "research-os", "catalog", "latest"] as const,
  uiResearchOsDriftLatest: ["strategist", "ui", "research-os", "drift", "latest"] as const,
  uiResearchOsPolicyGateLatest: ["strategist", "ui", "research-os", "policy-gate", "latest"] as const,
  uiResearchOsExceptionLatest: ["strategist", "ui", "research-os", "exceptions", "latest"] as const,
  uiResearchOsRemediationLatest: ["strategist", "ui", "research-os", "remediation", "latest"] as const,
  uiResearchOsReleaseReadinessLatest: ["strategist", "ui", "research-os", "release-readiness", "latest"] as const,
  uiResearchOsHandoffLatest: ["strategist", "ui", "research-os", "handoff", "latest"] as const,
  uiResearchOsHandoffSignoffLatest: ["strategist", "ui", "research-os", "handoff-signoff", "latest"] as const,
  uiResearchOsReviewJournalLatest: ["strategist", "ui", "research-os", "review-journal", "latest"] as const,
  uiRuntime: (role: string) => ["strategist", "ui", "runtime", role] as const,
};
