"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffResolutionPlan } from "@/hooks/useUiSemanticValidatorHandoffResolutionPlan";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffResolutionPlan({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF RESOLUTION PLAN</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF RESOLUTION PLAN</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/resolution-plan · ordered read-only remediation plan derived from escalation board</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Resolution inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"steps",v:String(s.resolution_step_count_returned??0)},{k:"blockers",v:String(s.blocker_triage_count??0)},{k:"external",v:String(s.external_artifact_collection_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"ack",v:q.data.step_acknowledgment_authority},{k:"repair",v:q.data.repair_execution_authority},{k:"artifact_write",v:q.data.external_artifact_write_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"step",v:String(q.data.latest?.resolution_step_id??"—")},{k:"phase",v:String(q.data.latest?.phase??"—")},{k:"state",v:String(q.data.latest?.step_state??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")}]}/></Pane></PaneGrid><Pane title="Resolution steps"><table className="term-table"><thead><tr><th>#</th><th>phase</th><th>state</th><th>priority</th><th>experiment</th><th>completion gate</th></tr></thead><tbody>{q.data.resolution_steps.map((r,i)=><tr key={`${r.resolution_step_id}:${i}`}><td><code>{r.ordinal}</code></td><td><StatusBadge raw={r.phase}/></td><td><StatusBadge raw={r.step_state}/></td><td><StatusBadge raw={r.priority}/></td><td><code>{r.experiment_id??"—"}</code></td><td><code>{r.completion_gate}</code></td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/resolution-plan JSON" data={q.data}/></>}</div>; }
