"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffClearanceChecklist } from "@/hooks/useUiSemanticValidatorHandoffClearanceChecklist";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffClearanceChecklist({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE CHECKLIST</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE CHECKLIST</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/clearance-checklist · read-only flattened checklist derived from clearance dossiers</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Checklist inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"items",v:String(s.checklist_item_count_returned??0)},{k:"attention",v:String(s.attention_required_count??0)},{k:"blocked",v:String(s.blocked_check_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"ack",v:q.data.check_acknowledgment_authority},{k:"override",v:q.data.check_override_authority},{k:"approval",v:q.data.operator_approval_authority},{k:"signoff",v:q.data.signoff_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"item",v:String(q.data.latest?.checklist_item_id??"—")},{k:"check",v:String(q.data.latest?.check_id??"—")},{k:"state",v:String(q.data.latest?.check_state??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")}]}/></Pane></PaneGrid><Pane title="Clearance checklist"><table className="term-table"><thead><tr><th>#</th><th>state</th><th>check</th><th>posture</th><th>priority</th><th>instruction</th></tr></thead><tbody>{q.data.checklist_items.map((r,i)=><tr key={`${r.checklist_item_id}:${i}`}><td><code>{r.ordinal}</code></td><td><StatusBadge raw={r.check_state}/></td><td><code>{r.check_id}</code></td><td><StatusBadge raw={r.review_posture??"UNKNOWN"}/></td><td><StatusBadge raw={r.priority}/></td><td>{r.operator_instruction}</td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/clearance-checklist JSON" data={q.data}/></>}</div>; }
