"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceSignoffPacketPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceSignoffPacketQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; signoffStatus?: Nullable<string>; signoffReadiness?: Nullable<string>; docketStatus?: Nullable<string>; docketReadiness?: Nullable<string>; closeoutStatus?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; readyForHumanSignoffObservation?: Nullable<boolean>; blocked?: Nullable<boolean>; waiting?: Nullable<boolean>; requiresAuthorizedReview?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceSignoffPacketQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"ready_for_human_signoff_observation",q.readyForHumanSignoffObservation); append(p,"blocked",q.blocked); append(p,"waiting",q.waiting); append(p,"requires_authorized_review",q.requiresAuthorizedReview); append(p,"requires_external_artifact",q.requiresExternalArtifact); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.signoffStatus) p.append("signoff_status",q.signoffStatus); if(q.signoffReadiness) p.append("signoff_readiness",q.signoffReadiness); if(q.docketStatus) p.append("docket_status",q.docketStatus); if(q.docketReadiness) p.append("docket_readiness",q.docketReadiness); if(q.closeoutStatus) p.append("closeout_status",q.closeoutStatus); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-signoff-packet?${qs}`:"/ui/semantic-validator-handoff/clearance-signoff-packet"; }
export function useUiSemanticValidatorHandoffClearanceSignoffPacket(query?: UiSemanticValidatorHandoffClearanceSignoffPacketQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceSignoffPacketPayload>(queryKeys.uiSemanticValidatorHandoffClearanceSignoffPacketFiltered(query ?? {}), path(query)); }
