"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceReviewDocketPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceReviewDocketQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; docketStatus?: Nullable<string>; docketReadiness?: Nullable<string>; closeoutStatus?: Nullable<string>; closeoutReadiness?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; readyForAuthorizedReview?: Nullable<boolean>; blocked?: Nullable<boolean>; waiting?: Nullable<boolean>; requiresAuthorizedHumanReview?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceReviewDocketQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"ready_for_authorized_review",q.readyForAuthorizedReview); append(p,"blocked",q.blocked); append(p,"waiting",q.waiting); append(p,"requires_authorized_human_review",q.requiresAuthorizedHumanReview); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.docketStatus) p.append("docket_status",q.docketStatus); if(q.docketReadiness) p.append("docket_readiness",q.docketReadiness); if(q.closeoutStatus) p.append("closeout_status",q.closeoutStatus); if(q.closeoutReadiness) p.append("closeout_readiness",q.closeoutReadiness); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-review-docket?${qs}`:"/ui/semantic-validator-handoff/clearance-review-docket"; }
export function useUiSemanticValidatorHandoffClearanceReviewDocket(query?: UiSemanticValidatorHandoffClearanceReviewDocketQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceReviewDocketPayload>(queryKeys.uiSemanticValidatorHandoffClearanceReviewDocketFiltered(query ?? {}), path(query)); }
