"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceVerificationBoardPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceVerificationBoardQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; verificationStatus?: Nullable<string>; verificationResult?: Nullable<string>; phase?: Nullable<string>; stepState?: Nullable<string>; actionState?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; blocksHandoffClearance?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; requiresHumanReview?: Nullable<boolean>; readyForOperatorClearanceReview?: Nullable<boolean>; verificationPassed?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceVerificationBoardQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"blocks_handoff_clearance",q.blocksHandoffClearance); append(p,"requires_external_artifact",q.requiresExternalArtifact); append(p,"requires_human_review",q.requiresHumanReview); append(p,"ready_for_operator_clearance_review",q.readyForOperatorClearanceReview); append(p,"verification_passed",q.verificationPassed); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.verificationStatus) p.append("verification_status",q.verificationStatus); if(q.verificationResult) p.append("verification_result",q.verificationResult); if(q.phase) p.append("phase",q.phase); if(q.stepState) p.append("step_state",q.stepState); if(q.actionState) p.append("action_state",q.actionState); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-verification-board?${qs}`:"/ui/semantic-validator-handoff/clearance-verification-board"; }
export function useUiSemanticValidatorHandoffClearanceVerificationBoard(query?: UiSemanticValidatorHandoffClearanceVerificationBoardQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceVerificationBoardPayload>(queryKeys.uiSemanticValidatorHandoffClearanceVerificationBoardFiltered(query ?? {}), path(query)); }
