import { queryKeys } from "@/lib/query/keys";
import { useReadPlaneJsonQuery } from "@/lib/query/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceReleaseReadinessBoardPayload } from "@/lib/api/types";

type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceReleaseReadinessBoardQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; releaseStatus?: Nullable<string>; releaseReadiness?: Nullable<string>; acceptanceStatus?: Nullable<string>; acceptanceReadiness?: Nullable<string>; signoffStatus?: Nullable<string>; signoffReadiness?: Nullable<string>; docketStatus?: Nullable<string>; closeoutStatus?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; readyForReleaseObservation?: Nullable<boolean>; blocked?: Nullable<boolean>; waiting?: Nullable<boolean>; requiresAcceptanceObservation?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; limit?: Nullable<number>; };
function append(p: URLSearchParams, k: string, v: Nullable<string | number | boolean>) { if (v !== null && v !== undefined && v !== "") p.append(k, String(v)); }
function path(q?: UiSemanticValidatorHandoffClearanceReleaseReadinessBoardQuery) { const p = new URLSearchParams(); if (q) { append(p, "experiment_id_contains", q.experimentIdContains); append(p, "issue_contains", q.issueContains); append(p, "ready_for_release_observation", q.readyForReleaseObservation); append(p, "blocked", q.blocked); append(p, "waiting", q.waiting); append(p, "requires_acceptance_observation", q.requiresAcceptanceObservation); append(p, "requires_external_artifact", q.requiresExternalArtifact); append(p, "limit", q.limit); if (q.evidenceLane) p.append("evidence_lane", q.evidenceLane); if (q.releaseStatus) p.append("release_status", q.releaseStatus); if (q.releaseReadiness) p.append("release_readiness", q.releaseReadiness); if (q.acceptanceStatus) p.append("acceptance_status", q.acceptanceStatus); if (q.acceptanceReadiness) p.append("acceptance_readiness", q.acceptanceReadiness); if (q.signoffStatus) p.append("signoff_status", q.signoffStatus); if (q.signoffReadiness) p.append("signoff_readiness", q.signoffReadiness); if (q.docketStatus) p.append("docket_status", q.docketStatus); if (q.closeoutStatus) p.append("closeout_status", q.closeoutStatus); if (q.priority) p.append("priority", q.priority); if (q.severity) p.append("severity", q.severity); if (q.trustBanner) p.append("trust_banner", q.trustBanner); if (q.ownerHint) p.append("owner_hint", q.ownerHint); } const qs = p.toString(); return qs ? `/ui/semantic-validator-handoff/clearance-release-readiness-board?${qs}` : "/ui/semantic-validator-handoff/clearance-release-readiness-board"; }
export function useUiSemanticValidatorHandoffClearanceReleaseReadinessBoard(query?: UiSemanticValidatorHandoffClearanceReleaseReadinessBoardQuery) { return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceReleaseReadinessBoardPayload>(queryKeys.uiSemanticValidatorHandoffClearanceReleaseReadinessBoardFiltered(query ?? {}), path(query)); }
