"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceActionRegisterPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceActionRegisterQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; actionState?: Nullable<string>; actionType?: Nullable<string>; operationState?: Nullable<string>; actionGroup?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; blocked?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; requiresHumanReview?: Nullable<boolean>; readyForOperatorClearanceReview?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceActionRegisterQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"blocked",q.blocked); append(p,"requires_external_artifact",q.requiresExternalArtifact); append(p,"requires_human_review",q.requiresHumanReview); append(p,"ready_for_operator_clearance_review",q.readyForOperatorClearanceReview); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.actionState) p.append("action_state",q.actionState); if(q.actionType) p.append("action_type",q.actionType); if(q.operationState) p.append("operation_state",q.operationState); if(q.actionGroup) p.append("action_group",q.actionGroup); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-action-register?${qs}`:"/ui/semantic-validator-handoff/clearance-action-register"; }
export function useUiSemanticValidatorHandoffClearanceActionRegister(query?: UiSemanticValidatorHandoffClearanceActionRegisterQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceActionRegisterPayload>(queryKeys.uiSemanticValidatorHandoffClearanceActionRegisterFiltered(query ?? {}), path(query)); }
