"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffEvidenceGapsPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffEvidenceGapsQuery = { searchRoot?: Nullable<string>; experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; gapKind?: Nullable<string>; gapState?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; stage?: Nullable<string>; includeResolved?: Nullable<boolean>; limit?: Nullable<number>; };
function append(params: URLSearchParams, key: string, value: Nullable<string | number | boolean>) { if (value === null || value === undefined || value === "") return; params.set(key, String(value)); }
function buildPath(query?: UiSemanticValidatorHandoffEvidenceGapsQuery): string { if (!query) return "/ui/semantic-validator-handoff/evidence-gaps"; const params = new URLSearchParams(); append(params, "search_root", query.searchRoot); append(params, "experiment_id_contains", query.experimentIdContains); append(params, "issue_contains", query.issueContains); append(params, "include_resolved", query.includeResolved); append(params, "limit", query.limit); if (query.gapKind) params.append("gap_kind", query.gapKind); if (query.gapState) params.append("gap_state", query.gapState); if (query.priority) params.append("priority", query.priority); if (query.severity) params.append("severity", query.severity); if (query.stage) params.append("stage", query.stage); const qs = params.toString(); return qs ? `/ui/semantic-validator-handoff/evidence-gaps?${qs}` : "/ui/semantic-validator-handoff/evidence-gaps"; }
export function useUiSemanticValidatorHandoffEvidenceGaps(query?: UiSemanticValidatorHandoffEvidenceGapsQuery) { return useReadPlaneJsonQuery<UiSemanticValidatorHandoffEvidenceGapsPayload>(queryKeys.uiSemanticValidatorHandoffEvidenceGapsFiltered(query ?? {}), buildPath(query)); }
