import { queryKeys } from "@/lib/query/keys";
import { useReadPlaneJsonQuery } from "@/lib/query/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceReleasePacketPayload } from "@/lib/api/types";

type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceReleasePacketQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; releasePacketStatus?: Nullable<string>; releasePacketReadiness?: Nullable<string>; releaseStatus?: Nullable<string>; releaseReadiness?: Nullable<string>; acceptanceStatus?: Nullable<string>; acceptanceReadiness?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; readyForHumanReleaseObservation?: Nullable<boolean>; blocked?: Nullable<boolean>; waiting?: Nullable<boolean>; requiresAcceptanceObservation?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; limit?: Nullable<number>; };
function append(p: URLSearchParams, k: string, v: Nullable<string | number | boolean>) { if (v !== null && v !== undefined && v !== "") p.append(k, String(v)); }
function path(q?: UiSemanticValidatorHandoffClearanceReleasePacketQuery) { const p = new URLSearchParams(); if (q) { append(p, "experiment_id_contains", q.experimentIdContains); append(p, "issue_contains", q.issueContains); append(p, "ready_for_human_release_observation", q.readyForHumanReleaseObservation); append(p, "blocked", q.blocked); append(p, "waiting", q.waiting); append(p, "requires_acceptance_observation", q.requiresAcceptanceObservation); append(p, "requires_external_artifact", q.requiresExternalArtifact); append(p, "limit", q.limit); if (q.evidenceLane) p.append("evidence_lane", q.evidenceLane); if (q.releasePacketStatus) p.append("release_packet_status", q.releasePacketStatus); if (q.releasePacketReadiness) p.append("release_packet_readiness", q.releasePacketReadiness); if (q.releaseStatus) p.append("release_status", q.releaseStatus); if (q.releaseReadiness) p.append("release_readiness", q.releaseReadiness); if (q.acceptanceStatus) p.append("acceptance_status", q.acceptanceStatus); if (q.acceptanceReadiness) p.append("acceptance_readiness", q.acceptanceReadiness); if (q.priority) p.append("priority", q.priority); if (q.severity) p.append("severity", q.severity); if (q.trustBanner) p.append("trust_banner", q.trustBanner); if (q.ownerHint) p.append("owner_hint", q.ownerHint); } const qs = p.toString(); return qs ? `/ui/semantic-validator-handoff/clearance-release-packet?${qs}` : "/ui/semantic-validator-handoff/clearance-release-packet"; }
export function useUiSemanticValidatorHandoffClearanceReleasePacket(query?: UiSemanticValidatorHandoffClearanceReleasePacketQuery) { return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceReleasePacketPayload>(queryKeys.uiSemanticValidatorHandoffClearanceReleasePacketFiltered(query ?? {}), path(query)); }
