"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceEvidenceMatrixPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceEvidenceMatrixQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; evidenceState?: Nullable<string>; checkState?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; attentionRequired?: Nullable<boolean>; blocksClearance?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceEvidenceMatrixQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"attention_required",q.attentionRequired); append(p,"blocks_clearance",q.blocksClearance); append(p,"requires_external_artifact",q.requiresExternalArtifact); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.evidenceState) p.append("evidence_state",q.evidenceState); if(q.checkState) p.append("check_state",q.checkState); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-evidence-matrix?${qs}`:"/ui/semantic-validator-handoff/clearance-evidence-matrix"; }
export function useUiSemanticValidatorHandoffClearanceEvidenceMatrix(query?: UiSemanticValidatorHandoffClearanceEvidenceMatrixQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceEvidenceMatrixPayload>(queryKeys.uiSemanticValidatorHandoffClearanceEvidenceMatrixFiltered(query ?? {}), path(query)); }
