"use client";
import { useReadPlaneJsonQuery } from "@/hooks/useReadPlaneJsonQuery";
import type { UiSemanticValidatorHandoffClearanceOperationsBoardPayload } from "@/lib/api/types";
import { queryKeys } from "@/lib/query/keys";
type Nullable<T> = T | null | undefined;
export type UiSemanticValidatorHandoffClearanceOperationsBoardQuery = { experimentIdContains?: Nullable<string>; issueContains?: Nullable<string>; evidenceLane?: Nullable<string>; coverageStatus?: Nullable<string>; operationState?: Nullable<string>; actionGroup?: Nullable<string>; priority?: Nullable<string>; severity?: Nullable<string>; trustBanner?: Nullable<string>; ownerHint?: Nullable<string>; operatorAttentionRequired?: Nullable<boolean>; handoffClearanceBlocked?: Nullable<boolean>; requiresExternalArtifact?: Nullable<boolean>; readyForOperatorClearanceReview?: Nullable<boolean>; limit?: Nullable<number>; };
const append=(p:URLSearchParams,k:string,v:Nullable<string|number|boolean>)=>{ if(v!==null&&v!==undefined&&v!=="") p.set(k,String(v)); };
function path(q?:UiSemanticValidatorHandoffClearanceOperationsBoardQuery){ const p=new URLSearchParams(); if(q){ append(p,"experiment_id_contains",q.experimentIdContains); append(p,"issue_contains",q.issueContains); append(p,"operator_attention_required",q.operatorAttentionRequired); append(p,"handoff_clearance_blocked",q.handoffClearanceBlocked); append(p,"requires_external_artifact",q.requiresExternalArtifact); append(p,"ready_for_operator_clearance_review",q.readyForOperatorClearanceReview); append(p,"limit",q.limit); if(q.evidenceLane) p.append("evidence_lane",q.evidenceLane); if(q.coverageStatus) p.append("coverage_status",q.coverageStatus); if(q.operationState) p.append("operation_state",q.operationState); if(q.actionGroup) p.append("action_group",q.actionGroup); if(q.priority) p.append("priority",q.priority); if(q.severity) p.append("severity",q.severity); if(q.trustBanner) p.append("trust_banner",q.trustBanner); if(q.ownerHint) p.append("owner_hint",q.ownerHint); } const qs=p.toString(); return qs?`/ui/semantic-validator-handoff/clearance-operations-board?${qs}`:"/ui/semantic-validator-handoff/clearance-operations-board"; }
export function useUiSemanticValidatorHandoffClearanceOperationsBoard(query?: UiSemanticValidatorHandoffClearanceOperationsBoardQuery){ return useReadPlaneJsonQuery<UiSemanticValidatorHandoffClearanceOperationsBoardPayload>(queryKeys.uiSemanticValidatorHandoffClearanceOperationsBoardFiltered(query ?? {}), path(query)); }
