/** Subset of `GET /ui/facade` used by the operator console. */
export type UiFacadeRoute = {
  method: string;
  path: string;
  kind: string;
  auth_required: boolean;
  payload_schema: string;
};

export type UiFacadePayload = {
  schema_version: string;
  surface: string;
  frontend_expected_package: string;
  frontend_package_present: boolean;
  /** Same as `frontend_package_present`: true only if the API process sees `ui/strategist-web` under its cwd. */
  frontend_package_detected_by_backend?: boolean;
  frontend_status?: string;
  frontend_readiness_claimed: boolean;
  /** The API does not assess browser reachability; always null from backend. */
  frontend_runtime_reachable?: boolean | null;
  frontend_operator_console_hint?: string;
  read_plane_only: boolean;
  mutation_route: string;
  routes: UiFacadeRoute[];
};

export type UiWorkboardStats = {
  active_count: number;
  governed_count: number;
  journaled_count: number;
  escalated_count: number;
  blocked_count: number;
  linked_count: number;
  stale_link_count: number;
  pack_item_count: number;
  pack_column_count: number;
  freshness_state: string;
};

export type UiWorkboardQueueEntry = Record<string, unknown>;

export type UiWorkboardPayload = {
  schema_version: string;
  generated_at_utc: string;
  board_label: string;
  queue: {
    entries?: UiWorkboardQueueEntry[];
    work_item_count?: number;
    queue_summary_line?: string;
    queue_key?: string;
    [key: string]: unknown;
  };
  pack_workbench: Record<string, unknown>;
  transition_policy: Record<string, unknown>;
  intelligence: Record<string, unknown>;
  materialization: Record<string, unknown>;
  stats: UiWorkboardStats;
};


export type UiOperatorCommandAction = "claim-item" | "acknowledge-reentry" | "renew-lease";

export type UiOperatorCommandRequest = {
  operator_id: string;
  work_item_key?: string | null;
  review_target?: string | null;
  pack_kind?: string | null;
  manifest_path?: string | null;
  idempotency_key?: string | null;
};

export type UiOperatorCommandReceipt = {
  schema_version: string;
  generated_at_utc?: string;
  command_id?: string;
  action: UiOperatorCommandAction | string;
  accepted: boolean;
  operator_id?: string;
  execution_mode?: string;
  status?: string;
  requires_projection_refresh?: boolean;
  journal_family?: string;
  event_hash?: string;
  sequence_number?: number;
  previous_event_hash?: string | null;
  target?: Record<string, unknown>;
  target_payload_digest?: string;
  summary_line?: string;
  idempotency_status?: string;
  duplicate_of_command_id?: string;
  authorization?: Record<string, unknown>;
  operator_message?: string;
  [key: string]: unknown;
};




export type UiEvidenceChainEntry = {
  stream_family: string;
  record_id: string;
  aggregate_id?: string;
  experiment_id?: string;
  action_event_id?: string;
  sequence_number?: number | null;
  event_type?: string;
  action?: string;
  status?: string;
  promotion_state?: string;
  accepted?: boolean;
  actor_id?: string;
  operator_id?: string;
  writer_identity?: string;
  created_at_utc?: string;
  event_hash?: string;
  previous_event_hash?: string | null;
  manifest_hash?: string;
  payload_digest_sha256?: string;
  target_payload_digest?: string;
  idempotency_key?: string | null;
  chained?: boolean;
  issue_codes?: string[];
  [key: string]: unknown;
};

export type UiEvidenceChainPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  mutation_authority: string;
  promotion_authority: string;
  execution_authority: string;
  readonly: boolean;
  database_path?: string;
  ok: boolean;
  degraded: string[];
  summary: {
    event_count_total: number;
    chain_issue_count_total: number;
    decision_ledger_event_count: number;
    decision_ledger_stream_count: number;
    operator_action_event_count: number;
    decision_ledger_chain_ok: boolean;
    operator_action_chain_ok: boolean;
    [key: string]: unknown;
  };
  streams: Record<string, Record<string, unknown>>;
  timeline: {
    entry_count: number;
    returned_count: number;
    limit: number;
    entries: UiEvidenceChainEntry[];
  };
};


export type UiProviderSetupEntry = {
  provider_id: string;
  display_name: string;
  category: string;
  research_role: string;
  access_type: string;
  trust_level: string;
  pit_suitability: string;
  recommended_priority: number;
  official_docs_url?: string;
  signup_url?: string;
  expected_env_vars?: string[];
  requires_secret: boolean;
  configured: boolean;
  reachable: boolean;
  classified_status: string;
  setup_status: string;
  readiness_tier: string;
  freshness_class: string;
  freshness_age_seconds?: number | null;
  freshness_max_age_seconds: number;
  last_checked_utc?: string | null;
  sample_digest_prefix?: string | null;
  evidence_reference?: string;
  may_gate_live_promotion?: boolean;
  unsafe_as_promotion_authority_without_license?: boolean;
  warnings?: string[];
  blockers?: string[];
  remediation?: string[];
  [key: string]: unknown;
};

export type UiProviderSetupConsolePayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  mutation_authority: string;
  execution_authority: string;
  no_network_calls: boolean;
  no_secret_values: boolean;
  freshness_max_age_seconds: number;
  samples_manifest_path?: string | null;
  samples_manifest_digest_prefix?: string | null;
  execution_workflow_blockers?: string[];
  summary: {
    provider_count: number;
    ready_count: number;
    blocked_count: number;
    action_required_count: number;
    stale_count: number;
    not_checked_count: number;
    missing_secret_count: number;
    public_no_signup_count: number;
    keyed_provider_count: number;
    pit_strong_count: number;
    sample_manifest_present?: boolean;
    health_schema_version?: string;
    [key: string]: unknown;
  };
  entries: UiProviderSetupEntry[];
};


export type UiBacktestForensicsPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  no_live_trading: boolean;
  mutation_authority: string;
  promotion_authority: string;
  execution_authority: string;
  scan_root: string;
  summary_path?: string | null;
  degraded: string[];
  batch?: Record<string, unknown> | null;
  summary: Record<string, unknown>;
  strategies: Array<Record<string, unknown>>;
  raw_strategy_batch_route?: string | null;
};


export type UiPaperExecutionIntentPreview = {
  schema_version: string;
  tracking_id?: string | null;
  strategy_id?: string | null;
  symbol: string;
  side: "buy" | "sell" | string;
  qty: number;
  order_type: "market" | "limit" | string;
  time_in_force: string;
  source: string;
  rationale: string;
  confidence: string;
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionIntentSelectionArtifact = {
  schema_version: string;
  generated_at_utc: string;
  tracking_id: string;
  strategy_id?: string | null;
  paper_trading_only: boolean;
  live_trading_blocked: boolean;
  no_network_calls: boolean;
  no_order_submitted: boolean;
  mutation_authority: string;
  execution_authority: string;
  submission_authority: string;
  selection_authority: string;
  selected_by: string;
  selection_reason: string;
  source_artifact_path?: string | null;
  selected_intent: UiPaperExecutionIntentPreview;
  broker_intent: Record<string, unknown>;
  dry_run_command_hint: string;
  artifact_sha256: string;
  [key: string]: unknown;
};

export type UiPaperExecutionJournalEntry = {
  schema_version: string;
  tracking_id: string;
  artifact_kind?: "DRY_RUN" | "SUBMISSION" | string;
  artifact_path: string;
  broker_order_id?: string | null;
  status?: string | null;
  ok?: boolean | null;
  dry_run?: boolean | null;
  retrieved_at_utc?: string | null;
  digest_prefix?: string | null;
  source_selection_artifact_path?: string | null;
  source_selection_artifact_sha256?: string | null;
  linked_dry_run_artifact_sha256?: string | null;
  submission_guard_status?: string | null;
  evidence_freshness_status?: string | null;
  selected_intent_match?: boolean | null;
  linked_dry_run_match?: boolean | null;
  linked_dry_run_ok?: boolean | null;
  warnings: string[];
  blockers: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionSubmissionReceiptView = {
  schema_version: string;
  tracking_id: string;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  broker_order_id?: string | null;
  broker_status?: string | null;
  result_ok?: boolean | null;
  symbol?: string | null;
  side?: string | null;
  qty?: number | null;
  filled_qty?: number | null;
  policy_status?: string | null;
  guard_status: string;
  evidence_freshness_status: string;
  selected_intent_artifact_sha256?: string | null;
  linked_dry_run_artifact_sha256?: string | null;
  linked_dry_run_source_selection_sha256?: string | null;
  submission_intent_matches_selection?: boolean | null;
  linked_dry_run_matches_selection?: boolean | null;
  linked_dry_run_ok?: boolean | null;
  guard_blocker_count: number;
  guard_warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionOrderStatusView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path?: string | null;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  broker_order_id?: string | null;
  status?: string | null;
  ok?: boolean | null;
  filled_qty?: number | null;
  symbol?: string | null;
  side?: string | null;
  policy_status?: string | null;
  source_submission_artifact_sha256?: string | null;
  source_submission_artifact_path?: string | null;
  warnings: string[];
  blockers: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionPositionReconciliation = {
  schema_version: string;
  status: string;
  tracking_id?: string | null;
  symbol?: string | null;
  side?: string | null;
  submitted_qty?: number | null;
  filled_qty?: number | null;
  expected_position_delta_qty?: number | null;
  observed_position_qty?: number | null;
  broker_status?: string | null;
  latest_submission_receipt_at_utc?: string | null;
  latest_submission_receipt_artifact_sha256?: string | null;
  account_position_snapshot_path?: string | null;
  account_position_snapshot_sha256?: string | null;
  account_position_snapshot_at_utc?: string | null;
  account_position_snapshot_age_hours?: number | null;
  reconciliation_blocker_count: number;
  reconciliation_warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionAccountPositionSnapshot = {
  schema_version: string;
  generated_at_utc: string;
  broker_id: string;
  policy_status: string;
  position_count: number;
  positions: Array<Record<string, unknown>>;
  notes: string[];
  artifact_sha256: string;
  [key: string]: unknown;
};


export type UiPaperExecutionTimelineEntry = {
  schema_version: string;
  stage: string;
  stage_order: number;
  tracking_id?: string | null;
  generated_at_utc?: string | null;
  artifact_path?: string | null;
  artifact_sha256?: string | null;
  status: string;
  ok?: boolean | null;
  trusted: boolean;
  summary_line: string;
  broker_order_id?: string | null;
  symbol?: string | null;
  side?: string | null;
  qty?: number | null;
  source_selection_artifact_sha256?: string | null;
  linked_dry_run_artifact_sha256?: string | null;
  source_submission_artifact_sha256?: string | null;
  warnings: string[];
  blockers: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionTimelineSummary = {
  schema_version: string;
  event_count: number;
  stage_count: number;
  trusted_event_count: number;
  blocker_count: number;
  warning_count: number;
  latest_event_at_utc?: string | null;
  sequence_status: string;
  completed_stages: string[];
  missing_stages: string[];
  [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  bundle_sha256?: string | null;
  generated_at_utc?: string | null;
  trust_banner: string;
  bundle_status: string;
  timeline_sequence_status: string;
  timeline_event_count: number;
  timeline_trusted_event_count: number;
  timeline_blocker_count: number;
  source_artifact_count: number;
  missing_stages: string[];
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_bundle_artifact_path?: string | null;
  source_bundle_declared_sha256?: string | null;
  source_bundle_computed_sha256?: string | null;
  bundle_hash_valid: boolean;
  timeline_source_link_valid: boolean;
  source_artifact_count: number;
  verified_source_artifact_count: number;
  missing_source_artifact_count: number;
  mismatched_source_artifact_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleDriftView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  drift_status: string;
  trust_banner: string;
  source_bundle_artifact_path?: string | null;
  source_bundle_sha256?: string | null;
  source_bundle_generated_at_utc?: string | null;
  current_timeline_sequence_status?: string | null;
  current_timeline_event_count: number;
  bundled_timeline_event_count: number;
  current_source_artifact_count: number;
  bundled_source_artifact_count: number;
  current_timeline_fingerprint?: string | null;
  bundled_timeline_fingerprint?: string | null;
  new_source_artifact_count: number;
  removed_source_artifact_count: number;
  changed_stage_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRotationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  rotation_status: string;
  trust_banner: string;
  source_bundle_sha256?: string | null;
  source_bundle_status?: string | null;
  source_verification_status?: string | null;
  source_drift_status?: string | null;
  timeline_sequence_status?: string | null;
  timeline_event_count: number;
  rotation_reason_codes: string[];
  recommended_operator_sequence: string[];
  one_command_sequence_hint?: string | null;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRotationExecutionView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  rotation_execution_status: string;
  trust_banner: string;
  source_recommendation_status?: string | null;
  timeline_sequence_status?: string | null;
  sealed_bundle_sha256?: string | null;
  verification_status?: string | null;
  drift_status?: string | null;
  step_count: number;
  passed_step_count: number;
  failed_step_count: number;
  skipped_step_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleAttestationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  attestation_status: string;
  trust_banner: string;
  attestation_mode: string;
  signature_status: string;
  signer_identity?: string | null;
  source_bundle_sha256?: string | null;
  source_bundle_status?: string | null;
  source_verification_status?: string | null;
  source_drift_status?: string | null;
  statement_payload_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleAttestationVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_attestation_artifact_path?: string | null;
  source_attestation_declared_sha256?: string | null;
  source_attestation_computed_sha256?: string | null;
  source_attestation_status?: string | null;
  source_attestation_trust_banner?: string | null;
  artifact_hash_valid: boolean;
  statement_payload_hash_valid: boolean;
  envelope_payload_hash_valid: boolean;
  keyless_stub_signature_valid: boolean;
  source_bundle_hash_valid: boolean;
  source_verification_hash_valid: boolean;
  source_drift_hash_valid: boolean;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleClosureView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  closure_status: string;
  trust_banner: string;
  source_bundle_sha256?: string | null;
  source_bundle_status?: string | null;
  source_verification_status?: string | null;
  source_drift_status?: string | null;
  source_attestation_status?: string | null;
  source_attestation_verification_status?: string | null;
  source_attestation_artifact_hash_valid: boolean;
  source_attestation_statement_hash_valid: boolean;
  source_attestation_envelope_hash_valid: boolean;
  source_attestation_keyless_stub_valid: boolean;
  source_attestation_bundle_hash_valid: boolean;
  source_attestation_bundle_verification_hash_valid: boolean;
  source_attestation_drift_hash_valid: boolean;
  closure_reason_codes: string[];
  recommended_operator_sequence: string[];
  one_command_sequence_hint?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleClosureVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_closure_artifact_path?: string | null;
  source_closure_declared_sha256?: string | null;
  source_closure_computed_sha256?: string | null;
  source_closure_status?: string | null;
  source_closure_trust_banner?: string | null;
  closure_artifact_hash_valid: boolean;
  source_bundle_hash_valid: boolean;
  source_verification_hash_valid: boolean;
  source_drift_hash_valid: boolean;
  source_attestation_hash_valid: boolean;
  source_attestation_verification_hash_valid: boolean;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleExportManifestView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  export_status: string;
  trust_banner: string;
  source_closure_verification_artifact_path?: string | null;
  source_closure_verification_artifact_sha256?: string | null;
  source_closure_verification_status?: string | null;
  source_closure_status?: string | null;
  closure_verification_artifact_hash_valid: boolean;
  export_entry_count: number;
  export_digest_valid_entry_count: number;
  total_size_bytes: number;
  export_index_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};



export type UiPaperExecutionEvidenceBundleRetentionReceiptView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  retention_status: string;
  trust_banner: string;
  source_export_verification_artifact_path?: string | null;
  source_export_verification_artifact_sha256?: string | null;
  source_export_verification_status?: string | null;
  source_export_manifest_artifact_path?: string | null;
  source_export_manifest_status?: string | null;
  export_verification_artifact_hash_valid: boolean;
  retained_entry_count: number;
  retained_ready_entry_count: number;
  total_size_bytes: number;
  retention_index_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_receipt_artifact_path?: string | null;
  source_retention_receipt_declared_sha256?: string | null;
  source_retention_receipt_computed_sha256?: string | null;
  source_retention_receipt_status?: string | null;
  source_retention_receipt_trust_banner?: string | null;
  retention_receipt_hash_valid: boolean;
  source_retention_index_declared_sha256?: string | null;
  source_retention_index_computed_sha256?: string | null;
  retention_index_hash_valid: boolean;
  source_retention_entry_count: number;
  source_retention_ready_entry_count: number;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleRetentionSignoffView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  signoff_status: string;
  trust_banner: string;
  operator_id?: string | null;
  decision_note?: string | null;
  source_retention_verification_artifact_path?: string | null;
  source_retention_verification_declared_sha256?: string | null;
  source_retention_verification_status?: string | null;
  source_retention_verification_trust_banner?: string | null;
  retention_verification_artifact_hash_valid: boolean;
  source_retention_receipt_artifact_path?: string | null;
  source_retention_receipt_status?: string | null;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  signoff_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionSignoffVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_signoff_artifact_path?: string | null;
  source_retention_signoff_declared_sha256?: string | null;
  source_retention_signoff_computed_sha256?: string | null;
  source_retention_signoff_status?: string | null;
  source_retention_signoff_trust_banner?: string | null;
  retention_signoff_artifact_hash_valid: boolean;
  operator_id?: string | null;
  decision_note?: string | null;
  signoff_statement_declared_sha256?: string | null;
  signoff_statement_computed_sha256?: string | null;
  signoff_statement_hash_valid: boolean;
  source_retention_verification_artifact_path?: string | null;
  source_retention_verification_declared_sha256?: string | null;
  source_retention_verification_status?: string | null;
  source_retention_verification_trust_banner?: string | null;
  retention_verification_artifact_hash_valid: boolean;
  source_retention_receipt_artifact_path?: string | null;
  source_retention_receipt_status?: string | null;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleRetentionHandoffView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  handoff_status: string;
  trust_banner: string;
  custodian_id?: string | null;
  handoff_note?: string | null;
  source_retention_signoff_verification_artifact_path?: string | null;
  source_retention_signoff_verification_declared_sha256?: string | null;
  source_retention_signoff_verification_status?: string | null;
  source_retention_signoff_verification_trust_banner?: string | null;
  retention_signoff_verification_artifact_hash_valid: boolean;
  source_retention_signoff_artifact_path?: string | null;
  source_retention_signoff_status?: string | null;
  source_retention_signoff_trust_banner?: string | null;
  retention_signoff_artifact_hash_valid: boolean;
  signoff_statement_hash_valid: boolean;
  source_retention_verification_artifact_path?: string | null;
  source_retention_verification_status?: string | null;
  retention_verification_artifact_hash_valid: boolean;
  source_retention_receipt_artifact_path?: string | null;
  source_retention_receipt_status?: string | null;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  handoff_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionHandoffVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_handoff_artifact_path?: string | null;
  source_retention_handoff_declared_sha256?: string | null;
  source_retention_handoff_computed_sha256?: string | null;
  source_retention_handoff_status?: string | null;
  source_retention_handoff_trust_banner?: string | null;
  retention_handoff_artifact_hash_valid: boolean;
  custodian_id?: string | null;
  handoff_note?: string | null;
  handoff_statement_declared_sha256?: string | null;
  handoff_statement_computed_sha256?: string | null;
  handoff_statement_hash_valid: boolean;
  source_retention_signoff_verification_artifact_path?: string | null;
  source_retention_signoff_verification_declared_sha256?: string | null;
  source_retention_signoff_verification_status?: string | null;
  source_retention_signoff_verification_trust_banner?: string | null;
  retention_signoff_verification_artifact_hash_valid: boolean;
  retention_signoff_artifact_hash_valid: boolean;
  signoff_statement_hash_valid: boolean;
  retention_verification_artifact_hash_valid: boolean;
  source_retention_receipt_artifact_path?: string | null;
  source_retention_receipt_status?: string | null;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  acceptance_status: string;
  trust_banner: string;
  accepting_custodian_id?: string | null;
  custody_location?: string | null;
  acceptance_note?: string | null;
  source_retention_handoff_verification_artifact_path?: string | null;
  source_retention_handoff_verification_declared_sha256?: string | null;
  source_retention_handoff_verification_status?: string | null;
  source_retention_handoff_verification_trust_banner?: string | null;
  retention_handoff_verification_artifact_hash_valid: boolean;
  source_retention_handoff_artifact_path?: string | null;
  source_retention_handoff_status?: string | null;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  acceptance_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_handoff_acceptance_artifact_path?: string | null;
  source_retention_handoff_acceptance_declared_sha256?: string | null;
  source_retention_handoff_acceptance_status?: string | null;
  retention_handoff_acceptance_artifact_hash_valid: boolean;
  acceptance_statement_hash_valid: boolean;
  source_retention_handoff_verification_artifact_path?: string | null;
  source_retention_handoff_verification_declared_sha256?: string | null;
  source_retention_handoff_verification_status?: string | null;
  retention_handoff_verification_artifact_hash_valid: boolean;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyRegisterView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  register_status: string;
  trust_banner: string;
  custody_register_id?: string | null;
  registered_by?: string | null;
  custody_location?: string | null;
  register_note?: string | null;
  source_retention_handoff_acceptance_verification_artifact_path?: string | null;
  source_retention_handoff_acceptance_verification_declared_sha256?: string | null;
  source_retention_handoff_acceptance_verification_status?: string | null;
  retention_handoff_acceptance_verification_artifact_hash_valid: boolean;
  retention_handoff_acceptance_artifact_hash_valid: boolean;
  acceptance_statement_hash_valid: boolean;
  retention_handoff_verification_artifact_hash_valid: boolean;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  source_retention_index_sha256?: string | null;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  custody_register_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyRegisterVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_custody_register_artifact_path?: string | null;
  source_retention_custody_register_declared_sha256?: string | null;
  source_retention_custody_register_status?: string | null;
  retention_custody_register_artifact_hash_valid: boolean;
  custody_register_id?: string | null;
  custody_register_statement_hash_valid: boolean;
  retention_handoff_acceptance_verification_artifact_hash_valid: boolean;
  retention_handoff_acceptance_artifact_hash_valid: boolean;
  acceptance_statement_hash_valid: boolean;
  retention_handoff_verification_artifact_hash_valid: boolean;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodySealView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  seal_status: string;
  trust_banner: string;
  custody_seal_id?: string | null;
  sealed_by?: string | null;
  custody_location?: string | null;
  seal_note?: string | null;
  source_retention_custody_register_verification_artifact_path?: string | null;
  source_retention_custody_register_verification_declared_sha256?: string | null;
  source_retention_custody_register_verification_status?: string | null;
  retention_custody_register_verification_artifact_hash_valid: boolean;
  source_retention_custody_register_status?: string | null;
  retention_custody_register_artifact_hash_valid: boolean;
  custody_register_id?: string | null;
  custody_register_statement_hash_valid: boolean;
  retention_handoff_acceptance_verification_artifact_hash_valid: boolean;
  retention_handoff_acceptance_artifact_hash_valid: boolean;
  acceptance_statement_hash_valid: boolean;
  retention_handoff_verification_artifact_hash_valid: boolean;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  custody_seal_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodySealVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_custody_seal_artifact_path?: string | null;
  source_retention_custody_seal_declared_sha256?: string | null;
  source_retention_custody_seal_status?: string | null;
  retention_custody_seal_artifact_hash_valid: boolean;
  custody_seal_id?: string | null;
  custody_seal_statement_hash_valid: boolean;
  source_retention_custody_register_verification_status?: string | null;
  retention_custody_register_verification_artifact_hash_valid: boolean;
  source_retention_custody_register_status?: string | null;
  retention_custody_register_artifact_hash_valid: boolean;
  custody_register_id?: string | null;
  custody_register_statement_hash_valid: boolean;
  retention_handoff_acceptance_verification_artifact_hash_valid: boolean;
  retention_handoff_acceptance_artifact_hash_valid: boolean;
  acceptance_statement_hash_valid: boolean;
  retention_handoff_verification_artifact_hash_valid: boolean;
  retention_handoff_artifact_hash_valid: boolean;
  handoff_statement_hash_valid: boolean;
  retention_signoff_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyAuditView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  audit_status: string;
  trust_banner: string;
  custody_audit_id?: string | null;
  audited_by?: string | null;
  custody_location?: string | null;
  audit_note?: string | null;
  source_retention_custody_seal_verification_artifact_path?: string | null;
  source_retention_custody_seal_verification_status?: string | null;
  retention_custody_seal_verification_artifact_hash_valid: boolean;
  source_retention_custody_seal_status?: string | null;
  retention_custody_seal_artifact_hash_valid: boolean;
  custody_seal_id?: string | null;
  custody_seal_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  custody_audit_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyAuditVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_custody_audit_artifact_path?: string | null;
  source_retention_custody_audit_status?: string | null;
  retention_custody_audit_artifact_hash_valid: boolean;
  custody_audit_id?: string | null;
  audited_by?: string | null;
  custody_location?: string | null;
  custody_audit_statement_hash_valid: boolean;
  source_retention_custody_seal_verification_status?: string | null;
  retention_custody_seal_verification_artifact_hash_valid: boolean;
  source_retention_custody_seal_status?: string | null;
  retention_custody_seal_artifact_hash_valid: boolean;
  custody_seal_id?: string | null;
  custody_seal_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyContinuityView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  continuity_status: string;
  trust_banner: string;
  custody_continuity_id?: string | null;
  attested_by?: string | null;
  custody_location?: string | null;
  continuity_note?: string | null;
  source_retention_custody_audit_verification_artifact_path?: string | null;
  source_retention_custody_audit_verification_status?: string | null;
  retention_custody_audit_verification_artifact_hash_valid: boolean;
  source_retention_custody_audit_status?: string | null;
  retention_custody_audit_artifact_hash_valid: boolean;
  custody_audit_id?: string | null;
  custody_audit_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  custody_continuity_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyContinuityVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_custody_continuity_artifact_path?: string | null;
  source_retention_custody_continuity_status?: string | null;
  retention_custody_continuity_artifact_hash_valid: boolean;
  custody_continuity_id?: string | null;
  attested_by?: string | null;
  custody_location?: string | null;
  custody_continuity_statement_hash_valid: boolean;
  source_retention_custody_audit_verification_status?: string | null;
  retention_custody_audit_verification_artifact_hash_valid: boolean;
  source_retention_custody_audit_status?: string | null;
  retention_custody_audit_artifact_hash_valid: boolean;
  custody_audit_id?: string | null;
  custody_audit_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyReviewView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  review_status: string;
  trust_banner: string;
  custody_review_id?: string | null;
  reviewed_by?: string | null;
  custody_location?: string | null;
  review_note?: string | null;
  source_retention_custody_continuity_verification_artifact_path?: string | null;
  source_retention_custody_continuity_verification_status?: string | null;
  retention_custody_continuity_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  custody_review_statement_sha256?: string | null;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyReviewVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_retention_custody_review_artifact_path?: string | null;
  source_retention_custody_review_status?: string | null;
  retention_custody_review_artifact_hash_valid: boolean;
  custody_review_id?: string | null;
  reviewed_by?: string | null;
  custody_location?: string | null;
  custody_review_statement_hash_valid: boolean;
  source_retention_custody_continuity_verification_status?: string | null;
  retention_custody_continuity_verification_artifact_hash_valid: boolean;
  recomputed_retention_entry_count: number;
  recomputed_retention_ready_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyRenewalView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  renewal_status: string; trust_banner: string; custody_renewal_id?: string | null; renewed_by?: string | null; custody_location?: string | null; renewal_interval_days: number; renewal_note?: string | null;
  source_retention_custody_review_verification_status?: string | null; retention_custody_review_verification_artifact_hash_valid: boolean; custody_review_id?: string | null; custody_review_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_renewal_statement_sha256?: string | null;
  blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyRenewalVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_renewal_status?: string | null; retention_custody_renewal_artifact_hash_valid: boolean; custody_renewal_id?: string | null; renewed_by?: string | null; custody_location?: string | null; renewal_interval_days: number; custody_renewal_statement_hash_valid: boolean;
  source_retention_custody_review_verification_status?: string | null; retention_custody_review_verification_artifact_hash_valid: boolean; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number;
  blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyScheduleView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  schedule_status: string; trust_banner: string; custody_schedule_id?: string | null; scheduled_by?: string | null; custody_location?: string | null; schedule_start_at_utc?: string | null; next_renewal_due_at_utc?: string | null; renewal_interval_days: number; reminder_days_before_due: number; schedule_note?: string | null;
  source_retention_custody_renewal_verification_status?: string | null; retention_custody_renewal_verification_artifact_hash_valid: boolean; source_retention_custody_renewal_status?: string | null; retention_custody_renewal_artifact_hash_valid: boolean; custody_renewal_id?: string | null; custody_renewal_statement_hash_valid: boolean;
  recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_schedule_statement_sha256?: string | null; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyScheduleVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_schedule_status?: string | null; retention_custody_schedule_artifact_hash_valid: boolean; custody_schedule_id?: string | null; scheduled_by?: string | null; custody_location?: string | null; schedule_start_at_utc?: string | null; next_renewal_due_at_utc?: string | null; renewal_interval_days: number; reminder_days_before_due: number; custody_schedule_statement_hash_valid: boolean;
  source_retention_custody_renewal_verification_status?: string | null; retention_custody_renewal_verification_artifact_hash_valid: boolean; source_retention_custody_renewal_status?: string | null; retention_custody_renewal_artifact_hash_valid: boolean; custody_renewal_id?: string | null; custody_renewal_statement_hash_valid: boolean; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyNoticeView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  notice_status: string; trust_banner: string; custody_notice_id?: string | null; notified_by?: string | null; custody_location?: string | null; notice_generated_for_utc?: string | null; next_renewal_due_at_utc?: string | null; reminder_window_starts_at_utc?: string | null; days_until_due: number; renewal_interval_days: number; reminder_days_before_due: number; notice_message?: string | null; notice_note?: string | null;
  source_retention_custody_schedule_verification_status?: string | null; retention_custody_schedule_verification_artifact_hash_valid: boolean; source_retention_custody_schedule_status?: string | null; retention_custody_schedule_artifact_hash_valid: boolean; custody_schedule_id?: string | null; custody_schedule_statement_hash_valid: boolean; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_notice_statement_sha256?: string | null; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyNoticeVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_notice_status?: string | null; retention_custody_notice_artifact_hash_valid: boolean; custody_notice_id?: string | null; notified_by?: string | null; custody_location?: string | null; notice_generated_for_utc?: string | null; next_renewal_due_at_utc?: string | null; reminder_window_starts_at_utc?: string | null; days_until_due: number; renewal_interval_days: number; reminder_days_before_due: number; notice_message?: string | null; custody_notice_statement_hash_valid: boolean;
  source_retention_custody_schedule_verification_status?: string | null; retention_custody_schedule_verification_artifact_hash_valid: boolean; source_retention_custody_schedule_status?: string | null; retention_custody_schedule_artifact_hash_valid: boolean; custody_schedule_id?: string | null; custody_schedule_statement_hash_valid: boolean; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  acknowledgment_status: string; trust_banner: string; custody_acknowledgment_id?: string | null; acknowledged_by?: string | null; custody_location?: string | null; acknowledged_at_utc?: string | null; acknowledgment_note?: string | null;
  source_retention_custody_notice_verification_status?: string | null; retention_custody_notice_verification_artifact_hash_valid: boolean; source_retention_custody_notice_status?: string | null; retention_custody_notice_artifact_hash_valid: boolean; custody_notice_id?: string | null; custody_notice_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_acknowledgment_statement_sha256?: string | null; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_acknowledgment_status?: string | null; retention_custody_acknowledgment_artifact_hash_valid: boolean; custody_acknowledgment_id?: string | null; acknowledged_by?: string | null; custody_location?: string | null; acknowledged_at_utc?: string | null; custody_acknowledgment_statement_hash_valid: boolean;
  source_retention_custody_notice_verification_status?: string | null; retention_custody_notice_verification_artifact_hash_valid: boolean; source_retention_custody_notice_status?: string | null; retention_custody_notice_artifact_hash_valid: boolean; custody_notice_id?: string | null; custody_notice_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyCompletionView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  completion_status: string; trust_banner: string; custody_completion_id?: string | null; completed_by?: string | null; custody_location?: string | null; completed_at_utc?: string | null; completion_note?: string | null;
  source_retention_custody_acknowledgment_verification_status?: string | null; retention_custody_acknowledgment_verification_artifact_hash_valid: boolean; source_retention_custody_acknowledgment_status?: string | null; retention_custody_acknowledgment_artifact_hash_valid: boolean; custody_acknowledgment_id?: string | null; custody_acknowledgment_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_completion_statement_sha256?: string | null; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyCompletionVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_completion_status?: string | null; retention_custody_completion_artifact_hash_valid: boolean; custody_completion_id?: string | null; completed_by?: string | null; custody_location?: string | null; completed_at_utc?: string | null; custody_completion_statement_hash_valid: boolean;
  source_retention_custody_acknowledgment_verification_status?: string | null; retention_custody_acknowledgment_verification_artifact_hash_valid: boolean; source_retention_custody_acknowledgment_status?: string | null; retention_custody_acknowledgment_artifact_hash_valid: boolean; custody_acknowledgment_id?: string | null; custody_acknowledgment_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  closeout_status: string; trust_banner: string; custody_closeout_id?: string | null; closed_out_by?: string | null; custody_location?: string | null; closed_out_at_utc?: string | null; closeout_note?: string | null;
  source_retention_custody_completion_verification_status?: string | null; retention_custody_completion_verification_artifact_hash_valid: boolean; source_retention_custody_completion_status?: string | null; retention_custody_completion_artifact_hash_valid: boolean; custody_completion_id?: string | null; custody_completion_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; custody_closeout_statement_sha256?: string | null; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutVerificationView = {
  schema_version: string; tracking_id?: string | null; artifact_path: string; artifact_sha256?: string | null; generated_at_utc?: string | null;
  verification_status: string; trust_banner: string; source_retention_custody_closeout_status?: string | null; retention_custody_closeout_artifact_hash_valid: boolean; custody_closeout_id?: string | null; closed_out_by?: string | null; custody_location?: string | null; closed_out_at_utc?: string | null; custody_closeout_statement_hash_valid: boolean;
  source_retention_custody_completion_verification_status?: string | null; retention_custody_completion_verification_artifact_hash_valid: boolean; source_retention_custody_completion_status?: string | null; retention_custody_completion_artifact_hash_valid: boolean; custody_completion_id?: string | null; custody_completion_statement_hash_valid: boolean; next_renewal_due_at_utc?: string | null; days_until_due: number; recomputed_retention_entry_count: number; recomputed_retention_ready_entry_count: number; missing_entry_count: number; digest_mismatch_entry_count: number; blocker_count: number; warning_count: number; blockers: string[]; warnings: string[]; [key: string]: unknown;
};


export type UiPaperExecutionEvidenceBundleRetentionCustodyGenericView = {
  schema_version?: string;
  tracking_id?: string | null;
  artifact_path?: string | null;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status?: string | null;
  trust_banner?: string | null;
  archive_status?: string | null;
  retrieval_status?: string | null;
  return_status?: string | null;
  redeposit_status?: string | null;
  inventory_status?: string | null;
  reconciliation_status?: string | null;
  certification_status?: string | null;
  custody_archive_id?: string | null;
  custody_retrieval_id?: string | null;
  custody_return_id?: string | null;
  custody_redeposit_id?: string | null;
  custody_inventory_id?: string | null;
  custody_reconciliation_id?: string | null;
  custody_certification_id?: string | null;
  custody_closeout_id?: string | null;
  custody_completion_id?: string | null;
  archived_by?: string | null;
  retrieved_by?: string | null;
  returned_by?: string | null;
  redeposited_by?: string | null;
  inventoried_by?: string | null;
  reconciled_by?: string | null;
  certified_by?: string | null;
  custody_location?: string | null;
  next_renewal_due_at_utc?: string | null;
  source_retention_custody_certification_status?: string | null;
  source_retention_custody_reconciliation_status?: string | null;
  source_retention_custody_inventory_status?: string | null;
  source_retention_custody_redeposit_status?: string | null;
  source_retention_custody_return_status?: string | null;
  source_retention_custody_retrieval_status?: string | null;
  source_retention_custody_archive_status?: string | null;
  retention_custody_certification_artifact_hash_valid?: boolean;
  retention_custody_reconciliation_artifact_hash_valid?: boolean;
  retention_custody_inventory_artifact_hash_valid?: boolean;
  retention_custody_redeposit_artifact_hash_valid?: boolean;
  retention_custody_return_artifact_hash_valid?: boolean;
  retention_custody_retrieval_artifact_hash_valid?: boolean;
  retention_custody_archive_artifact_hash_valid?: boolean;
  retention_custody_closeout_artifact_hash_valid?: boolean;
  retention_custody_certification_verification_artifact_hash_valid?: boolean;
  retention_custody_reconciliation_verification_artifact_hash_valid?: boolean;
  retention_custody_inventory_verification_artifact_hash_valid?: boolean;
  retention_custody_redeposit_verification_artifact_hash_valid?: boolean;
  retention_custody_return_verification_artifact_hash_valid?: boolean;
  retention_custody_retrieval_verification_artifact_hash_valid?: boolean;
  retention_custody_archive_verification_artifact_hash_valid?: boolean;
  retention_custody_closeout_verification_artifact_hash_valid?: boolean;
  custody_certification_statement_hash_valid?: boolean;
  custody_reconciliation_statement_hash_valid?: boolean;
  custody_inventory_statement_hash_valid?: boolean;
  custody_redeposit_statement_hash_valid?: boolean;
  custody_return_statement_hash_valid?: boolean;
  custody_retrieval_statement_hash_valid?: boolean;
  custody_archive_statement_hash_valid?: boolean;
  blocker_count?: number;
  warning_count?: number;
  blockers?: string[];
  warnings?: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionEvidenceBundleRetentionCustodyArchiveView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyArchiveVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyReturnView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyReturnVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyRedepositView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyRedepositVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyInventoryView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyInventoryVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyCertificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;
export type UiPaperExecutionEvidenceBundleRetentionCustodyCertificationVerificationView = UiPaperExecutionEvidenceBundleRetentionCustodyGenericView;

export type UiPaperExecutionEvidenceBundleExportVerificationView = {
  schema_version: string;
  tracking_id?: string | null;
  artifact_path: string;
  artifact_sha256?: string | null;
  generated_at_utc?: string | null;
  verification_status: string;
  trust_banner: string;
  source_export_manifest_artifact_path?: string | null;
  source_export_manifest_declared_sha256?: string | null;
  source_export_manifest_computed_sha256?: string | null;
  source_export_manifest_status?: string | null;
  source_export_manifest_trust_banner?: string | null;
  export_manifest_hash_valid: boolean;
  source_export_index_declared_sha256?: string | null;
  source_export_index_computed_sha256?: string | null;
  export_index_hash_valid: boolean;
  source_export_entry_count: number;
  source_export_digest_valid_entry_count: number;
  recomputed_export_entry_count: number;
  recomputed_export_digest_valid_entry_count: number;
  missing_entry_count: number;
  digest_mismatch_entry_count: number;
  blocker_count: number;
  warning_count: number;
  blockers: string[];
  warnings: string[];
  [key: string]: unknown;
};

export type UiPaperExecutionCockpitPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  no_live_trading: boolean;
  no_browser_orders: boolean;
  no_network_calls: boolean;
  mutation_authority: string;
  promotion_authority: string;
  execution_authority: string;
  paper_submission_authority: string;
  scan_root: string;
  broker_artifact_path?: string | null;
  degraded: string[];
  summary: {
    schema_version: string;
    broker_policy_status: string;
    latest_tracking_id?: string | null;
    latest_strategy_id?: string | null;
    candidate_intent_count: number;
    dry_run_ok_count: number;
    dry_run_blocked_count: number;
    journal_entry_count: number;
    dry_run_artifact_count: number;
    submission_artifact_count: number;
    submission_receipt_count?: number;
    latest_submission_receipt_at_utc?: string | null;
    latest_submission_guard_status?: string | null;
    latest_submission_evidence_freshness_status?: string | null;
    latest_submission_broker_order_id?: string | null;
    submission_guard_blocker_count?: number;
    position_snapshot_count?: number;
    latest_position_snapshot_at_utc?: string | null;
    order_status_artifact_count?: number;
    latest_order_status_at_utc?: string | null;
    latest_order_status?: string | null;
    latest_order_status_broker_order_id?: string | null;
    latest_order_status_filled_qty?: number | null;
    order_status_blocker_count?: number;
    position_reconciliation_status?: string | null;
    position_reconciliation_blocker_count?: number;
    position_reconciliation_warning_count?: number;
    latest_reconciled_symbol?: string | null;
    latest_reconciled_position_qty?: number | null;
    timeline_event_count?: number;
    timeline_stage_count?: number;
    timeline_blocker_count?: number;
    timeline_warning_count?: number;
    timeline_trusted_event_count?: number;
    latest_timeline_event_at_utc?: string | null;
    timeline_sequence_status?: string | null;
    evidence_bundle_count?: number;
    latest_evidence_bundle_at_utc?: string | null;
    latest_evidence_bundle_trust_banner?: string | null;
    latest_evidence_bundle_status?: string | null;
    latest_evidence_bundle_sha256?: string | null;
    evidence_bundle_blocker_count?: number;
    evidence_bundle_verification_count?: number;
    latest_evidence_bundle_verification_at_utc?: string | null;
    latest_evidence_bundle_verification_status?: string | null;
    latest_evidence_bundle_verification_trust_banner?: string | null;
    latest_evidence_bundle_verification_sha256?: string | null;
    evidence_bundle_verification_blocker_count?: number;
    evidence_bundle_drift_count?: number;
    latest_evidence_bundle_drift_at_utc?: string | null;
    latest_evidence_bundle_drift_status?: string | null;
    latest_evidence_bundle_drift_trust_banner?: string | null;
    latest_evidence_bundle_drift_sha256?: string | null;
    evidence_bundle_drift_blocker_count?: number;
    evidence_bundle_drift_new_source_count?: number;
    evidence_bundle_drift_removed_source_count?: number;
    evidence_bundle_rotation_count?: number;
    latest_evidence_bundle_rotation_at_utc?: string | null;
    latest_evidence_bundle_rotation_status?: string | null;
    latest_evidence_bundle_rotation_trust_banner?: string | null;
    latest_evidence_bundle_rotation_sha256?: string | null;
    evidence_bundle_rotation_blocker_count?: number;
    evidence_bundle_rotation_execution_count?: number;
    latest_evidence_bundle_rotation_execution_at_utc?: string | null;
    latest_evidence_bundle_rotation_execution_status?: string | null;
    latest_evidence_bundle_rotation_execution_trust_banner?: string | null;
    latest_evidence_bundle_rotation_execution_sha256?: string | null;
    evidence_bundle_rotation_execution_blocker_count?: number;
    evidence_bundle_attestation_count?: number;
    latest_evidence_bundle_attestation_at_utc?: string | null;
    latest_evidence_bundle_attestation_status?: string | null;
    latest_evidence_bundle_attestation_trust_banner?: string | null;
    latest_evidence_bundle_attestation_sha256?: string | null;
    evidence_bundle_attestation_blocker_count?: number;
    evidence_bundle_attestation_verification_count?: number;
    latest_evidence_bundle_attestation_verification_at_utc?: string | null;
    latest_evidence_bundle_attestation_verification_status?: string | null;
    latest_evidence_bundle_attestation_verification_trust_banner?: string | null;
    latest_evidence_bundle_attestation_verification_sha256?: string | null;
    evidence_bundle_attestation_verification_blocker_count?: number;
    evidence_bundle_closure_count?: number;
    latest_evidence_bundle_closure_at_utc?: string | null;
    latest_evidence_bundle_closure_status?: string | null;
    latest_evidence_bundle_closure_trust_banner?: string | null;
    latest_evidence_bundle_closure_sha256?: string | null;
    evidence_bundle_closure_blocker_count?: number;
    evidence_bundle_closure_verification_count?: number;
    latest_evidence_bundle_closure_verification_at_utc?: string | null;
    latest_evidence_bundle_closure_verification_status?: string | null;
    latest_evidence_bundle_closure_verification_trust_banner?: string | null;
    latest_evidence_bundle_closure_verification_sha256?: string | null;
    evidence_bundle_closure_verification_blocker_count?: number;
    evidence_bundle_export_manifest_count?: number;
    latest_evidence_bundle_export_manifest_at_utc?: string | null;
    latest_evidence_bundle_export_manifest_status?: string | null;
    latest_evidence_bundle_export_manifest_trust_banner?: string | null;
    latest_evidence_bundle_export_manifest_sha256?: string | null;
    evidence_bundle_export_manifest_blocker_count?: number;
    evidence_bundle_export_verification_count?: number;
    latest_evidence_bundle_export_verification_at_utc?: string | null;
    latest_evidence_bundle_export_verification_status?: string | null;
    latest_evidence_bundle_export_verification_trust_banner?: string | null;
    latest_evidence_bundle_export_verification_sha256?: string | null;
    evidence_bundle_export_verification_blocker_count?: number;
    latest_dry_run_artifact_at_utc?: string | null;
    latest_dry_run_source_selection_sha256?: string | null;
    selected_intent_dry_run_match?: boolean | null;
    selected_intent_dry_run_status?: string;
    selected_intent_count?: number;
    latest_selected_tracking_id?: string | null;
    latest_selected_intent_at_utc?: string | null;
    selected_intent_artifact_path?: string | null;
    broker_ready: boolean;
    tracking_present: boolean;
    paper_submission_capability: string;
    evidence_freshness_status?: string;
    evidence_freshness_blocker_count?: number;
    selected_intent_age_hours?: number | null;
    latest_linked_dry_run_age_hours?: number | null;
    latest_tracking_signal_age_hours?: number | null;
    [key: string]: unknown;
  };
  broker_status: Record<string, unknown>;
  latest_tracking?: Record<string, unknown> | null;
  candidate_intents: UiPaperExecutionIntentPreview[];
  selected_intent?: UiPaperExecutionIntentSelectionArtifact | null;
  dry_run_command_hint?: string | null;
  dry_run_results: Array<Record<string, unknown>>;
  freshness_gate?: Record<string, unknown>;
  journal_entries: UiPaperExecutionJournalEntry[];
  submission_receipts?: UiPaperExecutionSubmissionReceiptView[];
  order_statuses?: UiPaperExecutionOrderStatusView[];
  account_position_snapshot?: UiPaperExecutionAccountPositionSnapshot | null;
  position_reconciliation?: UiPaperExecutionPositionReconciliation;
  execution_timeline?: UiPaperExecutionTimelineEntry[];
  execution_timeline_summary?: UiPaperExecutionTimelineSummary;
  evidence_bundles?: UiPaperExecutionEvidenceBundleView[];
  latest_evidence_bundle?: UiPaperExecutionEvidenceBundleView | null;
  evidence_bundle_verifications?: UiPaperExecutionEvidenceBundleVerificationView[];
  latest_evidence_bundle_verification?: UiPaperExecutionEvidenceBundleVerificationView | null;
  evidence_bundle_drifts?: UiPaperExecutionEvidenceBundleDriftView[];
  latest_evidence_bundle_drift?: UiPaperExecutionEvidenceBundleDriftView | null;
  evidence_bundle_rotations?: UiPaperExecutionEvidenceBundleRotationView[];
  latest_evidence_bundle_rotation?: UiPaperExecutionEvidenceBundleRotationView | null;
  evidence_bundle_rotation_executions?: UiPaperExecutionEvidenceBundleRotationExecutionView[];
  latest_evidence_bundle_rotation_execution?: UiPaperExecutionEvidenceBundleRotationExecutionView | null;
  evidence_bundle_attestations?: UiPaperExecutionEvidenceBundleAttestationView[];
  latest_evidence_bundle_attestation?: UiPaperExecutionEvidenceBundleAttestationView | null;
  evidence_bundle_attestation_verifications?: UiPaperExecutionEvidenceBundleAttestationVerificationView[];
  latest_evidence_bundle_attestation_verification?: UiPaperExecutionEvidenceBundleAttestationVerificationView | null;
  evidence_bundle_closures?: UiPaperExecutionEvidenceBundleClosureView[];
  latest_evidence_bundle_closure?: UiPaperExecutionEvidenceBundleClosureView | null;
  evidence_bundle_closure_verifications?: UiPaperExecutionEvidenceBundleClosureVerificationView[];
  latest_evidence_bundle_closure_verification?: UiPaperExecutionEvidenceBundleClosureVerificationView | null;
  evidence_bundle_export_manifests?: UiPaperExecutionEvidenceBundleExportManifestView[];
  latest_evidence_bundle_export_manifest?: UiPaperExecutionEvidenceBundleExportManifestView | null;
  evidence_bundle_export_verifications?: UiPaperExecutionEvidenceBundleExportVerificationView[];
  latest_evidence_bundle_export_verification?: UiPaperExecutionEvidenceBundleExportVerificationView | null;
  evidence_bundle_retention_receipts?: UiPaperExecutionEvidenceBundleRetentionReceiptView[];
  latest_evidence_bundle_retention_receipt?: UiPaperExecutionEvidenceBundleRetentionReceiptView | null;
  evidence_bundle_retention_verifications?: UiPaperExecutionEvidenceBundleRetentionVerificationView[];
  latest_evidence_bundle_retention_verification?: UiPaperExecutionEvidenceBundleRetentionVerificationView | null;
  evidence_bundle_retention_signoffs?: UiPaperExecutionEvidenceBundleRetentionSignoffView[];
  latest_evidence_bundle_retention_signoff?: UiPaperExecutionEvidenceBundleRetentionSignoffView | null;
  evidence_bundle_retention_signoff_verifications?: UiPaperExecutionEvidenceBundleRetentionSignoffVerificationView[];
  latest_evidence_bundle_retention_signoff_verification?: UiPaperExecutionEvidenceBundleRetentionSignoffVerificationView | null;
  evidence_bundle_retention_handoffs?: UiPaperExecutionEvidenceBundleRetentionHandoffView[];
  latest_evidence_bundle_retention_handoff?: UiPaperExecutionEvidenceBundleRetentionHandoffView | null;
  evidence_bundle_retention_handoff_verifications?: UiPaperExecutionEvidenceBundleRetentionHandoffVerificationView[];
  latest_evidence_bundle_retention_handoff_verification?: UiPaperExecutionEvidenceBundleRetentionHandoffVerificationView | null;
  evidence_bundle_retention_handoff_acceptances?: UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceView[];
  latest_evidence_bundle_retention_handoff_acceptance?: UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceView | null;
  evidence_bundle_retention_handoff_acceptance_verifications?: UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceVerificationView[];
  latest_evidence_bundle_retention_handoff_acceptance_verification?: UiPaperExecutionEvidenceBundleRetentionHandoffAcceptanceVerificationView | null;
  evidence_bundle_retention_custody_registers?: UiPaperExecutionEvidenceBundleRetentionCustodyRegisterView[];
  latest_evidence_bundle_retention_custody_register?: UiPaperExecutionEvidenceBundleRetentionCustodyRegisterView | null;
  evidence_bundle_retention_custody_register_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyRegisterVerificationView[];
  latest_evidence_bundle_retention_custody_register_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyRegisterVerificationView | null;
  evidence_bundle_retention_custody_seals?: UiPaperExecutionEvidenceBundleRetentionCustodySealView[];
  latest_evidence_bundle_retention_custody_seal?: UiPaperExecutionEvidenceBundleRetentionCustodySealView | null;
  evidence_bundle_retention_custody_seal_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodySealVerificationView[];
  latest_evidence_bundle_retention_custody_seal_verification?: UiPaperExecutionEvidenceBundleRetentionCustodySealVerificationView | null;
  evidence_bundle_retention_custody_audits?: UiPaperExecutionEvidenceBundleRetentionCustodyAuditView[];
  latest_evidence_bundle_retention_custody_audit?: UiPaperExecutionEvidenceBundleRetentionCustodyAuditView | null;
  evidence_bundle_retention_custody_audit_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyAuditVerificationView[];
  latest_evidence_bundle_retention_custody_audit_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyAuditVerificationView | null;
  evidence_bundle_retention_custody_continuities?: UiPaperExecutionEvidenceBundleRetentionCustodyContinuityView[];
  latest_evidence_bundle_retention_custody_continuity?: UiPaperExecutionEvidenceBundleRetentionCustodyContinuityView | null;
  evidence_bundle_retention_custody_continuity_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyContinuityVerificationView[];
  latest_evidence_bundle_retention_custody_continuity_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyContinuityVerificationView | null;
  evidence_bundle_retention_custody_reviews?: UiPaperExecutionEvidenceBundleRetentionCustodyReviewView[];
  latest_evidence_bundle_retention_custody_review?: UiPaperExecutionEvidenceBundleRetentionCustodyReviewView | null;
  evidence_bundle_retention_custody_review_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyReviewVerificationView[];
  latest_evidence_bundle_retention_custody_review_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyReviewVerificationView | null;
  evidence_bundle_retention_custody_renewals?: UiPaperExecutionEvidenceBundleRetentionCustodyRenewalView[];
  latest_evidence_bundle_retention_custody_renewal?: UiPaperExecutionEvidenceBundleRetentionCustodyRenewalView | null;
  evidence_bundle_retention_custody_renewal_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyRenewalVerificationView[];
  latest_evidence_bundle_retention_custody_renewal_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyRenewalVerificationView | null;
  evidence_bundle_retention_custody_schedules?: UiPaperExecutionEvidenceBundleRetentionCustodyScheduleView[];
  latest_evidence_bundle_retention_custody_schedule?: UiPaperExecutionEvidenceBundleRetentionCustodyScheduleView | null;
  evidence_bundle_retention_custody_schedule_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyScheduleVerificationView[];
  latest_evidence_bundle_retention_custody_schedule_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyScheduleVerificationView | null;
  evidence_bundle_retention_custody_notices?: UiPaperExecutionEvidenceBundleRetentionCustodyNoticeView[];
  latest_evidence_bundle_retention_custody_notice?: UiPaperExecutionEvidenceBundleRetentionCustodyNoticeView | null;
  evidence_bundle_retention_custody_notice_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyNoticeVerificationView[];
  latest_evidence_bundle_retention_custody_notice_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyNoticeVerificationView | null;
  evidence_bundle_retention_custody_acknowledgments?: UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentView[];
  latest_evidence_bundle_retention_custody_acknowledgment?: UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentView | null;
  evidence_bundle_retention_custody_acknowledgment_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentVerificationView[];
  latest_evidence_bundle_retention_custody_acknowledgment_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyAcknowledgmentVerificationView | null;
  evidence_bundle_retention_custody_completions?: UiPaperExecutionEvidenceBundleRetentionCustodyCompletionView[];
  latest_evidence_bundle_retention_custody_completion?: UiPaperExecutionEvidenceBundleRetentionCustodyCompletionView | null;
  evidence_bundle_retention_custody_completion_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyCompletionVerificationView[];
  latest_evidence_bundle_retention_custody_completion_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyCompletionVerificationView | null;
  evidence_bundle_retention_custody_closeouts?: UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutView[];
  latest_evidence_bundle_retention_custody_closeout?: UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutView | null;
  evidence_bundle_retention_custody_closeout_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutVerificationView[];
  latest_evidence_bundle_retention_custody_closeout_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyCloseoutVerificationView | null;
  evidence_bundle_retention_custody_archives?: UiPaperExecutionEvidenceBundleRetentionCustodyArchiveView[];
  latest_evidence_bundle_retention_custody_archive?: UiPaperExecutionEvidenceBundleRetentionCustodyArchiveView | null;
  evidence_bundle_retention_custody_archive_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyArchiveVerificationView[];
  latest_evidence_bundle_retention_custody_archive_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyArchiveVerificationView | null;
  evidence_bundle_retention_custody_retrievals?: UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalView[];
  latest_evidence_bundle_retention_custody_retrieval?: UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalView | null;
  evidence_bundle_retention_custody_retrieval_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalVerificationView[];
  latest_evidence_bundle_retention_custody_retrieval_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyRetrievalVerificationView | null;
  evidence_bundle_retention_custody_returns?: UiPaperExecutionEvidenceBundleRetentionCustodyReturnView[];
  latest_evidence_bundle_retention_custody_return?: UiPaperExecutionEvidenceBundleRetentionCustodyReturnView | null;
  evidence_bundle_retention_custody_return_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyReturnVerificationView[];
  latest_evidence_bundle_retention_custody_return_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyReturnVerificationView | null;
  evidence_bundle_retention_custody_redeposits?: UiPaperExecutionEvidenceBundleRetentionCustodyRedepositView[];
  latest_evidence_bundle_retention_custody_redeposit?: UiPaperExecutionEvidenceBundleRetentionCustodyRedepositView | null;
  evidence_bundle_retention_custody_redeposit_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyRedepositVerificationView[];
  latest_evidence_bundle_retention_custody_redeposit_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyRedepositVerificationView | null;
  evidence_bundle_retention_custody_inventories?: UiPaperExecutionEvidenceBundleRetentionCustodyInventoryView[];
  latest_evidence_bundle_retention_custody_inventory?: UiPaperExecutionEvidenceBundleRetentionCustodyInventoryView | null;
  evidence_bundle_retention_custody_inventory_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyInventoryVerificationView[];
  latest_evidence_bundle_retention_custody_inventory_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyInventoryVerificationView | null;
  evidence_bundle_retention_custody_reconciliations?: UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationView[];
  latest_evidence_bundle_retention_custody_reconciliation?: UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationView | null;
  evidence_bundle_retention_custody_reconciliation_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationVerificationView[];
  latest_evidence_bundle_retention_custody_reconciliation_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyReconciliationVerificationView | null;
  evidence_bundle_retention_custody_certifications?: UiPaperExecutionEvidenceBundleRetentionCustodyCertificationView[];
  latest_evidence_bundle_retention_custody_certification?: UiPaperExecutionEvidenceBundleRetentionCustodyCertificationView | null;
  evidence_bundle_retention_custody_certification_verifications?: UiPaperExecutionEvidenceBundleRetentionCustodyCertificationVerificationView[];
  latest_evidence_bundle_retention_custody_certification_verification?: UiPaperExecutionEvidenceBundleRetentionCustodyCertificationVerificationView | null;
  recommended_actions: string[];
  disclaimer: string;
};

export type UiStrategyGraveyardPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  no_live_trading: boolean;
  mutation_authority: string;
  promotion_authority: string;
  execution_authority: string;
  scan_root: string;
  index_path: string;
  degraded: string[];
  summary: Record<string, unknown>;
  entries: Array<Record<string, unknown>>;
  disclaimer: string;
};

export type UiDailyOperatorRunComponent = {
  schema_version: string;
  component_id: string;
  title: string;
  source_route: string;
  status: string;
  posture: string;
  summary: Record<string, unknown>;
  warnings: string[];
  blockers: string[];
  recommended_actions: string[];
  evidence_refs: Record<string, unknown>[];
};

export type UiDailyOperatorRunPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  no_live_trading: boolean;
  no_broker_orders: boolean;
  no_order_controls: boolean;
  mutation_authority: string;
  promotion_authority: string;
  execution_authority: string;
  status: string;
  trust_banner: string;
  summary: Record<string, unknown>;
  components: UiDailyOperatorRunComponent[];
  warnings: string[];
  blockers: string[];
  recommended_actions: string[];
  source_routes: string[];
  disclaimer: string;
};

export type UiStrategyIntakeRequest = {
  strategy_name: string;
  thesis: string;
  target_universe: string;
  intended_horizon: string;
  expected_edge: string;
  required_evidence_class?: string;
  data_dependencies?: string[];
  feature_dependencies?: string[];
  source_registry_references?: string[];
  falsification_rules?: string[];
  risk_assumptions?: string[];
  tags?: string[];
  evaluation_plan?: Record<string, unknown>;
  operator_id?: string;
  idempotency_key?: string | null;
};

export type UiStrategyIntakeReceipt = {
  schema_version: string;
  generated_at_utc: string;
  accepted: boolean;
  intake_id: string;
  proposal_id: string;
  artifact_path: string;
  artifact_sha256: string;
  index_path: string;
  read_plane_route: string;
  authority_boundary: string;
  promotion_authority: string;
  execution_authority: string;
  requires_projection_refresh: boolean;
  idempotency_status: string;
  duplicate_of_intake_id?: string | null;
  summary_line: string;
  authorization?: Record<string, unknown>;
};

export type UiStrategyIntakeIndexEntry = {
  intake_id: string;
  proposal_id: string;
  strategy_name: string;
  created_at_utc: string;
  operator_id: string;
  target_universe: string;
  intended_horizon: string;
  readiness_state: string;
  artifact_path: string;
  artifact_sha256: string;
  tags?: string[];
};

export type UiStrategyIntakeLatestPayload = {
  schema_version: string;
  generated_at_utc: string;
  read_plane_only: boolean;
  no_live_trading: boolean;
  authority_boundary: string;
  scan_root: string;
  index_path: string;
  degraded: string[];
  latest: {
    schema_version: string;
    generated_at_utc: string;
    read_plane_only: boolean;
    no_live_trading: boolean;
    authority_boundary: string;
    intake_count: number;
    entries: UiStrategyIntakeIndexEntry[];
  };
};

export function deriveWorkboardDegradedReason(payload: UiWorkboardPayload): string | null {
  const fresh = (payload.stats?.freshness_state || "UNKNOWN").toUpperCase();
  if (fresh === "STALE" || fresh === "DEGRADED") {
    return `Workboard projection freshness is ${payload.stats.freshness_state}.`;
  }
  const matState = String(payload.materialization?.materialization_state || "").toUpperCase();
  if (matState && matState !== "READY" && matState !== "UNKNOWN" && matState !== "") {
    return `Materialization state: ${payload.materialization.materialization_state}.`;
  }
  return null;
}
