"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffEscalationBoard } from "@/hooks/useUiSemanticValidatorHandoffEscalationBoard";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffEscalationBoard({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF ESCALATION BOARD</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF ESCALATION BOARD</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/escalation-board · read-only escalation lanes derived from action queue</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Escalation inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"escalations",v:String(s.escalation_count_returned??0)},{k:"blockers",v:String(s.immediate_blocker_count??0)},{k:"external",v:String(s.external_artifact_needed_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"ack",v:q.data.escalation_acknowledgment_authority},{k:"action_execute",v:q.data.action_execution_authority},{k:"artifact_write",v:q.data.external_artifact_write_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"escalation",v:String(q.data.latest?.escalation_id??"—")},{k:"lane",v:String(q.data.latest?.escalation_lane??"—")},{k:"owner",v:String(q.data.latest?.owner_hint??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")}]}/></Pane></PaneGrid><Pane title="Escalation cards"><table className="term-table"><thead><tr><th>lane</th><th>priority</th><th>trust</th><th>owner</th><th>experiment</th><th>action</th></tr></thead><tbody>{q.data.escalation_cards.map((r,i)=><tr key={`${r.escalation_id}:${i}`}><td><StatusBadge raw={r.escalation_lane}/></td><td><StatusBadge raw={r.priority}/></td><td><StatusBadge raw={r.trust_banner}/></td><td><code>{r.owner_hint}</code></td><td><code>{r.experiment_id??"—"}</code></td><td><code>{r.operator_action}</code></td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/escalation-board JSON" data={q.data}/></>}</div>; }
