"""Root contract exports resolved lazily."""
from __future__ import annotations

from importlib import import_module

_EXPORT_MAP = {
    'OracleMorningAttestation': 'strategy_validator.contracts.advisory',
    'OracleRegimeTransition': 'strategy_validator.contracts.advisory',
    'OracleSensorIngestionInput': 'strategy_validator.contracts.advisory',
    'OracleStrategicFusionReport': 'strategy_validator.contracts.advisory',
    'StrategyHealthPosteriorReport': 'strategy_validator.contracts.analytics',
    'OracleResearchPriorityReport': 'strategy_validator.contracts.analytics',
    'OracleThesisGraphNode': 'strategy_validator.contracts.analytics',
    'OracleThesisGraphEdge': 'strategy_validator.contracts.analytics',
    'OracleThesisGraphReport': 'strategy_validator.contracts.analytics',
    'OracleStrategicTensionItem': 'strategy_validator.contracts.analytics',
    'OracleStrategicTensionReport': 'strategy_validator.contracts.analytics',
    'ApplicationCommand': 'strategy_validator.contracts.application',
    'ApplicationResult': 'strategy_validator.contracts.application',
    'ProjectionQueryCommand': 'strategy_validator.contracts.application',
    'ProjectionQueryResult': 'strategy_validator.contracts.application',
    'RebuildProjectionCommand': 'strategy_validator.contracts.application',
    'RebuildProjectionResult': 'strategy_validator.contracts.application',
    'OracleBriefingPackReport': 'strategy_validator.contracts.briefing',
    'DecisionRecord': 'strategy_validator.contracts.decision_record',
    'OracleIncidentPackReport': 'strategy_validator.contracts.diagnostics',
    'OracleOperatorDiagnosticReport': 'strategy_validator.contracts.diagnostics',
    'OracleStatusPackReport': 'strategy_validator.contracts.diagnostics',
    'OracleConstitutionalGateReport': 'strategy_validator.contracts.doctrine',
    'OracleDoctrineDriftReport': 'strategy_validator.contracts.doctrine',
    'OracleDoctrineLineageIndex': 'strategy_validator.contracts.doctrine',
    'OracleDoctrineLineageVerification': 'strategy_validator.contracts.doctrine',
    'OracleWeeklyDigestReport': 'strategy_validator.contracts.doctrine',
    'OracleDerivedViewCheckpointMetadata': 'strategy_validator.contracts.event_views',
    'OracleDerivedViewReport': 'strategy_validator.contracts.event_views',
    'OracleEventCheckpointManifest': 'strategy_validator.contracts.event_views',
    'OracleEventCheckpointVerification': 'strategy_validator.contracts.event_views',
    'OracleEventLogEntry': 'strategy_validator.contracts.event_views',
    'OracleEventLogQuerySpec': 'strategy_validator.contracts.event_views',
    'EventEnvelope': 'strategy_validator.contracts.events',
    'FeatureLineageRecord': 'strategy_validator.contracts.feature_lineage',
    'OracleGovernanceActionItem': 'strategy_validator.contracts.governance',
    'OracleGovernanceClaimActionItem': 'strategy_validator.contracts.governance',
    'OracleGovernanceFingerprint': 'strategy_validator.contracts.governance',
    'OracleOperatorDiagnosticReport': 'strategy_validator.contracts.governance',
    'OracleOperatorWorkboardItemReport': 'strategy_validator.contracts.governance',
    'OracleOperatorWorkboardReport': 'strategy_validator.contracts.governance',
    'OracleTrustExplanationReport': 'strategy_validator.contracts.governance',
    'KernelDecisionReport': 'strategy_validator.contracts.kernel_reports',
    'OracleMemoryLaneEntry': 'strategy_validator.contracts.memory',
    'OracleMemoryLaneSummary': 'strategy_validator.contracts.memory',
    'OracleMemoryReviewReport': 'strategy_validator.contracts.memory',
    'OracleIncidentPackArtifact': 'strategy_validator.contracts.operator_packs',
    'OracleIncidentPackReport': 'strategy_validator.contracts.operator_packs',
    'OracleStatusPackReport': 'strategy_validator.contracts.operator_packs',
    'OracleStatusPackSection': 'strategy_validator.contracts.operator_packs',
    'OperatorGovernanceReport': 'strategy_validator.contracts.operator_reports',
    'ClosureReleaseAttestation': 'strategy_validator.contracts.operational',
    'ClosureSnapshotManifest': 'strategy_validator.contracts.operational',
    'ClosureSnapshotVerification': 'strategy_validator.contracts.operational',
    'GovernedExceptionMemo': 'strategy_validator.contracts.operational',
    'GovernedExceptionVerification': 'strategy_validator.contracts.operational',
    'ControlledRolloutBundle': 'strategy_validator.contracts.operational',
    'ControlledRolloutRules': 'strategy_validator.contracts.operational',
    'DailyOperationsChecklist': 'strategy_validator.contracts.operational',
    'RuntimeEvidenceReview': 'strategy_validator.contracts.operational',
    'KeyedHostFingerprint': 'strategy_validator.contracts.operational',
    'RolloutScope': 'strategy_validator.contracts.operational',
    'ReleaseReadinessReport': 'strategy_validator.contracts.operator_reports',
    'ProjectionSnapshotManifest': 'strategy_validator.contracts.projection_snapshots',
    'ProposalManifest': 'strategy_validator.contracts.proposal_manifest',
    'PublicationArtifactRecord': 'strategy_validator.contracts.publications',
    'OracleOpportunityQueueItem': 'strategy_validator.contracts.research',
    'OracleOpportunityQueueReport': 'strategy_validator.contracts.research',
    'OracleResearchExecutionMemoryItem': 'strategy_validator.contracts.research',
    'OracleResearchExecutionMemoryReport': 'strategy_validator.contracts.research',
    'OracleResearchPriorityItem': 'strategy_validator.contracts.research',
    'OracleResearchPriorityReport': 'strategy_validator.contracts.research',
    'OracleThesisGraphEdge': 'strategy_validator.contracts.research',
    'OracleThesisGraphNode': 'strategy_validator.contracts.research',
    'OracleThesisGraphReport': 'strategy_validator.contracts.research',
    'OracleThesisMemoryItem': 'strategy_validator.contracts.research',
    'OracleThesisMemoryReport': 'strategy_validator.contracts.research',
    'TemporalSourceRecord': 'strategy_validator.contracts.oracle_temporal',
    'TemporalSemanticExtractionDayRequest': 'strategy_validator.contracts.oracle_temporal',
    'TemporalSemanticExtractionBatchRequest': 'strategy_validator.contracts.oracle_temporal',
    'TemporalSemanticBatchManifest': 'strategy_validator.contracts.oracle_temporal',
    'TemporalSemanticBatchVerification': 'strategy_validator.contracts.oracle_temporal',
    'TemporalProviderArtifactManifest': 'strategy_validator.contracts.oracle_temporal',
    'TemporalEventLogAppendDayResult': 'strategy_validator.contracts.oracle_temporal',
    'TemporalEventLogAppendBatchResult': 'strategy_validator.contracts.oracle_temporal',
    'TemporalCanonicalizationBatchResult': 'strategy_validator.contracts.oracle_temporal',
    'TemporalCanonicalizationDayResult': 'strategy_validator.contracts.oracle_temporal',
    'TemporalLaneStatus': 'strategy_validator.contracts.oracle_temporal',
    'OpenBBTemporalSensorIngressDayResult': 'strategy_validator.contracts.oracle_temporal',
    'OpenBBTemporalSensorIngressBatchResult': 'strategy_validator.contracts.oracle_temporal',
    'SourceRegistryRecord': 'strategy_validator.contracts.source_registry',
    'OracleScenarioLabReport': 'strategy_validator.contracts.strategic',
    'OracleScenarioOutcome': 'strategy_validator.contracts.strategic',
    'OracleScenarioPlanInput': 'strategy_validator.contracts.strategic',
    'OracleScenarioShock': 'strategy_validator.contracts.strategic',
    'OracleStrategicBriefingReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicBriefingSection': 'strategy_validator.contracts.strategic',
    'OracleStrategicCampaignExecutionReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicCampaignItem': 'strategy_validator.contracts.strategic',
    'OracleStrategicCampaignReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicFusionReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicInterventionReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicNarrativeReport': 'strategy_validator.contracts.strategic',
    'OracleStrategicTensionReport': 'strategy_validator.contracts.strategic',
    'OracleStrategyCohortReport': 'strategy_validator.contracts.strategic',
    'OracleRegimeTransitionSignalReport': 'strategy_validator.contracts.transitions',
    'OracleContradictionResolutionReport': 'strategy_validator.contracts.transitions',
    'OracleStrategicInterventionReport': 'strategy_validator.contracts.transitions',
    'TribunalChallengePacket': 'strategy_validator.contracts.tribunal',
    'TribunalOpinion': 'strategy_validator.contracts.tribunal',
}

__all__ = sorted(_EXPORT_MAP)

def __getattr__(name: str):
    module_name = _EXPORT_MAP.get(name)
    if module_name is None:
        raise AttributeError(name)
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value

def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
