"""Grouped lazy exports for operator-state and UI contract surfaces."""
from __future__ import annotations

EXPORTS_OPERATOR_UI = {
    'ControlPlaneEventEnvelope': 'strategy_validator.contracts.control_plane_event_envelope',
    'build_control_plane_event_envelope': 'strategy_validator.contracts.control_plane_event_envelope',
    'verify_control_plane_event_envelope': 'strategy_validator.contracts.control_plane_event_envelope',
    'AppendOperatorActionEventRequest': 'strategy_validator.contracts.operator_action_journal',
    'OperatorActionEvent': 'strategy_validator.contracts.operator_action_journal',
    'ReadOperatorActionEventsRequest': 'strategy_validator.contracts.operator_action_journal',
    'OracleOperatorQueueQueryRequest': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorQueueQueryResult': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorQueueQueryWorkItem': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorQueueSnapshot': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorQueueSnapshotRequest': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorWorkItem': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorWorkboard': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorWorkboardEntry': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorWorkboardRequest': 'strategy_validator.contracts.operator_queue',
    'OracleOperatorControlPlaneBundle': 'strategy_validator.contracts.operator_control_plane_bundle',
    'OracleOperatorControlPlaneBundleRequest': 'strategy_validator.contracts.operator_control_plane_bundle',
    'UiMutationAuthContext': 'strategy_validator.contracts.ui_command_mutation',
    'UiOperatorCommandRequest': 'strategy_validator.contracts.ui_command_mutation',
    'UiOperatorQueueQueryPayload': 'strategy_validator.contracts.ui_workboard_dashboard',
    'UiOperatorWorkboardPayload': 'strategy_validator.contracts.ui_workboard_dashboard',
    'UiWorkboardDashboardPayload': 'strategy_validator.contracts.ui_workboard_dashboard',
    'UiWorkboardDashboardStats': 'strategy_validator.contracts.ui_workboard_dashboard',
    'UiWorkboardExportDocument': 'strategy_validator.contracts.ui_workboard_export',
    'UiWorkboardExportIndex': 'strategy_validator.contracts.ui_workboard_export',
    'UiWorkboardExportPayload': 'strategy_validator.contracts.ui_workboard_export',
    'UiWorkboardOperationalTruth': 'strategy_validator.contracts.ui_workboard_export',
    'UiWorkboardQueueProvenance': 'strategy_validator.contracts.ui_workboard_export',
    'UiWorkboardQuery': 'strategy_validator.contracts.ui_workboard_query',
    'UiEvidenceQuery': 'strategy_validator.contracts.ui_detail_queries',
    'UiPackDetailQuery': 'strategy_validator.contracts.ui_detail_queries',
    'UiBurninQuery': 'strategy_validator.contracts.ui_runtime_queries',
    'UiRuntimeQuery': 'strategy_validator.contracts.ui_runtime_queries',
    'UiTribunalQuery': 'strategy_validator.contracts.ui_runtime_queries',
}
