from __future__ import annotations

from strategy_validator.contracts.oracle_strategic_fusion import (
    OracleStrategicPosture,
    OracleStrategicTransitionClassification,
    OracleStrategicQueueKind,
    OracleThesisCurrentState,
    OracleThesisEvolutionState,
    OracleScenarioKind,
    OracleStrategyCohortBucket,
    OracleResearchPriorityKind,
    StrategyRegimeFit,
    OracleSensorRawMacroInput,
    OracleSensorRawSemanticInput,
    OracleSensorRawMicrostructureInput,
    OracleSensorIngestionInput,
    OracleSensorIngestionReport,
    OracleStrategicFusionReport,
    StrategyPosteriorState,
    StrategyHealthPosteriorReport,
    OracleRegimeTransitionSignalReport,
    OracleOpportunityQueueItem,
    OracleOpportunityQueueReport,
)

from strategy_validator.contracts.oracle_strategic_programs import (
    OracleStrategicCampaignStep,
    OracleStrategicCampaignItem,
    OracleStrategicCampaignReport,
    OracleStrategicCampaignExecutionUpdateItem,
    OracleStrategicCampaignExecutionInput,
    OracleStrategicCampaignExecutionItem,
    OracleStrategicCampaignExecutionReport,
    OracleStrategicBriefingSection,
    OracleStrategicBriefingReport,
    OracleStrategicStackEvidenceManifest,
    OracleStrategicArtifactEvidenceManifest,
    OracleStrategicArtifactEvidenceVerification,
    OracleStrategicStackEvidenceVerification,
    OracleScenarioShock,
    OracleScenarioPlanInput,
    OracleScenarioOutcome,
    OracleScenarioLabReport,
    OracleStrategyCohortItem,
    OracleStrategyCohortReport,
)

from strategy_validator.contracts.oracle_strategic_memory import (
    OracleThesisMemoryItem,
    OracleThesisMemoryReport,
    OracleDoctrineAdaptationItem,
    OracleDoctrineAdaptationReport,
    OracleResearchPriorityItem,
    OracleResearchPriorityReport,
    OracleInvestigationOutcomeInputItem,
    OracleInvestigationOutcomeInput,
    OracleResearchExecutionMemoryItem,
    OracleResearchExecutionMemoryReport,
    OracleThesisGraphNode,
    OracleThesisGraphEdge,
    OracleThesisGraphReport,
    OracleStrategicTensionItem,
    OracleStrategicTensionReport,
    OracleStrategicNarrativeItem,
    OracleStrategicNarrativeReport,
    OracleStrategicMemoryPoint,
    OracleStrategicDriverDriftItem,
    OracleStrategicMemoryHorizonReport,
    OracleContradictionResolutionItem,
    OracleContradictionResolutionReport,
    OracleStrategicInterventionItem,
    OracleStrategicInterventionReport,
)
