"""Paper execution cockpit summary contracts."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class PaperExecutionSummary(BaseModel):
    schema_version: Literal["paper_execution_summary/v1"] = "paper_execution_summary/v1"
    broker_policy_status: str
    latest_tracking_id: str | None = None
    latest_strategy_id: str | None = None
    candidate_intent_count: int = 0
    dry_run_ok_count: int = 0
    dry_run_blocked_count: int = 0
    journal_entry_count: int = 0
    dry_run_artifact_count: int = 0
    submission_artifact_count: int = 0
    submission_receipt_count: int = 0
    latest_submission_receipt_at_utc: str | None = None
    latest_submission_guard_status: str | None = None
    latest_submission_evidence_freshness_status: str | None = None
    latest_submission_broker_order_id: str | None = None
    submission_guard_blocker_count: int = 0
    position_snapshot_count: int = 0
    latest_position_snapshot_at_utc: str | None = None
    order_status_artifact_count: int = 0
    latest_order_status_at_utc: str | None = None
    latest_order_status: str | None = None
    latest_order_status_broker_order_id: str | None = None
    latest_order_status_filled_qty: float | None = None
    order_status_blocker_count: int = 0
    position_reconciliation_status: str | None = None
    position_reconciliation_blocker_count: int = 0
    position_reconciliation_warning_count: int = 0
    latest_reconciled_symbol: str | None = None
    latest_reconciled_position_qty: float | None = None
    timeline_event_count: int = 0
    timeline_stage_count: int = 0
    timeline_blocker_count: int = 0
    timeline_warning_count: int = 0
    timeline_trusted_event_count: int = 0
    latest_timeline_event_at_utc: str | None = None
    timeline_sequence_status: str | None = None
    evidence_bundle_count: int = 0
    latest_evidence_bundle_at_utc: str | None = None
    latest_evidence_bundle_trust_banner: str | None = None
    latest_evidence_bundle_status: str | None = None
    latest_evidence_bundle_sha256: str | None = None
    evidence_bundle_blocker_count: int = 0
    evidence_bundle_verification_count: int = 0
    latest_evidence_bundle_verification_at_utc: str | None = None
    latest_evidence_bundle_verification_status: str | None = None
    latest_evidence_bundle_verification_trust_banner: str | None = None
    latest_evidence_bundle_verification_sha256: str | None = None
    evidence_bundle_verification_blocker_count: int = 0
    evidence_bundle_drift_count: int = 0
    latest_evidence_bundle_drift_at_utc: str | None = None
    latest_evidence_bundle_drift_status: str | None = None
    latest_evidence_bundle_drift_trust_banner: str | None = None
    latest_evidence_bundle_drift_sha256: str | None = None
    evidence_bundle_drift_blocker_count: int = 0
    evidence_bundle_drift_new_source_count: int = 0
    evidence_bundle_drift_removed_source_count: int = 0
    evidence_bundle_rotation_count: int = 0
    latest_evidence_bundle_rotation_at_utc: str | None = None
    latest_evidence_bundle_rotation_status: str | None = None
    latest_evidence_bundle_rotation_trust_banner: str | None = None
    latest_evidence_bundle_rotation_sha256: str | None = None
    evidence_bundle_rotation_blocker_count: int = 0
    evidence_bundle_rotation_execution_count: int = 0
    latest_evidence_bundle_rotation_execution_at_utc: str | None = None
    latest_evidence_bundle_rotation_execution_status: str | None = None
    latest_evidence_bundle_rotation_execution_trust_banner: str | None = None
    latest_evidence_bundle_rotation_execution_sha256: str | None = None
    evidence_bundle_rotation_execution_blocker_count: int = 0
    evidence_bundle_attestation_count: int = 0
    latest_evidence_bundle_attestation_at_utc: str | None = None
    latest_evidence_bundle_attestation_status: str | None = None
    latest_evidence_bundle_attestation_trust_banner: str | None = None
    latest_evidence_bundle_attestation_sha256: str | None = None
    evidence_bundle_attestation_blocker_count: int = 0
    evidence_bundle_attestation_verification_count: int = 0
    latest_evidence_bundle_attestation_verification_at_utc: str | None = None
    latest_evidence_bundle_attestation_verification_status: str | None = None
    latest_evidence_bundle_attestation_verification_trust_banner: str | None = None
    latest_evidence_bundle_attestation_verification_sha256: str | None = None
    evidence_bundle_attestation_verification_blocker_count: int = 0
    evidence_bundle_closure_count: int = 0
    latest_evidence_bundle_closure_at_utc: str | None = None
    latest_evidence_bundle_closure_status: str | None = None
    latest_evidence_bundle_closure_trust_banner: str | None = None
    latest_evidence_bundle_closure_sha256: str | None = None
    evidence_bundle_closure_blocker_count: int = 0
    evidence_bundle_closure_verification_count: int = 0
    latest_evidence_bundle_closure_verification_at_utc: str | None = None
    latest_evidence_bundle_closure_verification_status: str | None = None
    latest_evidence_bundle_closure_verification_trust_banner: str | None = None
    latest_evidence_bundle_closure_verification_sha256: str | None = None
    evidence_bundle_closure_verification_blocker_count: int = 0
    evidence_bundle_export_manifest_count: int = 0
    latest_evidence_bundle_export_manifest_at_utc: str | None = None
    latest_evidence_bundle_export_manifest_status: str | None = None
    latest_evidence_bundle_export_manifest_trust_banner: str | None = None
    latest_evidence_bundle_export_manifest_sha256: str | None = None
    evidence_bundle_export_manifest_blocker_count: int = 0
    evidence_bundle_export_verification_count: int = 0
    latest_evidence_bundle_export_verification_at_utc: str | None = None
    latest_evidence_bundle_export_verification_status: str | None = None
    latest_evidence_bundle_export_verification_trust_banner: str | None = None
    latest_evidence_bundle_export_verification_sha256: str | None = None
    evidence_bundle_export_verification_blocker_count: int = 0
    evidence_bundle_retention_receipt_count: int = 0
    latest_evidence_bundle_retention_receipt_at_utc: str | None = None
    latest_evidence_bundle_retention_receipt_status: str | None = None
    latest_evidence_bundle_retention_receipt_trust_banner: str | None = None
    latest_evidence_bundle_retention_receipt_sha256: str | None = None
    evidence_bundle_retention_receipt_blocker_count: int = 0
    evidence_bundle_retention_verification_count: int = 0
    latest_evidence_bundle_retention_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_verification_status: str | None = None
    latest_evidence_bundle_retention_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_verification_sha256: str | None = None
    evidence_bundle_retention_verification_blocker_count: int = 0
    evidence_bundle_retention_signoff_count: int = 0
    latest_evidence_bundle_retention_signoff_at_utc: str | None = None
    latest_evidence_bundle_retention_signoff_status: str | None = None
    latest_evidence_bundle_retention_signoff_trust_banner: str | None = None
    latest_evidence_bundle_retention_signoff_sha256: str | None = None
    evidence_bundle_retention_signoff_blocker_count: int = 0
    evidence_bundle_retention_signoff_verification_count: int = 0
    latest_evidence_bundle_retention_signoff_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_signoff_verification_status: str | None = None
    latest_evidence_bundle_retention_signoff_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_signoff_verification_sha256: str | None = None
    evidence_bundle_retention_signoff_verification_blocker_count: int = 0
    evidence_bundle_retention_handoff_count: int = 0
    latest_evidence_bundle_retention_handoff_at_utc: str | None = None
    latest_evidence_bundle_retention_handoff_status: str | None = None
    latest_evidence_bundle_retention_handoff_trust_banner: str | None = None
    latest_evidence_bundle_retention_handoff_sha256: str | None = None
    evidence_bundle_retention_handoff_blocker_count: int = 0
    evidence_bundle_retention_handoff_verification_count: int = 0
    latest_evidence_bundle_retention_handoff_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_handoff_verification_status: str | None = None
    latest_evidence_bundle_retention_handoff_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_handoff_verification_sha256: str | None = None
    evidence_bundle_retention_handoff_verification_blocker_count: int = 0
    evidence_bundle_retention_handoff_acceptance_count: int = 0
    latest_evidence_bundle_retention_handoff_acceptance_at_utc: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_status: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_trust_banner: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_sha256: str | None = None
    evidence_bundle_retention_handoff_acceptance_blocker_count: int = 0
    evidence_bundle_retention_handoff_acceptance_verification_count: int = 0
    latest_evidence_bundle_retention_handoff_acceptance_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_verification_status: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_handoff_acceptance_verification_sha256: str | None = None
    evidence_bundle_retention_handoff_acceptance_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_register_count: int = 0
    latest_evidence_bundle_retention_custody_register_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_register_status: str | None = None
    latest_evidence_bundle_retention_custody_register_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_register_sha256: str | None = None
    evidence_bundle_retention_custody_register_blocker_count: int = 0
    evidence_bundle_retention_custody_register_verification_count: int = 0
    latest_evidence_bundle_retention_custody_register_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_register_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_register_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_register_verification_sha256: str | None = None
    evidence_bundle_retention_custody_register_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_seal_count: int = 0
    latest_evidence_bundle_retention_custody_seal_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_seal_status: str | None = None
    latest_evidence_bundle_retention_custody_seal_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_seal_sha256: str | None = None
    evidence_bundle_retention_custody_seal_blocker_count: int = 0
    evidence_bundle_retention_custody_seal_verification_count: int = 0
    latest_evidence_bundle_retention_custody_seal_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_seal_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_seal_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_seal_verification_sha256: str | None = None
    evidence_bundle_retention_custody_seal_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_audit_count: int = 0
    latest_evidence_bundle_retention_custody_audit_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_audit_status: str | None = None
    latest_evidence_bundle_retention_custody_audit_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_audit_sha256: str | None = None
    evidence_bundle_retention_custody_audit_blocker_count: int = 0
    evidence_bundle_retention_custody_audit_verification_count: int = 0
    latest_evidence_bundle_retention_custody_audit_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_audit_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_audit_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_audit_verification_sha256: str | None = None
    evidence_bundle_retention_custody_audit_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_continuity_count: int = 0
    latest_evidence_bundle_retention_custody_continuity_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_continuity_status: str | None = None
    latest_evidence_bundle_retention_custody_continuity_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_continuity_sha256: str | None = None
    evidence_bundle_retention_custody_continuity_blocker_count: int = 0
    evidence_bundle_retention_custody_continuity_verification_count: int = 0
    latest_evidence_bundle_retention_custody_continuity_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_continuity_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_continuity_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_continuity_verification_sha256: str | None = None
    evidence_bundle_retention_custody_continuity_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_review_count: int = 0
    latest_evidence_bundle_retention_custody_review_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_review_status: str | None = None
    latest_evidence_bundle_retention_custody_review_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_review_sha256: str | None = None
    evidence_bundle_retention_custody_review_blocker_count: int = 0
    evidence_bundle_retention_custody_review_verification_count: int = 0
    latest_evidence_bundle_retention_custody_review_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_review_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_review_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_review_verification_sha256: str | None = None
    evidence_bundle_retention_custody_review_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_renewal_count: int = 0
    latest_evidence_bundle_retention_custody_renewal_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_renewal_status: str | None = None
    latest_evidence_bundle_retention_custody_renewal_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_renewal_sha256: str | None = None
    evidence_bundle_retention_custody_renewal_blocker_count: int = 0
    evidence_bundle_retention_custody_renewal_verification_count: int = 0
    latest_evidence_bundle_retention_custody_renewal_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_renewal_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_renewal_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_renewal_verification_sha256: str | None = None
    evidence_bundle_retention_custody_renewal_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_schedule_count: int = 0
    latest_evidence_bundle_retention_custody_schedule_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_schedule_status: str | None = None
    latest_evidence_bundle_retention_custody_schedule_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_schedule_sha256: str | None = None
    latest_evidence_bundle_retention_custody_schedule_due_at_utc: str | None = None
    evidence_bundle_retention_custody_schedule_blocker_count: int = 0
    evidence_bundle_retention_custody_schedule_verification_count: int = 0
    latest_evidence_bundle_retention_custody_schedule_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_schedule_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_schedule_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_schedule_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_schedule_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_schedule_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_notice_count: int = 0
    latest_evidence_bundle_retention_custody_notice_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_notice_status: str | None = None
    latest_evidence_bundle_retention_custody_notice_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_notice_sha256: str | None = None
    latest_evidence_bundle_retention_custody_notice_due_at_utc: str | None = None
    evidence_bundle_retention_custody_notice_blocker_count: int = 0
    evidence_bundle_retention_custody_notice_verification_count: int = 0
    latest_evidence_bundle_retention_custody_notice_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_notice_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_notice_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_notice_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_notice_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_notice_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_acknowledgment_count: int = 0
    latest_evidence_bundle_retention_custody_acknowledgment_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_status: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_sha256: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_due_at_utc: str | None = None
    evidence_bundle_retention_custody_acknowledgment_blocker_count: int = 0
    evidence_bundle_retention_custody_acknowledgment_verification_count: int = 0
    latest_evidence_bundle_retention_custody_acknowledgment_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_acknowledgment_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_acknowledgment_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_completion_count: int = 0
    latest_evidence_bundle_retention_custody_completion_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_completion_status: str | None = None
    latest_evidence_bundle_retention_custody_completion_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_completion_sha256: str | None = None
    latest_evidence_bundle_retention_custody_completion_due_at_utc: str | None = None
    evidence_bundle_retention_custody_completion_blocker_count: int = 0
    evidence_bundle_retention_custody_completion_verification_count: int = 0
    latest_evidence_bundle_retention_custody_completion_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_completion_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_completion_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_completion_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_completion_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_completion_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_closeout_count: int = 0
    latest_evidence_bundle_retention_custody_closeout_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_closeout_status: str | None = None
    latest_evidence_bundle_retention_custody_closeout_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_closeout_sha256: str | None = None
    latest_evidence_bundle_retention_custody_closeout_due_at_utc: str | None = None
    evidence_bundle_retention_custody_closeout_blocker_count: int = 0
    evidence_bundle_retention_custody_closeout_verification_count: int = 0
    latest_evidence_bundle_retention_custody_closeout_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_closeout_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_closeout_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_closeout_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_closeout_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_closeout_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_archive_count: int = 0
    latest_evidence_bundle_retention_custody_archive_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_archive_status: str | None = None
    latest_evidence_bundle_retention_custody_archive_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_archive_sha256: str | None = None
    latest_evidence_bundle_retention_custody_archive_due_at_utc: str | None = None
    evidence_bundle_retention_custody_archive_blocker_count: int = 0
    evidence_bundle_retention_custody_archive_verification_count: int = 0
    latest_evidence_bundle_retention_custody_archive_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_archive_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_archive_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_archive_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_archive_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_archive_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_retrieval_count: int = 0
    latest_evidence_bundle_retention_custody_retrieval_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_status: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_sha256: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_due_at_utc: str | None = None
    evidence_bundle_retention_custody_retrieval_blocker_count: int = 0
    evidence_bundle_retention_custody_retrieval_verification_count: int = 0
    latest_evidence_bundle_retention_custody_retrieval_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_retrieval_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_retrieval_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_return_count: int = 0
    latest_evidence_bundle_retention_custody_return_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_return_status: str | None = None
    latest_evidence_bundle_retention_custody_return_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_return_sha256: str | None = None
    latest_evidence_bundle_retention_custody_return_due_at_utc: str | None = None
    evidence_bundle_retention_custody_return_blocker_count: int = 0
    evidence_bundle_retention_custody_return_verification_count: int = 0
    latest_evidence_bundle_retention_custody_return_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_return_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_return_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_return_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_return_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_return_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_redeposit_count: int = 0
    latest_evidence_bundle_retention_custody_redeposit_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_status: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_sha256: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_due_at_utc: str | None = None
    evidence_bundle_retention_custody_redeposit_blocker_count: int = 0
    evidence_bundle_retention_custody_redeposit_verification_count: int = 0
    latest_evidence_bundle_retention_custody_redeposit_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_redeposit_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_redeposit_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_inventory_count: int = 0
    latest_evidence_bundle_retention_custody_inventory_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_inventory_status: str | None = None
    latest_evidence_bundle_retention_custody_inventory_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_inventory_sha256: str | None = None
    latest_evidence_bundle_retention_custody_inventory_due_at_utc: str | None = None
    evidence_bundle_retention_custody_inventory_blocker_count: int = 0
    evidence_bundle_retention_custody_inventory_verification_count: int = 0
    latest_evidence_bundle_retention_custody_inventory_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_inventory_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_inventory_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_inventory_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_inventory_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_inventory_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_reconciliation_count: int = 0
    latest_evidence_bundle_retention_custody_reconciliation_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_status: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_sha256: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_due_at_utc: str | None = None
    evidence_bundle_retention_custody_reconciliation_blocker_count: int = 0
    evidence_bundle_retention_custody_reconciliation_verification_count: int = 0
    latest_evidence_bundle_retention_custody_reconciliation_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_reconciliation_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_reconciliation_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_certification_count: int = 0
    latest_evidence_bundle_retention_custody_certification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_certification_status: str | None = None
    latest_evidence_bundle_retention_custody_certification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_certification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_certification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_certification_blocker_count: int = 0
    evidence_bundle_retention_custody_certification_verification_count: int = 0
    latest_evidence_bundle_retention_custody_certification_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_certification_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_certification_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_certification_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_certification_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_certification_verification_blocker_count: int = 0
    evidence_bundle_retention_custody_attestation_count: int = 0
    latest_evidence_bundle_retention_custody_attestation_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_attestation_status: str | None = None
    latest_evidence_bundle_retention_custody_attestation_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_attestation_sha256: str | None = None
    latest_evidence_bundle_retention_custody_attestation_due_at_utc: str | None = None
    evidence_bundle_retention_custody_attestation_blocker_count: int = 0
    evidence_bundle_retention_custody_attestation_verification_count: int = 0
    latest_evidence_bundle_retention_custody_attestation_verification_at_utc: str | None = None
    latest_evidence_bundle_retention_custody_attestation_verification_status: str | None = None
    latest_evidence_bundle_retention_custody_attestation_verification_trust_banner: str | None = None
    latest_evidence_bundle_retention_custody_attestation_verification_sha256: str | None = None
    latest_evidence_bundle_retention_custody_attestation_verification_due_at_utc: str | None = None
    evidence_bundle_retention_custody_attestation_verification_blocker_count: int = 0
    latest_dry_run_artifact_at_utc: str | None = None
    latest_dry_run_source_selection_sha256: str | None = None
    selected_intent_dry_run_match: bool | None = None
    selected_intent_dry_run_status: Literal["NO_SELECTED_INTENT", "NO_DRY_RUN", "MATCHED", "MISMATCHED"] = "NO_SELECTED_INTENT"
    selected_intent_count: int = 0
    latest_selected_tracking_id: str | None = None
    latest_selected_intent_at_utc: str | None = None
    selected_intent_artifact_path: str | None = None
    broker_ready: bool = False
    tracking_present: bool = False
    paper_submission_capability: str = "CLI_ONLY"
    evidence_freshness_status: Literal["FRESH", "STALE", "REPLAY_REQUIRED", "MISSING_EVIDENCE", "UNKNOWN"] = "UNKNOWN"
    evidence_freshness_blocker_count: int = 0
    selected_intent_age_hours: float | None = None
    latest_linked_dry_run_age_hours: float | None = None
    latest_tracking_signal_age_hours: float | None = None

    model_config = {"extra": "forbid"}




__all__ = (
    "PaperExecutionSummary",
)
