"""Provider capability registry entries for alternative."""
from __future__ import annotations

from strategy_validator.contracts.provider_capabilities_types import (
    DefaultTrustLevel,
    PitSuitability,
    ProviderAccessType,
    ProviderCapability,
    ProviderCategory,
)

ALTERNATIVE_PROVIDER_CAPABILITIES: tuple[ProviderCapability, ...] = (
    ProviderCapability(
            provider_id="api_sports",
            display_name="API-Football / API-Sports",
            category=ProviderCategory.SPORTS_ODDS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("API_SPORTS_KEY", "API_FOOTBALL_KEY", "APISPORTS_KEY"),
            requires_secret=True,
            official_docs_url="https://www.api-football.com/documentation-v3",
            signup_url="https://dashboard.api-football.com/",
            research_role="research_sports_odds",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier daily caps.",
            license_notes="Commercial sports data; redistribution limited by plan.",
            recommended_priority=88,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="binance_public",
            display_name="Binance (public market data)",
            category=ProviderCategory.CRYPTO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://binance-docs.github.io/apidocs/spot/en/",
            signup_url="",
            research_role="research_crypto",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="Public REST IP-weighted limits.",
            license_notes="Authenticated trading is separate and key-gated.",
            recommended_priority=35,
        ),
    ProviderCapability(
            provider_id="coingecko",
            display_name="CoinGecko",
            category=ProviderCategory.CRYPTO,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("COINGECKO_API_KEY",),
            requires_secret=True,
            official_docs_url="https://www.coingecko.com/en/api/documentation",
            signup_url="https://www.coingecko.com/en/api/pricing",
            research_role="research_crypto",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Demo vs paid tiers differ sharply.",
            license_notes="Aggregator; not exchange canonical tape.",
            recommended_priority=55,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="coinmarketcap",
            display_name="CoinMarketCap",
            category=ProviderCategory.CRYPTO,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("COINMARKETCAP_API_KEY",),
            requires_secret=True,
            official_docs_url="https://coinmarketcap.com/api/documentation/v1/",
            signup_url="https://coinmarketcap.com/api/",
            research_role="research_crypto",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Monthly credits by plan.",
            license_notes="Commercial terms.",
            recommended_priority=56,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="football_data_org",
            display_name="football-data.org",
            category=ProviderCategory.SPORTS_ODDS,
            access_type=ProviderAccessType.FREE_KEY_REQUIRED,
            env_vars=("FOOTBALL_DATA_API_KEY", "FOOTBALL_DATA_API_TOKEN"),
            requires_secret=True,
            official_docs_url="https://www.football-data.org/documentation/quickstart",
            signup_url="https://www.football-data.org/client/register",
            research_role="research_sports_odds",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.LICENSED_PROVIDER,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier request caps.",
            license_notes="Read ToS for commercial vs non-commercial use.",
            recommended_priority=86,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="gdelt",
            display_name="GDELT Project",
            category=ProviderCategory.NEWS,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://www.gdeltproject.org/data.html",
            signup_url="",
            research_role="research_news",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
            pit_suitability=PitSuitability.NOT_PIT_SAFE_WITHOUT_ARCHIVE,
            rate_limit_notes="HTTP and BigQuery surfaces have platform quotas.",
            license_notes="Verify downstream redistribution constraints.",
            recommended_priority=62,
        ),
    ProviderCapability(
            provider_id="guardian_open_platform",
            display_name="The Guardian Open Platform",
            category=ProviderCategory.NEWS,
            access_type=ProviderAccessType.FREE_KEY_REQUIRED,
            env_vars=("GUARDIAN_API_KEY",),
            requires_secret=True,
            official_docs_url="https://open-platform.theguardian.com/documentation/",
            signup_url="https://open-platform.theguardian.com/access/",
            research_role="research_news",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.LICENSED_PROVIDER,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="Daily limits by tier.",
            license_notes="Attribution required.",
            recommended_priority=64,
        ),
    ProviderCapability(
            provider_id="kraken_public",
            display_name="Kraken (public market data)",
            category=ProviderCategory.CRYPTO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://docs.kraken.com/rest/",
            signup_url="",
            research_role="research_crypto",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="Per-IP public limits.",
            license_notes="Private trading requires API keys.",
            recommended_priority=36,
        ),
    ProviderCapability(
            provider_id="mediastack",
            display_name="Mediastack",
            category=ProviderCategory.NEWS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("MEDIASTACK_API_KEY",),
            requires_secret=True,
            official_docs_url="https://mediastack.com/documentation",
            signup_url="https://mediastack.com/signup/free",
            research_role="research_news",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Monthly quota by plan.",
            license_notes="Commercial aggregator.",
            recommended_priority=66,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="newsapi",
            display_name="NewsAPI.org",
            category=ProviderCategory.NEWS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("NEWSAPI_KEY", "NEWSAPI_API_KEY"),
            requires_secret=True,
            official_docs_url="https://newsapi.org/docs",
            signup_url="https://newsapi.org/register",
            research_role="research_news",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.NOT_PIT_SAFE_WITHOUT_ARCHIVE,
            rate_limit_notes="Developer tier historical limits.",
            license_notes="Free vs commercial license split.",
            recommended_priority=65,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="sportmonks",
            display_name="Sportmonks",
            category=ProviderCategory.SPORTS_ODDS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("SPORTMONKS_API_KEY", "SPORTMONKS_API_TOKEN"),
            requires_secret=True,
            official_docs_url="https://docs.sportmonks.com/",
            signup_url="https://www.sportmonks.com/",
            research_role="research_sports_odds",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Plan-based pools.",
            license_notes="Commercial sports data.",
            recommended_priority=87,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="the_odds_api",
            display_name="The Odds API",
            category=ProviderCategory.SPORTS_ODDS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("THE_ODDS_API_KEY",),
            requires_secret=True,
            official_docs_url="https://the-odds-api.com/liveapi/guides/v4/",
            signup_url="https://the-odds-api.com/",
            research_role="research_sports_odds",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free monthly caps.",
            license_notes="Odds aggregation; bookmaker ToS downstream.",
            recommended_priority=85,
            unsafe_as_promotion_authority_without_license=True,
        ),
)


__all__ = ("ALTERNATIVE_PROVIDER_CAPABILITIES",)
