"""Optional external research/data provider capability registry.

No provider listed here is required for backend startup; connectors remain opt-in.
"""
from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

SCHEMA_VERSION = "provider_capabilities/v2"


class ProviderCategory(str, Enum):
    FILINGS = "filings"
    MACRO = "macro"
    MARKET_DATA = "market_data"
    FUNDAMENTALS = "fundamentals"
    NEWS = "news"
    CRYPTO = "crypto"
    SPORTS_ODDS = "sports_odds"
    BROKER_EXECUTION = "broker_execution"


class ProviderAccessType(str, Enum):
    PUBLIC_NO_SIGNUP = "PUBLIC_NO_SIGNUP"
    FREE_KEY_REQUIRED = "FREE_KEY_REQUIRED"
    FREEMIUM_KEY_REQUIRED = "FREEMIUM_KEY_REQUIRED"
    PAID_OR_TRIAL = "PAID_OR_TRIAL"
    BROKER_ACCOUNT_REQUIRED = "BROKER_ACCOUNT_REQUIRED"


class DefaultTrustLevel(str, Enum):
    OFFICIAL_SOURCE = "OFFICIAL_SOURCE"
    LICENSED_PROVIDER = "LICENSED_PROVIDER"
    FREEMIUM_RESEARCH_ONLY = "FREEMIUM_RESEARCH_ONLY"
    PUBLIC_BEST_EFFORT = "PUBLIC_BEST_EFFORT"
    SNAPSHOT_ONLY = "SNAPSHOT_ONLY"
    BROKER_EXECUTION = "BROKER_EXECUTION"
    UNAVAILABLE = "UNAVAILABLE"


class PitSuitability(str, Enum):
    STRONG_PIT_SOURCE = "STRONG_PIT_SOURCE"
    PIT_WITH_RELEASE_TIMESTAMP = "PIT_WITH_RELEASE_TIMESTAMP"
    BEST_EFFORT_AS_OF = "BEST_EFFORT_AS_OF"
    NOT_PIT_SAFE_WITHOUT_ARCHIVE = "NOT_PIT_SAFE_WITHOUT_ARCHIVE"
    EXECUTION_ONLY = "EXECUTION_ONLY"


ResearchRole = Literal[
    "official_public_good",
    "research_filings",
    "research_macro",
    "research_market_data",
    "research_fundamentals",
    "research_news",
    "research_crypto",
    "research_sports_odds",
    "broker_execution_paper_first",
]


class ProviderCapability(BaseModel):
    """Machine-readable classification for one logical provider integration surface."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    provider_id: str = Field(min_length=1)
    display_name: str = Field(min_length=1)
    category: ProviderCategory
    access_type: ProviderAccessType
    env_vars: tuple[str, ...] = ()
    requires_secret: bool = False
    official_docs_url: str = ""
    signup_url: str = ""
    research_role: ResearchRole
    may_gate_live_promotion: bool = False
    default_trust_level: DefaultTrustLevel
    pit_suitability: PitSuitability
    rate_limit_notes: str = ""
    license_notes: str = ""
    recommended_priority: int = Field(default=100, ge=0, le=999)
    unsafe_as_promotion_authority_without_license: bool = False
    personal_live_trading_env_gate: str | None = None


def all_provider_capabilities() -> tuple[ProviderCapability, ...]:
    return _PROVIDERS


def export_provider_capabilities_payload() -> dict[str, object]:
    providers = [p.model_dump(mode="json") for p in _PROVIDERS]
    return {
        "schema_version": SCHEMA_VERSION,
        "providers": providers,
        "provider_count": len(providers),
    }


def capability_by_provider_id() -> dict[str, ProviderCapability]:
    return {p.provider_id: p for p in _PROVIDERS}


# Registry (alphabetical by provider_id)
_PROVIDERS: tuple[ProviderCapability, ...] = (
    ProviderCapability(
        provider_id="alpha_vantage",
        display_name="Alpha Vantage",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREE_KEY_REQUIRED,
        env_vars=("ALPHA_VANTAGE_API_KEY", "ALPHAVANTAGE_API_KEY"),
        requires_secret=True,
        official_docs_url="https://www.alphavantage.co/documentation/",
        signup_url="https://www.alphavantage.co/support/#api-key",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Strict per-endpoint limits on free tier.",
        license_notes="Terms restrict redistribution; not a canonical exchange tape.",
        recommended_priority=45,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="alpaca",
        display_name="Alpaca Markets",
        category=ProviderCategory.BROKER_EXECUTION,
        access_type=ProviderAccessType.BROKER_ACCOUNT_REQUIRED,
        env_vars=(
            "ALPACA_API_KEY",
            "ALPACA_API_SECRET",
            "APCA_API_KEY_ID",
            "APCA_API_SECRET_KEY",
            "STRATEGY_VALIDATOR_ALPACA_API_KEY_ID_ENV",
            "STRATEGY_VALIDATOR_ALPACA_API_SECRET_KEY_ENV",
        ),
        requires_secret=True,
        official_docs_url="https://docs.alpaca.markets/",
        signup_url="https://alpaca.markets/",
        research_role="broker_execution_paper_first",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.BROKER_EXECUTION,
        pit_suitability=PitSuitability.EXECUTION_ONLY,
        rate_limit_notes="Paper vs live endpoints and limits differ.",
        license_notes="Not canonical PIT tape; live money requires explicit operator approval and KYC outside this repo.",
        recommended_priority=20,
        unsafe_as_promotion_authority_without_license=True,
        personal_live_trading_env_gate="PERSONAL_LIVE_APPROVED",
    ),
    ProviderCapability(
        provider_id="api_sports",
        display_name="API-Football / API-Sports",
        category=ProviderCategory.SPORTS_ODDS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("API_SPORTS_KEY", "API_FOOTBALL_KEY", "APISPORTS_KEY"),
        requires_secret=True,
        official_docs_url="https://www.api-football.com/documentation-v3",
        signup_url="https://dashboard.api-football.com/",
        research_role="research_sports_odds",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier daily caps.",
        license_notes="Commercial sports data; redistribution limited by plan.",
        recommended_priority=88,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="binance_public",
        display_name="Binance (public market data)",
        category=ProviderCategory.CRYPTO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://binance-docs.github.io/apidocs/spot/en/",
        signup_url="",
        research_role="research_crypto",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="Public REST IP-weighted limits.",
        license_notes="Authenticated trading is separate and key-gated.",
        recommended_priority=35,
    ),
    ProviderCapability(
        provider_id="bls",
        display_name="U.S. Bureau of Labor Statistics (BLS) v1 public",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://www.bls.gov/developers/",
        signup_url="",
        research_role="research_macro",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
        rate_limit_notes="v1: no registration; lower limits. Prefer v2 key for production volume.",
        license_notes="Series revisions and vintages apply.",
        recommended_priority=12,
    ),
    ProviderCapability(
        provider_id="bls_registered_api",
        display_name="BLS Public Data API (registered / v2)",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.FREE_KEY_REQUIRED,
        env_vars=("BLS_API_KEY",),
        requires_secret=True,
        official_docs_url="https://www.bls.gov/developers/",
        signup_url="https://data.bls.gov/registrationEngine/",
        research_role="research_macro",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
        rate_limit_notes="Registration yields API key and higher limits.",
        license_notes="Same official BLS statistics with API terms.",
        recommended_priority=13,
    ),
    ProviderCapability(
        provider_id="coingecko",
        display_name="CoinGecko",
        category=ProviderCategory.CRYPTO,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("COINGECKO_API_KEY",),
        requires_secret=True,
        official_docs_url="https://www.coingecko.com/en/api/documentation",
        signup_url="https://www.coingecko.com/en/api/pricing",
        research_role="research_crypto",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Demo vs paid tiers differ sharply.",
        license_notes="Aggregator; not exchange canonical tape.",
        recommended_priority=55,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="coinmarketcap",
        display_name="CoinMarketCap",
        category=ProviderCategory.CRYPTO,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("COINMARKETCAP_API_KEY",),
        requires_secret=True,
        official_docs_url="https://coinmarketcap.com/api/documentation/v1/",
        signup_url="https://coinmarketcap.com/api/",
        research_role="research_crypto",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Monthly credits by plan.",
        license_notes="Commercial terms.",
        recommended_priority=56,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="ecb",
        display_name="ECB Statistical Data Warehouse",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://data.ecb.europa.eu/help/api/overview",
        signup_url="",
        research_role="official_public_good",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="Courtesy pacing for bulk SDMX pulls.",
        license_notes="Official ECB statistics; redistribution under ECB terms.",
        recommended_priority=8,
    ),
    ProviderCapability(
        provider_id="eodhd",
        display_name="EOD Historical Data (EODHD)",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("EODHD_API_KEY",),
        requires_secret=True,
        official_docs_url="https://eodhistoricaldata.com/financial-apis/",
        signup_url="https://eodhistoricaldata.com/register",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Plan-based daily limits.",
        license_notes="Verify license for redistribution.",
        recommended_priority=48,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="eurostat",
        display_name="Eurostat",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://ec.europa.eu/eurostat/web/main/data/web-services",
        signup_url="",
        research_role="official_public_good",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="JSON-stat API; fair use.",
        license_notes="EU open data policies.",
        recommended_priority=9,
    ),
    ProviderCapability(
        provider_id="financial_modeling_prep",
        display_name="Financial Modeling Prep (FMP)",
        category=ProviderCategory.FUNDAMENTALS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("FMP_API_KEY",),
        requires_secret=True,
        official_docs_url="https://site.financialmodelingprep.com/developer/docs/",
        signup_url="https://site.financialmodelingprep.com/register",
        research_role="research_fundamentals",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier capped.",
        license_notes="Aggregated fundamentals.",
        recommended_priority=50,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="finnhub",
        display_name="Finnhub",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("FINNHUB_API_KEY",),
        requires_secret=True,
        official_docs_url="https://finnhub.io/docs/api",
        signup_url="https://finnhub.io/register",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier ~60 calls/min class limits.",
        license_notes="Commercial aggregator.",
        recommended_priority=46,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="football_data_org",
        display_name="football-data.org",
        category=ProviderCategory.SPORTS_ODDS,
        access_type=ProviderAccessType.FREE_KEY_REQUIRED,
        env_vars=("FOOTBALL_DATA_API_KEY", "FOOTBALL_DATA_API_TOKEN"),
        requires_secret=True,
        official_docs_url="https://www.football-data.org/documentation/quickstart",
        signup_url="https://www.football-data.org/client/register",
        research_role="research_sports_odds",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.LICENSED_PROVIDER,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier request caps.",
        license_notes="Read ToS for commercial vs non-commercial use.",
        recommended_priority=86,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="fred",
        display_name="FRED (Federal Reserve Economic Data)",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.FREE_KEY_REQUIRED,
        env_vars=("FRED_API_KEY",),
        requires_secret=True,
        official_docs_url="https://fred.stlouisfed.org/docs/api/fred/",
        signup_url="https://fred.stlouisfed.org/docs/api/api_key.html",
        research_role="research_macro",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
        rate_limit_notes="Reasonable limits for registered API keys.",
        license_notes="St. Louis Fed attribution terms.",
        recommended_priority=5,
    ),
    ProviderCapability(
        provider_id="gdelt",
        display_name="GDELT Project",
        category=ProviderCategory.NEWS,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://www.gdeltproject.org/data.html",
        signup_url="",
        research_role="research_news",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
        pit_suitability=PitSuitability.NOT_PIT_SAFE_WITHOUT_ARCHIVE,
        rate_limit_notes="HTTP and BigQuery surfaces have platform quotas.",
        license_notes="Verify downstream redistribution constraints.",
        recommended_priority=62,
    ),
    ProviderCapability(
        provider_id="guardian_open_platform",
        display_name="The Guardian Open Platform",
        category=ProviderCategory.NEWS,
        access_type=ProviderAccessType.FREE_KEY_REQUIRED,
        env_vars=("GUARDIAN_API_KEY",),
        requires_secret=True,
        official_docs_url="https://open-platform.theguardian.com/documentation/",
        signup_url="https://open-platform.theguardian.com/access/",
        research_role="research_news",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.LICENSED_PROVIDER,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="Daily limits by tier.",
        license_notes="Attribution required.",
        recommended_priority=64,
    ),
    ProviderCapability(
        provider_id="imf_data",
        display_name="IMF Data Services",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://datahelp.imf.org/knowledge/articles/101668-data-services",
        signup_url="",
        research_role="official_public_good",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="SDMX/JSON-REST; throttle bulk pulls.",
        license_notes="IMF terms of use.",
        recommended_priority=11,
    ),
    ProviderCapability(
        provider_id="kraken_public",
        display_name="Kraken (public market data)",
        category=ProviderCategory.CRYPTO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://docs.kraken.com/rest/",
        signup_url="",
        research_role="research_crypto",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.PUBLIC_BEST_EFFORT,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="Per-IP public limits.",
        license_notes="Private trading requires API keys.",
        recommended_priority=36,
    ),
    ProviderCapability(
        provider_id="massive",
        display_name="Massive (Polygon successor brand)",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("MASSIVE_API_KEY", "POLYGON_API_KEY"),
        requires_secret=True,
        official_docs_url="https://polygon.io/docs",
        signup_url="https://polygon.io/dashboard/signup",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Polygon/Massive API keys and tiers; verify current product naming.",
        license_notes="Commercial market data; redistribution per contract.",
        recommended_priority=41,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="mediastack",
        display_name="Mediastack",
        category=ProviderCategory.NEWS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("MEDIASTACK_API_KEY",),
        requires_secret=True,
        official_docs_url="https://mediastack.com/documentation",
        signup_url="https://mediastack.com/signup/free",
        research_role="research_news",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Monthly quota by plan.",
        license_notes="Commercial aggregator.",
        recommended_priority=66,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="nasdaq_data_link",
        display_name="Nasdaq Data Link",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("NASDAQ_DATA_LINK_API_KEY",),
        requires_secret=True,
        official_docs_url="https://docs.data.nasdaq.com/docs",
        signup_url="https://data.nasdaq.com/sign-up",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Dataset-dependent; many tables commercial-only.",
        license_notes="Dataset licenses vary.",
        recommended_priority=42,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="newsapi",
        display_name="NewsAPI.org",
        category=ProviderCategory.NEWS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("NEWSAPI_KEY", "NEWSAPI_API_KEY"),
        requires_secret=True,
        official_docs_url="https://newsapi.org/docs",
        signup_url="https://newsapi.org/register",
        research_role="research_news",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.NOT_PIT_SAFE_WITHOUT_ARCHIVE,
        rate_limit_notes="Developer tier historical limits.",
        license_notes="Free vs commercial license split.",
        recommended_priority=65,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="oecd",
        display_name="OECD Data API",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://data.oecd.org/api/",
        signup_url="",
        research_role="official_public_good",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="SDMX-JSON; avoid unbounded concurrency.",
        license_notes="OECD attribution terms.",
        recommended_priority=10,
    ),
    ProviderCapability(
        provider_id="polygon_io",
        display_name="Polygon.io",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("POLYGON_API_KEY",),
        requires_secret=True,
        official_docs_url="https://polygon.io/docs",
        signup_url="https://polygon.io/dashboard/signup",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier delayed data; commercial for real-time.",
        license_notes="Rebranding to Massive; verify current API base URLs and keys.",
        recommended_priority=40,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="sec_edgar",
        display_name="SEC EDGAR",
        category=ProviderCategory.FILINGS,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://www.sec.gov/edgar/sec-api-documentation",
        signup_url="",
        research_role="research_filings",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
        rate_limit_notes="10 r/s fair access; set descriptive User-Agent (e.g. SEC_USER_AGENT).",
        license_notes="Public filings; follow SEC bulk/API guidance.",
        recommended_priority=3,
    ),
    ProviderCapability(
        provider_id="sportmonks",
        display_name="Sportmonks",
        category=ProviderCategory.SPORTS_ODDS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("SPORTMONKS_API_KEY", "SPORTMONKS_API_TOKEN"),
        requires_secret=True,
        official_docs_url="https://docs.sportmonks.com/",
        signup_url="https://www.sportmonks.com/",
        research_role="research_sports_odds",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Plan-based pools.",
        license_notes="Commercial sports data.",
        recommended_priority=87,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="the_odds_api",
        display_name="The Odds API",
        category=ProviderCategory.SPORTS_ODDS,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("THE_ODDS_API_KEY",),
        requires_secret=True,
        official_docs_url="https://the-odds-api.com/liveapi/guides/v4/",
        signup_url="https://the-odds-api.com/",
        research_role="research_sports_odds",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free monthly caps.",
        license_notes="Odds aggregation; bookmaker ToS downstream.",
        recommended_priority=85,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="tiingo",
        display_name="Tiingo",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("TIINGO_API_KEY",),
        requires_secret=True,
        official_docs_url="https://api.tiingo.com/documentation/",
        signup_url="https://www.tiingo.com/account/api/token",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Free tier endpoint limits.",
        license_notes="Commercial redistribution requires paid terms.",
        recommended_priority=44,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="twelve_data",
        display_name="Twelve Data",
        category=ProviderCategory.MARKET_DATA,
        access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
        env_vars=("TWELVE_DATA_API_KEY",),
        requires_secret=True,
        official_docs_url="https://twelvedata.com/docs",
        signup_url="https://twelvedata.com/pricing",
        research_role="research_market_data",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
        pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
        rate_limit_notes="Credits/day by plan.",
        license_notes="Aggregator.",
        recommended_priority=47,
        unsafe_as_promotion_authority_without_license=True,
    ),
    ProviderCapability(
        provider_id="world_bank_open_data",
        display_name="World Bank Open Data (indicators)",
        category=ProviderCategory.MACRO,
        access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
        env_vars=(),
        requires_secret=False,
        official_docs_url="https://datahelp.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation",
        signup_url="",
        research_role="official_public_good",
        may_gate_live_promotion=False,
        default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
        pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
        rate_limit_notes="Paginate; avoid bulk hammering.",
        license_notes="World Bank open data terms.",
        recommended_priority=7,
    ),
)
