"""Provider capability registry entries for official."""
from __future__ import annotations

from strategy_validator.contracts.provider_capabilities_types import (
    DefaultTrustLevel,
    PitSuitability,
    ProviderAccessType,
    ProviderCapability,
    ProviderCategory,
)

OFFICIAL_PROVIDER_CAPABILITIES: tuple[ProviderCapability, ...] = (
    ProviderCapability(
            provider_id="bls",
            display_name="U.S. Bureau of Labor Statistics (BLS) v1 public",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://www.bls.gov/developers/",
            signup_url="",
            research_role="research_macro",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
            rate_limit_notes="v1: no registration; lower limits. Prefer v2 key for production volume.",
            license_notes="Series revisions and vintages apply.",
            recommended_priority=12,
        ),
    ProviderCapability(
            provider_id="bls_registered_api",
            display_name="BLS Public Data API (registered / v2)",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.FREE_KEY_REQUIRED,
            env_vars=("BLS_API_KEY",),
            requires_secret=True,
            official_docs_url="https://www.bls.gov/developers/",
            signup_url="https://data.bls.gov/registrationEngine/",
            research_role="research_macro",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
            rate_limit_notes="Registration yields API key and higher limits.",
            license_notes="Same official BLS statistics with API terms.",
            recommended_priority=13,
        ),
    ProviderCapability(
            provider_id="ecb",
            display_name="ECB Statistical Data Warehouse",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://data.ecb.europa.eu/help/api/overview",
            signup_url="",
            research_role="official_public_good",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="Courtesy pacing for bulk SDMX pulls.",
            license_notes="Official ECB statistics; redistribution under ECB terms.",
            recommended_priority=8,
        ),
    ProviderCapability(
            provider_id="eurostat",
            display_name="Eurostat",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://ec.europa.eu/eurostat/web/main/data/web-services",
            signup_url="",
            research_role="official_public_good",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="JSON-stat API; fair use.",
            license_notes="EU open data policies.",
            recommended_priority=9,
        ),
    ProviderCapability(
            provider_id="fred",
            display_name="FRED (Federal Reserve Economic Data)",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.FREE_KEY_REQUIRED,
            env_vars=("FRED_API_KEY",),
            requires_secret=True,
            official_docs_url="https://fred.stlouisfed.org/docs/api/fred/",
            signup_url="https://fred.stlouisfed.org/docs/api/api_key.html",
            research_role="research_macro",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
            rate_limit_notes="Reasonable limits for registered API keys.",
            license_notes="St. Louis Fed attribution terms.",
            recommended_priority=5,
        ),
    ProviderCapability(
            provider_id="imf_data",
            display_name="IMF Data Services",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://datahelp.imf.org/knowledge/articles/101668-data-services",
            signup_url="",
            research_role="official_public_good",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="SDMX/JSON-REST; throttle bulk pulls.",
            license_notes="IMF terms of use.",
            recommended_priority=11,
        ),
    ProviderCapability(
            provider_id="oecd",
            display_name="OECD Data API",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://data.oecd.org/api/",
            signup_url="",
            research_role="official_public_good",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="SDMX-JSON; avoid unbounded concurrency.",
            license_notes="OECD attribution terms.",
            recommended_priority=10,
        ),
    ProviderCapability(
            provider_id="sec_edgar",
            display_name="SEC EDGAR",
            category=ProviderCategory.FILINGS,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://www.sec.gov/edgar/sec-api-documentation",
            signup_url="",
            research_role="research_filings",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.STRONG_PIT_SOURCE,
            rate_limit_notes="10 r/s fair access; set descriptive User-Agent (e.g. SEC_USER_AGENT).",
            license_notes="Public filings; follow SEC bulk/API guidance.",
            recommended_priority=3,
        ),
    ProviderCapability(
            provider_id="world_bank_open_data",
            display_name="World Bank Open Data (indicators)",
            category=ProviderCategory.MACRO,
            access_type=ProviderAccessType.PUBLIC_NO_SIGNUP,
            env_vars=(),
            requires_secret=False,
            official_docs_url="https://datahelp.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation",
            signup_url="",
            research_role="official_public_good",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.OFFICIAL_SOURCE,
            pit_suitability=PitSuitability.PIT_WITH_RELEASE_TIMESTAMP,
            rate_limit_notes="Paginate; avoid bulk hammering.",
            license_notes="World Bank open data terms.",
            recommended_priority=7,
        ),
)


__all__ = ("OFFICIAL_PROVIDER_CAPABILITIES",)
