"""Provider capability registry entries for market."""
from __future__ import annotations

from strategy_validator.contracts.provider_capabilities_types import (
    DefaultTrustLevel,
    PitSuitability,
    ProviderAccessType,
    ProviderCapability,
    ProviderCategory,
)

MARKET_PROVIDER_CAPABILITIES: tuple[ProviderCapability, ...] = (
    ProviderCapability(
            provider_id="alpha_vantage",
            display_name="Alpha Vantage",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREE_KEY_REQUIRED,
            env_vars=("ALPHA_VANTAGE_API_KEY", "ALPHAVANTAGE_API_KEY"),
            requires_secret=True,
            official_docs_url="https://www.alphavantage.co/documentation/",
            signup_url="https://www.alphavantage.co/support/#api-key",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Strict per-endpoint limits on free tier.",
            license_notes="Terms restrict redistribution; not a canonical exchange tape.",
            recommended_priority=45,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="eodhd",
            display_name="EOD Historical Data (EODHD)",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("EODHD_API_KEY",),
            requires_secret=True,
            official_docs_url="https://eodhistoricaldata.com/financial-apis/",
            signup_url="https://eodhistoricaldata.com/register",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Plan-based daily limits.",
            license_notes="Verify license for redistribution.",
            recommended_priority=48,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="financial_modeling_prep",
            display_name="Financial Modeling Prep (FMP)",
            category=ProviderCategory.FUNDAMENTALS,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("FMP_API_KEY",),
            requires_secret=True,
            official_docs_url="https://site.financialmodelingprep.com/developer/docs/",
            signup_url="https://site.financialmodelingprep.com/register",
            research_role="research_fundamentals",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier capped.",
            license_notes="Aggregated fundamentals.",
            recommended_priority=50,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="finnhub",
            display_name="Finnhub",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("FINNHUB_API_KEY",),
            requires_secret=True,
            official_docs_url="https://finnhub.io/docs/api",
            signup_url="https://finnhub.io/register",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier ~60 calls/min class limits.",
            license_notes="Commercial aggregator.",
            recommended_priority=46,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="massive",
            display_name="Massive (Polygon successor brand)",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("MASSIVE_API_KEY", "POLYGON_API_KEY"),
            requires_secret=True,
            official_docs_url="https://polygon.io/docs",
            signup_url="https://polygon.io/dashboard/signup",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Polygon/Massive API keys and tiers; verify current product naming.",
            license_notes="Commercial market data; redistribution per contract.",
            recommended_priority=41,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="nasdaq_data_link",
            display_name="Nasdaq Data Link",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("NASDAQ_DATA_LINK_API_KEY",),
            requires_secret=True,
            official_docs_url="https://docs.data.nasdaq.com/docs",
            signup_url="https://data.nasdaq.com/sign-up",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Dataset-dependent; many tables commercial-only.",
            license_notes="Dataset licenses vary.",
            recommended_priority=42,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="polygon_io",
            display_name="Polygon.io",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("POLYGON_API_KEY",),
            requires_secret=True,
            official_docs_url="https://polygon.io/docs",
            signup_url="https://polygon.io/dashboard/signup",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier delayed data; commercial for real-time.",
            license_notes="Rebranding to Massive; verify current API base URLs and keys.",
            recommended_priority=40,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="tiingo",
            display_name="Tiingo",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("TIINGO_API_KEY",),
            requires_secret=True,
            official_docs_url="https://api.tiingo.com/documentation/",
            signup_url="https://www.tiingo.com/account/api/token",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Free tier endpoint limits.",
            license_notes="Commercial redistribution requires paid terms.",
            recommended_priority=44,
            unsafe_as_promotion_authority_without_license=True,
        ),
    ProviderCapability(
            provider_id="twelve_data",
            display_name="Twelve Data",
            category=ProviderCategory.MARKET_DATA,
            access_type=ProviderAccessType.FREEMIUM_KEY_REQUIRED,
            env_vars=("TWELVE_DATA_API_KEY",),
            requires_secret=True,
            official_docs_url="https://twelvedata.com/docs",
            signup_url="https://twelvedata.com/pricing",
            research_role="research_market_data",
            may_gate_live_promotion=False,
            default_trust_level=DefaultTrustLevel.FREEMIUM_RESEARCH_ONLY,
            pit_suitability=PitSuitability.BEST_EFFORT_AS_OF,
            rate_limit_notes="Credits/day by plan.",
            license_notes="Aggregator.",
            recommended_priority=47,
            unsafe_as_promotion_authority_without_license=True,
        ),
)


__all__ = ("MARKET_PROVIDER_CAPABILITIES",)
