"""Lazy runtime dependency registry for the paper broker CLI.

The paper-broker command surface fans out into broker clients, paper execution
evidence builders, retention/custody artifacts, and Pydantic contract models.
Keeping those lazy proxies in this support module keeps the public dispatcher
small while preserving the historical ``strategy_validator.cli.paper_broker``
monkeypatch surface through module-level delegation.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from strategy_validator.core.lazy_imports import lazy_callable, lazy_model

dry_run_paper_order = lazy_callable('strategy_validator.brokers.alpaca_paper', 'dry_run_paper_order')
get_alpaca_paper_account = lazy_callable('strategy_validator.brokers.alpaca_paper', 'get_alpaca_paper_account')
get_alpaca_paper_order_status = lazy_callable('strategy_validator.brokers.alpaca_paper', 'get_alpaca_paper_order_status')
list_alpaca_paper_positions = lazy_callable('strategy_validator.brokers.alpaca_paper', 'list_alpaca_paper_positions')
submit_paper_order = lazy_callable('strategy_validator.brokers.alpaca_paper', 'submit_paper_order')
build_paper_broker_status_artifact = lazy_callable('strategy_validator.brokers.paper_broker_status_builder', 'build_paper_broker_status_artifact')
write_paper_broker_status_artifact = lazy_callable('strategy_validator.brokers.paper_broker_status_builder', 'write_paper_broker_status_artifact')
write_paper_execution_evidence_bundle_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle', 'write_paper_execution_evidence_bundle_artifact')
write_paper_execution_evidence_bundle_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_verification', 'write_paper_execution_evidence_bundle_verification_artifact')
write_paper_execution_evidence_bundle_drift_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_drift', 'write_paper_execution_evidence_bundle_drift_artifact')
write_paper_execution_evidence_bundle_rotation_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_rotation', 'write_paper_execution_evidence_bundle_rotation_artifact')
write_paper_execution_evidence_bundle_rotation_execution_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_rotation_execution', 'write_paper_execution_evidence_bundle_rotation_execution_artifact')
write_paper_execution_evidence_bundle_attestation_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_attestation', 'write_paper_execution_evidence_bundle_attestation_artifact')
write_paper_execution_evidence_bundle_attestation_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_attestation_verification', 'write_paper_execution_evidence_bundle_attestation_verification_artifact')
write_paper_execution_evidence_bundle_closure_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_closure', 'write_paper_execution_evidence_bundle_closure_artifact')
write_paper_execution_evidence_bundle_closure_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_closure_verification', 'write_paper_execution_evidence_bundle_closure_verification_artifact')
write_paper_execution_evidence_bundle_export_manifest_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_export', 'write_paper_execution_evidence_bundle_export_manifest_artifact')
write_paper_execution_evidence_bundle_export_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_export_verification', 'write_paper_execution_evidence_bundle_export_verification_artifact')
write_paper_execution_evidence_bundle_retention_receipt_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention', 'write_paper_execution_evidence_bundle_retention_receipt_artifact')
write_paper_execution_evidence_bundle_retention_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_verification', 'write_paper_execution_evidence_bundle_retention_verification_artifact')
write_paper_execution_evidence_bundle_retention_signoff_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_signoff', 'write_paper_execution_evidence_bundle_retention_signoff_artifact')
write_paper_execution_evidence_bundle_retention_signoff_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_signoff_verification', 'write_paper_execution_evidence_bundle_retention_signoff_verification_artifact')
write_paper_execution_evidence_bundle_retention_handoff_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_handoff', 'write_paper_execution_evidence_bundle_retention_handoff_artifact')
write_paper_execution_evidence_bundle_retention_handoff_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_handoff_verification', 'write_paper_execution_evidence_bundle_retention_handoff_verification_artifact')
write_paper_execution_evidence_bundle_retention_handoff_acceptance_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_handoff_acceptance', 'write_paper_execution_evidence_bundle_retention_handoff_acceptance_artifact')
write_paper_execution_evidence_bundle_retention_handoff_acceptance_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_handoff_acceptance_verification', 'write_paper_execution_evidence_bundle_retention_handoff_acceptance_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_register_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_register', 'write_paper_execution_evidence_bundle_retention_custody_register_artifact')
write_paper_execution_evidence_bundle_retention_custody_register_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_register_verification', 'write_paper_execution_evidence_bundle_retention_custody_register_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_seal_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_seal', 'write_paper_execution_evidence_bundle_retention_custody_seal_artifact')
write_paper_execution_evidence_bundle_retention_custody_seal_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_seal_verification', 'write_paper_execution_evidence_bundle_retention_custody_seal_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_audit_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_audit', 'write_paper_execution_evidence_bundle_retention_custody_audit_artifact')
write_paper_execution_evidence_bundle_retention_custody_audit_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_audit_verification', 'write_paper_execution_evidence_bundle_retention_custody_audit_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_continuity_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_continuity', 'write_paper_execution_evidence_bundle_retention_custody_continuity_artifact')
write_paper_execution_evidence_bundle_retention_custody_continuity_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_continuity_verification', 'write_paper_execution_evidence_bundle_retention_custody_continuity_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_review_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_review', 'write_paper_execution_evidence_bundle_retention_custody_review_artifact')
write_paper_execution_evidence_bundle_retention_custody_review_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_review_verification', 'write_paper_execution_evidence_bundle_retention_custody_review_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_renewal_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_renewal', 'write_paper_execution_evidence_bundle_retention_custody_renewal_artifact')
write_paper_execution_evidence_bundle_retention_custody_renewal_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_renewal_verification', 'write_paper_execution_evidence_bundle_retention_custody_renewal_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_schedule_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_schedule', 'write_paper_execution_evidence_bundle_retention_custody_schedule_artifact')
write_paper_execution_evidence_bundle_retention_custody_schedule_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_schedule_verification', 'write_paper_execution_evidence_bundle_retention_custody_schedule_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_notice_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_notice', 'write_paper_execution_evidence_bundle_retention_custody_notice_artifact')
write_paper_execution_evidence_bundle_retention_custody_notice_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_notice_verification', 'write_paper_execution_evidence_bundle_retention_custody_notice_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_acknowledgment_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_acknowledgment', 'write_paper_execution_evidence_bundle_retention_custody_acknowledgment_artifact')
write_paper_execution_evidence_bundle_retention_custody_acknowledgment_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_acknowledgment_verification', 'write_paper_execution_evidence_bundle_retention_custody_acknowledgment_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_completion_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_completion', 'write_paper_execution_evidence_bundle_retention_custody_completion_artifact')
write_paper_execution_evidence_bundle_retention_custody_completion_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_completion_verification', 'write_paper_execution_evidence_bundle_retention_custody_completion_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_closeout_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_closeout', 'write_paper_execution_evidence_bundle_retention_custody_closeout_artifact')
write_paper_execution_evidence_bundle_retention_custody_closeout_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_closeout_verification', 'write_paper_execution_evidence_bundle_retention_custody_closeout_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_archive_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_archive', 'write_paper_execution_evidence_bundle_retention_custody_archive_artifact')
write_paper_execution_evidence_bundle_retention_custody_archive_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_archive_verification', 'write_paper_execution_evidence_bundle_retention_custody_archive_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_retrieval_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_retrieval', 'write_paper_execution_evidence_bundle_retention_custody_retrieval_artifact')
write_paper_execution_evidence_bundle_retention_custody_retrieval_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_retrieval_verification', 'write_paper_execution_evidence_bundle_retention_custody_retrieval_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_return_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_return', 'write_paper_execution_evidence_bundle_retention_custody_return_artifact')
write_paper_execution_evidence_bundle_retention_custody_return_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_return_verification', 'write_paper_execution_evidence_bundle_retention_custody_return_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_redeposit_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_redeposit', 'write_paper_execution_evidence_bundle_retention_custody_redeposit_artifact')
write_paper_execution_evidence_bundle_retention_custody_redeposit_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_redeposit_verification', 'write_paper_execution_evidence_bundle_retention_custody_redeposit_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_inventory_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_inventory', 'write_paper_execution_evidence_bundle_retention_custody_inventory_artifact')
write_paper_execution_evidence_bundle_retention_custody_inventory_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_inventory_verification', 'write_paper_execution_evidence_bundle_retention_custody_inventory_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_reconciliation_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_reconciliation', 'write_paper_execution_evidence_bundle_retention_custody_reconciliation_artifact')
write_paper_execution_evidence_bundle_retention_custody_reconciliation_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_reconciliation_verification', 'write_paper_execution_evidence_bundle_retention_custody_reconciliation_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_certification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_certification', 'write_paper_execution_evidence_bundle_retention_custody_certification_artifact')
write_paper_execution_evidence_bundle_retention_custody_certification_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_certification_verification', 'write_paper_execution_evidence_bundle_retention_custody_certification_verification_artifact')
write_paper_execution_evidence_bundle_retention_custody_attestation_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_attestation', 'write_paper_execution_evidence_bundle_retention_custody_attestation_artifact')
write_paper_execution_evidence_bundle_retention_custody_attestation_verification_artifact = lazy_callable('strategy_validator.application.paper_execution_evidence_bundle_retention_custody_attestation_verification', 'write_paper_execution_evidence_bundle_retention_custody_attestation_verification_artifact')
read_paper_execution_intent_selection_artifact = lazy_callable('strategy_validator.application.paper_execution_intent_selection', 'read_paper_execution_intent_selection_artifact')
write_paper_execution_intent_selection_artifact = lazy_callable('strategy_validator.application.paper_execution_intent_selection', 'write_paper_execution_intent_selection_artifact')
write_paper_order_dry_run_artifact = lazy_callable('strategy_validator.application.paper_execution_journal', 'write_paper_order_dry_run_artifact')
broker_order_id_from_submission = lazy_callable('strategy_validator.application.paper_execution_order_status', 'broker_order_id_from_submission')
find_latest_submission_artifact = lazy_callable('strategy_validator.application.paper_execution_order_status', 'find_latest_submission_artifact')
tracking_id_from_submission = lazy_callable('strategy_validator.application.paper_execution_order_status', 'tracking_id_from_submission')
write_paper_order_status_artifact = lazy_callable('strategy_validator.application.paper_execution_order_status', 'write_paper_order_status_artifact')
build_paper_submission_guard_snapshot = lazy_callable('strategy_validator.application.paper_execution_submission_guard', 'build_paper_submission_guard_snapshot')
write_paper_order_submission_artifact = lazy_callable('strategy_validator.application.paper_execution_submission_guard', 'write_paper_order_submission_artifact')
write_paper_account_position_snapshot_artifact = lazy_callable('strategy_validator.application.paper_execution_reconciliation', 'write_paper_account_position_snapshot_artifact')
build_ui_paper_execution_cockpit_payload = lazy_callable('strategy_validator.application.paper_execution_cockpit', 'build_ui_paper_execution_cockpit_payload')
parse_env_file = lazy_callable('strategy_validator.cli.deployment_env_check', 'parse_env_file')
PaperBrokerOrderIntent = lazy_model('strategy_validator.contracts.paper_broker', 'PaperBrokerOrderIntent')
PaperExecutionTimelineEntry = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionTimelineEntry')
PaperExecutionTimelineSummary = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionTimelineSummary')
PaperExecutionEvidenceBundleDriftView = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionEvidenceBundleDriftView')
PaperExecutionEvidenceBundleVerificationView = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionEvidenceBundleVerificationView')
PaperExecutionEvidenceBundleView = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionEvidenceBundleView')
PaperExecutionEvidenceBundleRotationView = lazy_model('strategy_validator.contracts.paper_execution', 'PaperExecutionEvidenceBundleRotationView')

__all__ = [
    "json",
    "sys",
    "Path",
    "dry_run_paper_order",
    "get_alpaca_paper_account",
    "get_alpaca_paper_order_status",
    "list_alpaca_paper_positions",
    "submit_paper_order",
    "build_paper_broker_status_artifact",
    "write_paper_broker_status_artifact",
    "write_paper_execution_evidence_bundle_artifact",
    "write_paper_execution_evidence_bundle_verification_artifact",
    "write_paper_execution_evidence_bundle_drift_artifact",
    "write_paper_execution_evidence_bundle_rotation_artifact",
    "write_paper_execution_evidence_bundle_rotation_execution_artifact",
    "write_paper_execution_evidence_bundle_attestation_artifact",
    "write_paper_execution_evidence_bundle_attestation_verification_artifact",
    "write_paper_execution_evidence_bundle_closure_artifact",
    "write_paper_execution_evidence_bundle_closure_verification_artifact",
    "write_paper_execution_evidence_bundle_export_manifest_artifact",
    "write_paper_execution_evidence_bundle_export_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_receipt_artifact",
    "write_paper_execution_evidence_bundle_retention_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_signoff_artifact",
    "write_paper_execution_evidence_bundle_retention_signoff_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_handoff_artifact",
    "write_paper_execution_evidence_bundle_retention_handoff_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_handoff_acceptance_artifact",
    "write_paper_execution_evidence_bundle_retention_handoff_acceptance_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_register_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_register_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_seal_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_seal_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_audit_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_audit_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_continuity_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_continuity_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_review_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_review_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_renewal_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_renewal_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_schedule_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_schedule_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_notice_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_notice_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_acknowledgment_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_acknowledgment_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_completion_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_completion_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_closeout_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_closeout_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_archive_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_archive_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_retrieval_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_retrieval_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_return_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_return_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_redeposit_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_redeposit_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_inventory_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_inventory_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_reconciliation_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_reconciliation_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_certification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_certification_verification_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_attestation_artifact",
    "write_paper_execution_evidence_bundle_retention_custody_attestation_verification_artifact",
    "read_paper_execution_intent_selection_artifact",
    "write_paper_execution_intent_selection_artifact",
    "write_paper_order_dry_run_artifact",
    "broker_order_id_from_submission",
    "find_latest_submission_artifact",
    "tracking_id_from_submission",
    "write_paper_order_status_artifact",
    "build_paper_submission_guard_snapshot",
    "write_paper_order_submission_artifact",
    "write_paper_account_position_snapshot_artifact",
    "build_ui_paper_execution_cockpit_payload",
    "parse_env_file",
    "PaperBrokerOrderIntent",
    "PaperExecutionTimelineEntry",
    "PaperExecutionTimelineSummary",
    "PaperExecutionEvidenceBundleDriftView",
    "PaperExecutionEvidenceBundleVerificationView",
    "PaperExecutionEvidenceBundleView",
    "PaperExecutionEvidenceBundleRotationView",
]
