from __future__ import annotations

from collections.abc import Callable, Mapping
import argparse

from strategy_validator.cli.oracle_event_log_commands import register_oracle_event_log_commands

Runner = Callable[[argparse.Namespace], int]


def register_oracle_event_constitutional_commands(sub: argparse._SubParsersAction[argparse.ArgumentParser], *, runners: Mapping[str, Runner]) -> None:
        register_oracle_event_log_commands(
            sub,
            runners={
                "oracle-event-log-append": runners["oracle-event-log-append"],
                "oracle-derived-view": runners["oracle-derived-view"],
                "oracle-horizon-view": runners["oracle-horizon-view"],
                "oracle-rolling-review": runners["oracle-rolling-review"],
                "oracle-rolling-review-checkpoint": runners["oracle-rolling-review-checkpoint"],
                "oracle-event-checkpoint": runners["oracle-event-checkpoint"],
                "oracle-horizon-checkpoint": runners["oracle-horizon-checkpoint"],
                "verify-oracle-event-checkpoint": runners["verify-oracle-event-checkpoint"],
            },
        )

        ote = sub.add_parser("oracle-transition-evidence", help="Build signed oracle transition evidence from two verified oracle evidence manifests")
        ote.add_argument("previous_manifest", help="Previous ORACLE_EVIDENCE.json path")
        ote.add_argument("current_manifest", help="Current ORACLE_EVIDENCE.json path")
        ote.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ote.add_argument("--previous-dsse", default="", help="Optional DSSE envelope for the previous oracle evidence manifest")
        ote.add_argument("--current-dsse", default="", help="Optional DSSE envelope for the current oracle evidence manifest")
        ote.add_argument("--previous-public-key", default="", help="Optional Ed25519 public key PEM for the previous manifest")
        ote.add_argument("--current-public-key", default="", help="Optional Ed25519 public key PEM for the current manifest")
        ote.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for signing the transition evidence manifest")
        ote.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify the transition evidence manifest immediately")
        ote.add_argument("--report-output", default="", help="Write ORACLE_STATE_TRANSITION_REPORT.json path")
        ote.add_argument("--markdown-output", default="", help="Write ORACLE_STATE_TRANSITION_REPORT.md path")
        ote.add_argument("--output", default="", help="Write ORACLE_TRANSITION_EVIDENCE.json path")
        ote.add_argument("--dsse-output", default="", help="Write ORACLE_TRANSITION_EVIDENCE.dsse.json path")
        ote.add_argument("--verification-output", default="", help="Write ORACLE_TRANSITION_EVIDENCE.verification.json path")
        ote.set_defaults(_run=runners["oracle-transition-evidence"])

        vot = sub.add_parser("verify-oracle-transition-evidence", help="Verify signed oracle transition evidence")
        vot.add_argument("manifest", help="Oracle transition evidence manifest JSON path")
        vot.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vot.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        vot.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vot.add_argument("--output", default="", help="Write verification JSON path")
        vot.set_defaults(_run=runners["verify-oracle-transition-evidence"])

        oml = sub.add_parser("oracle-memory-append", help="Append verified oracle transition evidence into an append-only JSONL memory lane")
        oml.add_argument("manifest", help="Oracle transition evidence manifest JSON path")
        oml.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        oml.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        oml.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        oml.add_argument("--lane-path", required=True, help="Append-only JSONL oracle memory lane path")
        oml.add_argument("--verification-output", default="", help="Write verification JSON path")
        oml.add_argument("--output", default="", help="Write appended lane entry JSON path")
        oml.set_defaults(_run=runners["oracle-memory-append"])

        oms = sub.add_parser("oracle-memory-summary", help="Summarize an append-only oracle memory lane")
        oms.add_argument("--lane-path", required=True, help="Append-only JSONL oracle memory lane path")
        oms.add_argument("--output", default="", help="Write ORACLE_MEMORY_LANE_SUMMARY.json path")
        oms.add_argument("--markdown-output", default="", help="Write ORACLE_MEMORY_LANE_SUMMARY.md path")
        oms.set_defaults(_run=runners["oracle-memory-summary"])

        omr = sub.add_parser("oracle-memory-review", help="Review a rolling oracle memory lane window and emit advisory posture classification")
        omr.add_argument("--lane-path", required=True, help="Append-only JSONL oracle memory lane path")
        omr.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        omr.add_argument("--window-size", type=int, default=7, help="Rolling window size in lane entries")
        omr.add_argument("--output", default="", help="Write ORACLE_MEMORY_REVIEW_REPORT.json path")
        omr.add_argument("--markdown-output", default="", help="Write ORACLE_MEMORY_REVIEW_REPORT.md path")
        omr.set_defaults(_run=runners["oracle-memory-review"])

        omre = sub.add_parser("oracle-memory-review-evidence", help="Build signed oracle memory review evidence from an append-only memory lane")
        omre.add_argument("--lane-path", required=True, help="Append-only JSONL oracle memory lane path")
        omre.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        omre.add_argument("--window-size", type=int, default=7, help="Rolling window size in lane entries")
        omre.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for signing the memory review evidence manifest")
        omre.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify the memory review evidence manifest immediately")
        omre.add_argument("--report-output", default="", help="Write ORACLE_MEMORY_REVIEW_REPORT.json path")
        omre.add_argument("--markdown-output", default="", help="Write ORACLE_MEMORY_REVIEW_REPORT.md path")
        omre.add_argument("--output", default="", help="Write ORACLE_MEMORY_REVIEW_EVIDENCE.json path")
        omre.add_argument("--dsse-output", default="", help="Write ORACLE_MEMORY_REVIEW_EVIDENCE.dsse.json path")
        omre.add_argument("--verification-output", default="", help="Write ORACLE_MEMORY_REVIEW_EVIDENCE.verification.json path")
        omre.set_defaults(_run=runners["oracle-memory-review-evidence"])

        vomr = sub.add_parser("verify-oracle-memory-review-evidence", help="Verify signed oracle memory review evidence")
        vomr.add_argument("manifest", help="Oracle memory review evidence manifest JSON path")
        vomr.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vomr.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        vomr.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vomr.add_argument("--output", default="", help="Write verification JSON path")
        vomr.set_defaults(_run=runners["verify-oracle-memory-review-evidence"])

        orla = sub.add_parser("oracle-review-lane-append", help="Append verified oracle memory review evidence into an append-only JSONL review lane")
        orla.add_argument("manifest", help="Oracle memory review evidence manifest JSON path")
        orla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        orla.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        orla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        orla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle review lane path")
        orla.add_argument("--verification-output", default="", help="Write verification JSON path")
        orla.add_argument("--output", default="", help="Write ORACLE_REVIEW_LANE_ENTRY.json path")
        orla.set_defaults(_run=runners["oracle-review-lane-append"])

        owd = sub.add_parser("oracle-weekly-digest", help="Legacy compatibility: build a weekly doctrine digest from the review lane (prefer oracle-horizon-view on the canonical Oracle Event Log)")
        owd.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle review lane path")
        owd.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        owd.add_argument("--window-size", type=int, default=7, help="Rolling window size in review-lane entries")
        owd.add_argument("--output", default="", help="Write ORACLE_WEEKLY_DIGEST.json path")
        owd.add_argument("--markdown-output", default="", help="Write ORACLE_WEEKLY_DIGEST.md path")
        owd.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        owd.add_argument("--repo-root", default="", help="Optional repository root used for cadence feedback artifact discovery")
        owd.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        owd.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy review-lane reads when the canonical Oracle Event Log is unavailable")
        owd.set_defaults(_run=runners["oracle-weekly-digest"])

        owde = sub.add_parser("oracle-weekly-digest-evidence", help="Legacy compatibility: build signed oracle weekly digest evidence from an append-only review lane (direct lane reads require --allow-legacy-lane-read)")
        owde.add_argument("--lane-path", required=True, help="Append-only JSONL oracle review lane path")
        owde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        owde.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        owde.add_argument("--window-size", type=int, default=7, help="Rolling window size in review-lane entries")
        owde.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for signing the weekly digest evidence manifest")
        owde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify the weekly digest evidence manifest immediately")
        owde.add_argument("--report-output", default="", help="Write ORACLE_WEEKLY_DIGEST.json path")
        owde.add_argument("--markdown-output", default="", help="Write ORACLE_WEEKLY_DIGEST.md path")
        owde.add_argument("--output", default="", help="Write ORACLE_WEEKLY_DIGEST_EVIDENCE.json path")
        owde.add_argument("--dsse-output", default="", help="Write ORACLE_WEEKLY_DIGEST_EVIDENCE.dsse.json path")
        owde.add_argument("--verification-output", default="", help="Write ORACLE_WEEKLY_DIGEST_EVIDENCE.verification.json path")
        owde.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy review-lane reads for this legacy evidence command")
        owde.set_defaults(_run=runners["oracle-weekly-digest-evidence"])

        vowe = sub.add_parser("verify-oracle-weekly-digest-evidence", help="Verify signed oracle weekly digest evidence")
        vowe.add_argument("manifest", help="Oracle weekly digest evidence manifest JSON path")
        vowe.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vowe.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        vowe.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vowe.add_argument("--output", default="", help="Write verification JSON path")
        vowe.set_defaults(_run=runners["verify-oracle-weekly-digest-evidence"])

        odd = sub.add_parser("oracle-doctrine-drift", help="Compare two verified weekly digest evidence manifests and emit a doctrine drift report")
        odd.add_argument("previous_manifest", help="Previous ORACLE_WEEKLY_DIGEST_EVIDENCE.json path")
        odd.add_argument("current_manifest", help="Current ORACLE_WEEKLY_DIGEST_EVIDENCE.json path")
        odd.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        odd.add_argument("--previous-dsse", default="", help="Optional DSSE envelope for the previous weekly digest evidence manifest")
        odd.add_argument("--current-dsse", default="", help="Optional DSSE envelope for the current weekly digest evidence manifest")
        odd.add_argument("--previous-public-key", default="", help="Optional Ed25519 public key PEM for the previous manifest")
        odd.add_argument("--current-public-key", default="", help="Optional Ed25519 public key PEM for the current manifest")
        odd.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_DRIFT_REPORT.json path")
        odd.add_argument("--markdown-output", default="", help="Write ORACLE_DOCTRINE_DRIFT_REPORT.md path")
        odd.set_defaults(_run=runners["oracle-doctrine-drift"])

        odde = sub.add_parser("oracle-doctrine-drift-evidence", help="Build signed oracle doctrine drift evidence from two verified weekly digest evidence manifests")
        odde.add_argument("previous_manifest", help="Previous ORACLE_WEEKLY_DIGEST_EVIDENCE.json path")
        odde.add_argument("current_manifest", help="Current ORACLE_WEEKLY_DIGEST_EVIDENCE.json path")
        odde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        odde.add_argument("--previous-dsse", default="", help="Optional DSSE envelope for the previous weekly digest evidence manifest")
        odde.add_argument("--current-dsse", default="", help="Optional DSSE envelope for the current weekly digest evidence manifest")
        odde.add_argument("--previous-public-key", default="", help="Optional Ed25519 public key PEM for the previous manifest")
        odde.add_argument("--current-public-key", default="", help="Optional Ed25519 public key PEM for the current manifest")
        odde.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for signing the doctrine drift evidence manifest")
        odde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify the doctrine drift evidence manifest immediately")
        odde.add_argument("--report-output", default="", help="Write ORACLE_DOCTRINE_DRIFT_REPORT.json path")
        odde.add_argument("--markdown-output", default="", help="Write ORACLE_DOCTRINE_DRIFT_REPORT.md path")
        odde.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_DRIFT_EVIDENCE.json path")
        odde.add_argument("--dsse-output", default="", help="Write ORACLE_DOCTRINE_DRIFT_EVIDENCE.dsse.json path")
        odde.add_argument("--verification-output", default="", help="Write ORACLE_DOCTRINE_DRIFT_EVIDENCE.verification.json path")
        odde.set_defaults(_run=runners["oracle-doctrine-drift-evidence"])

        vodde = sub.add_parser("verify-oracle-doctrine-drift-evidence", help="Verify signed oracle doctrine drift evidence")
        vodde.add_argument("manifest", help="Oracle doctrine drift evidence manifest JSON path")
        vodde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vodde.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        vodde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vodde.add_argument("--output", default="", help="Write verification JSON path")
        vodde.set_defaults(_run=runners["verify-oracle-doctrine-drift-evidence"])

        odla = sub.add_parser("oracle-doctrine-lane-append", help="Append verified oracle doctrine drift evidence into an append-only JSONL doctrine lane")
        odla.add_argument("manifest", help="Oracle doctrine drift evidence manifest JSON path")
        odla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        odla.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        odla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        odla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle doctrine lane path")
        odla.add_argument("--verification-output", default="", help="Write verification JSON path")
        odla.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_LANE_ENTRY.json path")
        odla.set_defaults(_run=runners["oracle-doctrine-lane-append"])

        omd = sub.add_parser("oracle-monthly-digest", help="Legacy compatibility: build a monthly digest from the doctrine lane (prefer oracle-horizon-view on the canonical Oracle Event Log)")
        omd.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle doctrine lane path")
        omd.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        omd.add_argument("--window-size", type=int, default=4, help="Rolling window size in doctrine-lane entries")
        omd.add_argument("--output", default="", help="Write ORACLE_MONTHLY_DIGEST.json path")
        omd.add_argument("--markdown-output", default="", help="Write ORACLE_MONTHLY_DIGEST.md path")
        omd.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        omd.add_argument("--repo-root", default="", help="Optional repository root used for cadence feedback artifact discovery")
        omd.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        omd.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy doctrine-lane reads when the canonical Oracle Event Log is unavailable")
        omd.set_defaults(_run=runners["oracle-monthly-digest"])

        omde = sub.add_parser("oracle-monthly-digest-evidence", help="Legacy compatibility: build signed oracle monthly digest evidence from an append-only doctrine lane (direct lane reads require --allow-legacy-lane-read)")
        omde.add_argument("--lane-path", required=True, help="Append-only JSONL oracle doctrine lane path")
        omde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        omde.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        omde.add_argument("--window-size", type=int, default=4, help="Rolling window size in doctrine-lane entries")
        omde.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for signing the monthly digest evidence manifest")
        omde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify the monthly digest evidence manifest immediately")
        omde.add_argument("--report-output", default="", help="Write ORACLE_MONTHLY_DIGEST.json path")
        omde.add_argument("--markdown-output", default="", help="Write ORACLE_MONTHLY_DIGEST.md path")
        omde.add_argument("--output", default="", help="Write ORACLE_MONTHLY_DIGEST_EVIDENCE.json path")
        omde.add_argument("--dsse-output", default="", help="Write ORACLE_MONTHLY_DIGEST_EVIDENCE.dsse.json path")
        omde.add_argument("--verification-output", default="", help="Write ORACLE_MONTHLY_DIGEST_EVIDENCE.verification.json path")
        omde.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy doctrine-lane reads for this legacy evidence command")
        omde.set_defaults(_run=runners["oracle-monthly-digest-evidence"])

        vomde = sub.add_parser("verify-oracle-monthly-digest-evidence", help="Verify signed oracle monthly digest evidence")
        vomde.add_argument("manifest", help="Oracle monthly digest evidence manifest JSON path")
        vomde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vomde.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        vomde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vomde.add_argument("--output", default="", help="Write verification JSON path")
        vomde.set_defaults(_run=runners["verify-oracle-monthly-digest-evidence"])

        omla = sub.add_parser("oracle-monthly-lane-append", help="Legacy compatibility: append verified oracle monthly digest evidence into an append-only JSONL monthly lane")
        omla.add_argument("manifest", help="Oracle monthly digest evidence manifest JSON path")
        omla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        omla.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
        omla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        omla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle monthly lane path")
        omla.add_argument("--verification-output", default="", help="Write verification JSON path")
        omla.add_argument("--output", default="", help="Write ORACLE_MONTHLY_LANE_ENTRY.json path")
        omla.set_defaults(_run=runners["oracle-monthly-lane-append"])

        oqr = sub.add_parser("oracle-quarterly-review", help="Legacy compatibility: build a quarterly review from the monthly lane (prefer oracle-horizon-view on the canonical Oracle Event Log)")
        oqr.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle monthly lane path")
        oqr.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        oqr.add_argument("--window-size", type=int, default=3, help="Rolling window size in monthly-lane entries")
        oqr.add_argument("--output", default="", help="Write ORACLE_QUARTERLY_REVIEW.json path")
        oqr.add_argument("--markdown-output", default="", help="Write ORACLE_QUARTERLY_REVIEW.md path")
        oqr.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        oqr.add_argument("--repo-root", default="", help="Optional repository root used for cadence feedback artifact discovery")
        oqr.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        oqr.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy monthly-lane reads when the canonical Oracle Event Log is unavailable")
        oqr.set_defaults(_run=runners["oracle-quarterly-review"])

        oqre = sub.add_parser("oracle-quarterly-review-evidence", help="Legacy compatibility: build signed oracle quarterly review evidence from an append-only monthly lane (direct lane reads require --allow-legacy-lane-read)")
        oqre.add_argument("--lane-path", required=True, help="Append-only JSONL oracle monthly lane path")
        oqre.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        oqre.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        oqre.add_argument("--window-size", type=int, default=3, help="Rolling window size in monthly-lane entries")
        oqre.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for DSSE signing")
        oqre.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        oqre.add_argument("--report-output", default="", help="Write ORACLE_QUARTERLY_REVIEW.json path")
        oqre.add_argument("--markdown-output", default="", help="Write ORACLE_QUARTERLY_REVIEW.md path")
        oqre.add_argument("--output", default="", help="Write ORACLE_QUARTERLY_REVIEW_EVIDENCE.json path")
        oqre.add_argument("--dsse-output", default="", help="Write ORACLE_QUARTERLY_REVIEW_EVIDENCE.dsse.json path")
        oqre.add_argument("--verification-output", default="", help="Write ORACLE_QUARTERLY_REVIEW_EVIDENCE.verification.json path")
        oqre.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy monthly-lane reads for this legacy evidence command")
        oqre.set_defaults(_run=runners["oracle-quarterly-review-evidence"])

        ovqre = sub.add_parser("verify-oracle-quarterly-review-evidence", help="Verify signed oracle quarterly review evidence")
        ovqre.add_argument("manifest", help="ORACLE_QUARTERLY_REVIEW_EVIDENCE.json path")
        ovqre.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ovqre.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        ovqre.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ovqre.add_argument("--output", default="", help="Write verification JSON path")
        ovqre.set_defaults(_run=runners["verify-oracle-quarterly-review-evidence"])

        oqla = sub.add_parser("oracle-quarterly-lane-append", help="Legacy compatibility: append verified oracle quarterly review evidence to an append-only quarterly lane")
        oqla.add_argument("manifest", help="ORACLE_QUARTERLY_REVIEW_EVIDENCE.json path")
        oqla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        oqla.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        oqla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        oqla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle quarterly lane path")
        oqla.add_argument("--verification-output", default="", help="Write verification JSON path")
        oqla.add_argument("--output", default="", help="Write ORACLE_QUARTERLY_LANE_ENTRY.json path")
        oqla.set_defaults(_run=runners["oracle-quarterly-lane-append"])

        osa = sub.add_parser("oracle-semiannual-audit", help="Legacy compatibility: build a semiannual oracle doctrine audit from an append-only quarterly lane")
        osa.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle quarterly lane path")
        osa.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        osa.add_argument("--window-size", type=int, default=2, help="Rolling window size in quarterly-lane entries")
        osa.add_argument("--output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT.json path")
        osa.add_argument("--markdown-output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT.md path")
        osa.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        osa.add_argument("--repo-root", default="", help="Optional repository root used for cadence feedback artifact discovery")
        osa.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        osa.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy quarterly-lane reads when the canonical Oracle Event Log is unavailable")
        osa.set_defaults(_run=runners["oracle-semiannual-audit"])

        osae = sub.add_parser("oracle-semiannual-audit-evidence", help="Legacy compatibility: build signed oracle semiannual audit evidence from an append-only quarterly lane (direct lane reads require --allow-legacy-lane-read)")
        osae.add_argument("--lane-path", required=True, help="Append-only JSONL oracle quarterly lane path")
        osae.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        osae.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        osae.add_argument("--window-size", type=int, default=2, help="Rolling window size in quarterly-lane entries")
        osae.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for DSSE signing")
        osae.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        osae.add_argument("--report-output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT.json path")
        osae.add_argument("--markdown-output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT.md path")
        osae.add_argument("--output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT_EVIDENCE.json path")
        osae.add_argument("--dsse-output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT_EVIDENCE.dsse.json path")
        osae.add_argument("--verification-output", default="", help="Write ORACLE_SEMIANNUAL_AUDIT_EVIDENCE.verification.json path")
        osae.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy quarterly-lane reads for this legacy evidence command")
        osae.set_defaults(_run=runners["oracle-semiannual-audit-evidence"])

        ovsae = sub.add_parser("verify-oracle-semiannual-audit-evidence", help="Verify signed oracle semiannual audit evidence")
        ovsae.add_argument("manifest", help="ORACLE_SEMIANNUAL_AUDIT_EVIDENCE.json path")
        ovsae.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ovsae.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        ovsae.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ovsae.add_argument("--output", default="", help="Write verification JSON path")
        ovsae.set_defaults(_run=runners["verify-oracle-semiannual-audit-evidence"])

        osla = sub.add_parser("oracle-semiannual-lane-append", help="Legacy compatibility: append verified oracle semiannual audit evidence to an append-only semiannual lane")
        osla.add_argument("manifest", help="ORACLE_SEMIANNUAL_AUDIT_EVIDENCE.json path")
        osla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        osla.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        osla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        osla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle semiannual lane path")
        osla.add_argument("--verification-output", default="", help="Write verification JSON path")
        osla.add_argument("--output", default="", help="Write ORACLE_SEMIANNUAL_LANE_ENTRY.json path")
        osla.set_defaults(_run=runners["oracle-semiannual-lane-append"])

        oar = sub.add_parser("oracle-annual-review", help="Legacy compatibility: build an annual oracle doctrine review from an append-only semiannual lane")
        oar.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle semiannual lane path")
        oar.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        oar.add_argument("--window-size", type=int, default=2, help="Rolling window size in semiannual-lane entries")
        oar.add_argument("--output", default="", help="Write ORACLE_ANNUAL_REVIEW.json path")
        oar.add_argument("--markdown-output", default="", help="Write ORACLE_ANNUAL_REVIEW.md path")
        oar.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        oar.add_argument("--repo-root", default="", help="Optional repository root used for cadence feedback artifact discovery")
        oar.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        oar.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy semiannual-lane reads when the canonical Oracle Event Log is unavailable")
        oar.set_defaults(_run=runners["oracle-annual-review"])

        oare = sub.add_parser("oracle-annual-review-evidence", help="Legacy compatibility: build signed oracle annual review evidence from an append-only semiannual lane (direct lane reads require --allow-legacy-lane-read)")
        oare.add_argument("--lane-path", required=True, help="Append-only JSONL oracle semiannual lane path")
        oare.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        oare.add_argument("--search-root", default="", help="Optional artifact search root used for cadence feedback discovery")
        oare.add_argument("--window-size", type=int, default=2, help="Rolling window size in semiannual-lane entries")
        oare.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM used to sign annual review evidence")
        oare.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM used to verify signed annual review evidence")
        oare.add_argument("--report-output", default="", help="Write ORACLE_ANNUAL_REVIEW.json path")
        oare.add_argument("--markdown-output", default="", help="Write ORACLE_ANNUAL_REVIEW.md path")
        oare.add_argument("--output", default="", help="Write ORACLE_ANNUAL_REVIEW_EVIDENCE.json path")
        oare.add_argument("--dsse-output", default="", help="Write ORACLE_ANNUAL_REVIEW_EVIDENCE.dsse.json path")
        oare.add_argument("--verification-output", default="", help="Write ORACLE_ANNUAL_REVIEW_EVIDENCE.verification.json path")
        oare.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy semiannual-lane reads for this legacy evidence command")
        oare.set_defaults(_run=runners["oracle-annual-review-evidence"])

        ovare = sub.add_parser("verify-oracle-annual-review-evidence", help="Verify signed oracle annual review evidence")
        ovare.add_argument("manifest", help="ORACLE_ANNUAL_REVIEW_EVIDENCE.json path")
        ovare.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ovare.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        ovare.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ovare.add_argument("--output", default="", help="Write verification JSON path")
        ovare.set_defaults(_run=runners["verify-oracle-annual-review-evidence"])

        oala = sub.add_parser("oracle-annual-lane-append", help="Legacy compatibility: append verified oracle annual review evidence to an append-only annual lane")
        oala.add_argument("manifest", help="ORACLE_ANNUAL_REVIEW_EVIDENCE.json path")
        oala.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        oala.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        oala.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        oala.add_argument("--lane-path", required=True, help="Append-only JSONL oracle annual lane path")
        oala.add_argument("--verification-output", default="", help="Write verification JSON path")
        oala.add_argument("--output", default="", help="Write ORACLE_ANNUAL_LANE_ENTRY.json path")
        oala.set_defaults(_run=runners["oracle-annual-lane-append"])

        ocd = sub.add_parser("oracle-constitutional-digest", help="Legacy compatibility: build a constitutional digest from the annual lane (prefer oracle-horizon-view plus the constitutional gate on the canonical Oracle Event Log)")
        ocd.add_argument("--lane-path", required=False, default="", help="Append-only JSONL oracle annual lane path")
        ocd.add_argument("--log-path", default="", help="Optional canonical Oracle Event Log path; when omitted the CLI auto-detects docs/artifacts/oracle/ORACLE_EVENT_LOG.jsonl and proxies this legacy command to the preferred rolling review engine when available")
        ocd.add_argument("--window-size", type=int, default=3, help="Rolling window size in annual-lane entries")
        ocd.add_argument("--output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST.json path")
        ocd.add_argument("--markdown-output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST.md path")
        ocd.add_argument("--checkpoint-metadata-output", default="", help="Write incremental ORACLE_DERIVED_VIEW checkpoint metadata JSON path when this legacy surface proxies to the canonical Event Log")
        ocd.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy annual-lane reads when the canonical Oracle Event Log is unavailable")
        ocd.set_defaults(_run=runners["oracle-constitutional-digest"])

        ocde = sub.add_parser("oracle-constitutional-digest-evidence", help="Legacy compatibility: build signed constitutional digest evidence from an append-only annual lane (direct lane reads require --allow-legacy-lane-read)")
        ocde.add_argument("--lane-path", required=True, help="Append-only JSONL oracle annual lane path")
        ocde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ocde.add_argument("--window-size", type=int, default=3, help="Rolling window size in annual-lane entries")
        ocde.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for DSSE signing")
        ocde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ocde.add_argument("--report-output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST.json path")
        ocde.add_argument("--markdown-output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST.md path")
        ocde.add_argument("--output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.json path")
        ocde.add_argument("--dsse-output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.dsse.json path")
        ocde.add_argument("--verification-output", default="", help="Write ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.verification.json path")
        ocde.add_argument("--allow-legacy-lane-read", action="store_true", help="Explicitly allow direct legacy annual-lane reads for this legacy evidence command")
        ocde.set_defaults(_run=runners["oracle-constitutional-digest-evidence"])

        vocde = sub.add_parser("verify-oracle-constitutional-digest-evidence", help="Verify signed constitutional digest evidence")
        vocde.add_argument("manifest", help="ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.json path")
        vocde.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        vocde.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        vocde.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        vocde.add_argument("--output", default="", help="Write verification JSON path")
        vocde.set_defaults(_run=runners["verify-oracle-constitutional-digest-evidence"])

        ocla = sub.add_parser("oracle-constitutional-lane-append", help="Legacy compatibility: append verified constitutional digest evidence to an append-only constitutional lane")
        ocla.add_argument("manifest", help="ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.json path")
        ocla.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
        ocla.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        ocla.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ocla.add_argument("--lane-path", required=True, help="Append-only JSONL oracle constitutional lane path")
        ocla.add_argument("--verification-output", default="", help="Write verification JSON path")
        ocla.add_argument("--output", default="", help="Write ORACLE_CONSTITUTIONAL_LANE_ENTRY.json path")
        ocla.set_defaults(_run=runners["oracle-constitutional-lane-append"])

        odli = sub.add_parser("oracle-doctrine-lineage-index", help="Index closure, oracle, doctrine, and constitutional evidence paths across the repo")
        odli.add_argument("--repo-root", required=True, help="Repository root to index")
        odli.add_argument("--search-root", default="", help="Optional search root, defaults to docs/artifacts under repo root")
        odli.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_LINEAGE_INDEX.json path")
        odli.add_argument("--markdown-output", default="", help="Write ORACLE_DOCTRINE_LINEAGE_INDEX.md path")
        odli.set_defaults(_run=runners["oracle-doctrine-lineage-index"])

        odlv = sub.add_parser("oracle-doctrine-lineage-verify", help="Verify doctrine ladder completeness and classify whether the repo snapshot is sealed or constitutionally replayable")
        odlv.add_argument("--repo-root", required=True, help="Repository root to verify")
        odlv.add_argument("--search-root", default="", help="Optional search root, defaults to docs/artifacts under repo root")
        odlv.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_LINEAGE_VERIFICATION.json path")
        odlv.add_argument("--markdown-output", default="", help="Write ORACLE_DOCTRINE_LINEAGE_VERIFICATION.md path")
        odlv.set_defaults(_run=runners["oracle-doctrine-lineage-verify"])

        ocg = sub.add_parser("oracle-constitutional-gate", help="Gate constitutional doctrine trust using constitutional evidence verification plus doctrine lineage sealing")
        ocg.add_argument("manifest", help="ORACLE_CONSTITUTIONAL_DIGEST_EVIDENCE.json path")
        ocg.add_argument("--repo-root", required=True, help="Repository root to verify")
        ocg.add_argument("--search-root", default="", help="Optional search root, defaults to docs/artifacts under repo root")
        ocg.add_argument("--dsse", default="", help="Optional DSSE envelope path")
        ocg.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
        ocg.add_argument("--minimum-required-seal-status", default="FULLY_SEALED", choices=["FULLY_SEALED", "CONSTITUTIONALLY_REPLAYABLE", "PARTIALLY_SEALED", "ADVISORY_ONLY_INCOMPLETE"], help="Minimum lineage seal status required before the constitutional digest can be trusted")
        ocg.add_argument("--output", default="", help="Write ORACLE_CONSTITUTIONAL_GATE_REPORT.json path")
        ocg.add_argument("--markdown-output", default="", help="Write ORACLE_CONSTITUTIONAL_GATE_REPORT.md path")
        ocg.set_defaults(_run=runners["oracle-constitutional-gate"])

        oex = sub.add_parser("oracle-explain", help="Emit a machine-readable trust/policy explanation tree for a derived view, lineage verification, constitutional gate, or event checkpoint")
        oex.add_argument("--report", default="", help="Supported report JSON path: ORACLE_DERIVED_VIEW, ORACLE_DOCTRINE_LINEAGE_VERIFICATION, or ORACLE_CONSTITUTIONAL_GATE_REPORT")
        oex.add_argument("--manifest", default="", help="ORACLE_EVENT_CHECKPOINT.json path when explaining a checkpoint")
        oex.add_argument("--verification", default="", help="ORACLE_EVENT_CHECKPOINT.verification.json path when explaining a checkpoint")
        oex.add_argument("--repo-root", default="", help="Optional repository root used to auto-resolve doctrine lineage context for derived views and checkpoints")
        oex.add_argument("--output", default="", help="Write ORACLE_TRUST_EXPLANATION_REPORT.json path")
        oex.add_argument("--markdown-output", default="", help="Write ORACLE_TRUST_EXPLANATION_REPORT.md path")
        oex.set_defaults(_run=runners["oracle-explain"])

        odx = sub.add_parser("oracle-diagnose", help="Explain why a canonical oracle surface is restricted or blocked")
        odx.add_argument("--report", default="", help="Supported report JSON path: ORACLE_DERIVED_VIEW, ORACLE_DOCTRINE_LINEAGE_VERIFICATION, or ORACLE_CONSTITUTIONAL_GATE_REPORT")
        odx.add_argument("--manifest", default="", help="ORACLE_EVENT_CHECKPOINT.json path when diagnosing a checkpoint")
        odx.add_argument("--verification", default="", help="ORACLE_EVENT_CHECKPOINT.verification.json path when diagnosing a checkpoint")
        odx.add_argument("--repo-root", default="", help="Optional repository root used to auto-resolve doctrine lineage context for reports and checkpoints")
        odx.add_argument("--output", default="", help="Write ORACLE_OPERATOR_DIAGNOSTIC_REPORT.json path")
        odx.add_argument("--markdown-output", default="", help="Write ORACLE_OPERATOR_DIAGNOSTIC_REPORT.md path")
        odx.set_defaults(_run=runners["oracle-diagnose"])

        osp = sub.add_parser("oracle-status-pack", help="Emit one auditable operator status pack covering oracle trust, lineage, closure posture, and governed exceptions")
        osp.add_argument("--repo-root", required=True, help="Repository root used to inspect canonical oracle/governance artifacts")
        osp.add_argument("--search-root", default="", help="Optional artifact search root, defaults to docs/artifacts under repo root")
        osp.add_argument("--derived-view-report", default="", help="Optional explicit ORACLE_DERIVED_VIEW / ORACLE_ROLLING_REVIEW JSON path")
        osp.add_argument("--constitutional-gate-report", default="", help="Optional explicit ORACLE_CONSTITUTIONAL_GATE_REPORT.json path")
        osp.add_argument("--closure-snapshot", default="", help="Optional explicit CLOSURE_SNAPSHOT.json path")
        osp.add_argument("--closure-dsse", default="", help="Optional explicit CLOSURE_SNAPSHOT.dsse.json path")
        osp.add_argument("--closure-public-key", default="", help="Optional explicit closure snapshot public key PEM path")
        osp.add_argument("--governed-exception", default="", help="Optional explicit GOVERNED_EXCEPTION_MEMO.json path")
        osp.add_argument("--governed-exception-dsse", default="", help="Optional explicit GOVERNED_EXCEPTION_MEMO.dsse.json path")
        osp.add_argument("--governed-exception-public-key", default="", help="Optional explicit governed exception public key PEM path")
        osp.add_argument("--pack-root", default="", help="Optional directory where a materialized status pack bundle should be written")
        osp.add_argument("--output", default="", help="Write ORACLE_STATUS_PACK_REPORT.json path")
        osp.add_argument("--markdown-output", default="", help="Write ORACLE_STATUS_PACK_REPORT.md path")
        osp.add_argument("--html-output", default="", help="Write ORACLE_STATUS_PACK_REPORT.html path")
        osp.set_defaults(_run=runners["oracle-status-pack"])

        oip = sub.add_parser("oracle-incident-pack", help="Emit a canonical incident pack for restricted, untrusted, or blocked oracle/governance states")
        oip.add_argument("--repo-root", required=True, help="Repository root used to inspect canonical oracle/governance artifacts")
        oip.add_argument("--search-root", default="", help="Optional artifact search root, defaults to docs/artifacts under repo root")
        oip.add_argument("--derived-view-report", default="", help="Optional explicit ORACLE_DERIVED_VIEW / ORACLE_ROLLING_REVIEW JSON path")
        oip.add_argument("--constitutional-gate-report", default="", help="Optional explicit ORACLE_CONSTITUTIONAL_GATE_REPORT.json path")
        oip.add_argument("--closure-snapshot", default="", help="Optional explicit CLOSURE_SNAPSHOT.json path")
        oip.add_argument("--closure-dsse", default="", help="Optional explicit CLOSURE_SNAPSHOT.dsse.json path")
        oip.add_argument("--closure-public-key", default="", help="Optional explicit closure snapshot public key PEM path")
        oip.add_argument("--governed-exception", default="", help="Optional explicit GOVERNED_EXCEPTION_MEMO.json path")
        oip.add_argument("--governed-exception-dsse", default="", help="Optional explicit GOVERNED_EXCEPTION_MEMO.dsse.json path")
        oip.add_argument("--governed-exception-public-key", default="", help="Optional explicit governed exception public key PEM path")
        oip.add_argument("--pack-root", default="", help="Optional directory where a materialized incident pack bundle should be written")
        oip.add_argument("--output", default="", help="Write ORACLE_INCIDENT_PACK_REPORT.json path")
        oip.add_argument("--markdown-output", default="", help="Write ORACLE_INCIDENT_PACK_REPORT.md path")
        oip.add_argument("--html-output", default="", help="Write ORACLE_INCIDENT_PACK_REPORT.html path")
        oip.set_defaults(_run=runners["oracle-incident-pack"])

