"""Operator queue and pack CLI command registration helpers."""
from __future__ import annotations

import argparse

from strategy_validator.cli.oracle_pack_commands import (
    cmd_oracle_operator_pack_approval_disposition,
    cmd_oracle_operator_pack_approval_needed,
    cmd_oracle_operator_pack_assignment,
    cmd_oracle_operator_pack_claim_lease,
    cmd_oracle_operator_pack_claim_lifecycle,
    cmd_oracle_operator_pack_claim_operability,
    cmd_oracle_operator_pack_comparison,
    cmd_oracle_operator_pack_dashboard,
    cmd_oracle_operator_pack_dispatch_outcome,
    cmd_oracle_operator_pack_dispatch_permission,
    cmd_oracle_operator_pack_drift,
    cmd_oracle_operator_pack_escalation,
    cmd_oracle_operator_pack_execution_authorization,
    cmd_oracle_operator_pack_execution_exception,
    cmd_oracle_operator_pack_execution_finality,
    cmd_oracle_operator_pack_execution_force,
    cmd_oracle_operator_pack_execution_readiness,
    cmd_oracle_operator_pack_handoff,
    cmd_oracle_operator_pack_lease_governance,
    cmd_oracle_operator_pack_navigation,
    cmd_oracle_operator_pack_query,
    cmd_oracle_operator_pack_terminal_archive,
    cmd_oracle_operator_pack_terminal_closure,
    cmd_oracle_operator_pack_terminal_record,
    cmd_oracle_operator_pack_terminal_record_publish,
    cmd_oracle_operator_pack_terminal_resolution,
    cmd_oracle_operator_pack_timeline,
    cmd_oracle_operator_pack_workbench,
    register_oracle_pack_commands,
)
from strategy_validator.cli.oracle_queue_commands import (
    cmd_oracle_operator_action_outcome_ledger,
    cmd_oracle_operator_chronic_exit_certification,
    cmd_oracle_operator_chronic_exit_return_bridge,
    cmd_oracle_operator_chronic_instability_packet,
    cmd_oracle_operator_chronic_origin_restoration_audit_overlay,
    cmd_oracle_operator_chronic_origin_restoration_provenance,
    cmd_oracle_operator_chronic_remediation_mandate_ledger,
    cmd_oracle_operator_chronic_remediation_satisfaction,
    cmd_oracle_operator_chronic_watch_audit_convergence,
    cmd_oracle_operator_chronic_watch_handoff,
    cmd_oracle_operator_chronic_watch_outcome,
    cmd_oracle_operator_control_plane_bundle,
    cmd_oracle_operator_converged_normalization_attestation,
    cmd_oracle_operator_decision_execution,
    cmd_oracle_operator_decision_journal,
    cmd_oracle_operator_escalation_closure,
    cmd_oracle_operator_escalation_packet,
    cmd_oracle_operator_escalation_routing,
    cmd_oracle_operator_escalation_sla,
    cmd_oracle_operator_feedback_state,
    cmd_oracle_operator_freeze_release_attestation,
    cmd_oracle_operator_freeze_release_gate,
    cmd_oracle_operator_monitored_rejoin_activation,
    cmd_oracle_operator_monitored_rejoin_normalization_bridge,
    cmd_oracle_operator_monitored_rejoin_policy,
    cmd_oracle_operator_normalization_bridge_activation,
    cmd_oracle_operator_post_review_disposition,
    cmd_oracle_operator_provenance_aware_drift_policy,
    cmd_oracle_operator_queue_query,
    cmd_oracle_operator_recurrence_tribunal_disposition,
    cmd_oracle_operator_recurrence_tribunal_lane,
    cmd_oracle_operator_reentry_acceptance,
    cmd_oracle_operator_reentry_acknowledgement_timeout,
    cmd_oracle_operator_reentry_assignment,
    cmd_oracle_operator_reentry_completion,
    cmd_oracle_operator_reentry_completion_attestation,
    cmd_oracle_operator_reentry_post_review_gate,
    cmd_oracle_operator_reentry_queue_state,
    cmd_oracle_operator_reentry_reassignment,
    cmd_oracle_operator_reopen_lineage,
    cmd_oracle_operator_reopen_recurrence_policy,
    cmd_oracle_operator_restoration_audit,
    cmd_oracle_operator_return_activation,
    cmd_oracle_operator_return_authorization_ledger,
    cmd_oracle_operator_return_drift_breach,
    cmd_oracle_operator_return_monitoring,
    cmd_oracle_operator_return_reopen_loop,
    cmd_oracle_operator_supervisor_review,
    cmd_oracle_operator_transition_policy,
    cmd_oracle_operator_workboard_action_contract,
    cmd_oracle_operator_workboard_query,
    register_oracle_queue_commands,
)


def register_oracle_operator_runtime_commands(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register operator queue and pack command clusters."""
    register_oracle_queue_commands(
        sub,
        runners={
            "oracle-operator-queue-query": cmd_oracle_operator_queue_query,
            "oracle-operator-workboard-query": cmd_oracle_operator_workboard_query,
            "oracle-operator-workboard-action-contract": cmd_oracle_operator_workboard_action_contract,
            "oracle-operator-transition-policy": cmd_oracle_operator_transition_policy,
            "oracle-operator-decision-journal": cmd_oracle_operator_decision_journal,
            "oracle-operator-decision-execution": cmd_oracle_operator_decision_execution,
            "oracle-operator-escalation-routing": cmd_oracle_operator_escalation_routing,
            "oracle-operator-escalation-packet": cmd_oracle_operator_escalation_packet,
            "oracle-operator-escalation-sla": cmd_oracle_operator_escalation_sla,
            "oracle-operator-supervisor-review": cmd_oracle_operator_supervisor_review,
            "oracle-operator-escalation-closure": cmd_oracle_operator_escalation_closure,
            "oracle-operator-reentry-queue-state": cmd_oracle_operator_reentry_queue_state,
            "oracle-operator-reentry-assignment": cmd_oracle_operator_reentry_assignment,
            "oracle-operator-reentry-acceptance": cmd_oracle_operator_reentry_acceptance,
            "oracle-operator-reentry-acknowledgement-timeout": cmd_oracle_operator_reentry_acknowledgement_timeout,
            "oracle-operator-reentry-reassignment": cmd_oracle_operator_reentry_reassignment,
            "oracle-operator-reentry-completion": cmd_oracle_operator_reentry_completion,
            "oracle-operator-reentry-completion-attestation": cmd_oracle_operator_reentry_completion_attestation,
            "oracle-operator-reentry-post-review-gate": cmd_oracle_operator_reentry_post_review_gate,
            "oracle-operator-post-review-disposition": cmd_oracle_operator_post_review_disposition,
            "oracle-operator-return-authorization-ledger": cmd_oracle_operator_return_authorization_ledger,
            "oracle-operator-return-activation": cmd_oracle_operator_return_activation,
            "oracle-operator-return-monitoring": cmd_oracle_operator_return_monitoring,
            "oracle-operator-return-drift-breach": cmd_oracle_operator_return_drift_breach,
            "oracle-operator-return-reopen-loop": cmd_oracle_operator_return_reopen_loop,
            "oracle-operator-reopen-lineage": cmd_oracle_operator_reopen_lineage,
            "oracle-operator-reopen-recurrence-policy": cmd_oracle_operator_reopen_recurrence_policy,
            "oracle-operator-chronic-instability-packet": cmd_oracle_operator_chronic_instability_packet,
            "oracle-operator-recurrence-tribunal-lane": cmd_oracle_operator_recurrence_tribunal_lane,
            "oracle-operator-recurrence-tribunal-disposition": cmd_oracle_operator_recurrence_tribunal_disposition,
            "oracle-operator-chronic-remediation-mandate-ledger": cmd_oracle_operator_chronic_remediation_mandate_ledger,
            "oracle-operator-chronic-remediation-satisfaction": cmd_oracle_operator_chronic_remediation_satisfaction,
            "oracle-operator-freeze-release-gate": cmd_oracle_operator_freeze_release_gate,
            "oracle-operator-freeze-release-attestation": cmd_oracle_operator_freeze_release_attestation,
            "oracle-operator-chronic-exit-certification": cmd_oracle_operator_chronic_exit_certification,
            "oracle-operator-chronic-exit-return-bridge": cmd_oracle_operator_chronic_exit_return_bridge,
            "oracle-operator-monitored-rejoin-policy": cmd_oracle_operator_monitored_rejoin_policy,
            "oracle-operator-monitored-rejoin-activation": cmd_oracle_operator_monitored_rejoin_activation,
            "oracle-operator-chronic-watch-handoff": cmd_oracle_operator_chronic_watch_handoff,
            "oracle-operator-chronic-watch-outcome": cmd_oracle_operator_chronic_watch_outcome,
            "oracle-operator-monitored-rejoin-normalization-bridge": cmd_oracle_operator_monitored_rejoin_normalization_bridge,
            "oracle-operator-normalization-bridge-activation": cmd_oracle_operator_normalization_bridge_activation,
            "oracle-operator-chronic-watch-audit-convergence": cmd_oracle_operator_chronic_watch_audit_convergence,
            "oracle-operator-converged-normalization-attestation": cmd_oracle_operator_converged_normalization_attestation,
            "oracle-operator-chronic-origin-restoration-provenance": cmd_oracle_operator_chronic_origin_restoration_provenance,
            "oracle-operator-chronic-origin-restoration-audit-overlay": cmd_oracle_operator_chronic_origin_restoration_audit_overlay,
            "oracle-operator-provenance-aware-drift-policy": cmd_oracle_operator_provenance_aware_drift_policy,
            "oracle-operator-restoration-audit": cmd_oracle_operator_restoration_audit,
            "oracle-operator-action-outcome-ledger": cmd_oracle_operator_action_outcome_ledger,
            "oracle-operator-feedback-state": cmd_oracle_operator_feedback_state,
            "oracle-operator-control-plane-bundle": cmd_oracle_operator_control_plane_bundle,
        },
    )
    register_oracle_pack_commands(
        sub,
        runners={
            "oracle-operator-pack-query": cmd_oracle_operator_pack_query,
            "oracle-operator-pack-comparison": cmd_oracle_operator_pack_comparison,
            "oracle-operator-pack-drift": cmd_oracle_operator_pack_drift,
            "oracle-operator-pack-escalation": cmd_oracle_operator_pack_escalation,
            "oracle-operator-pack-assignment": cmd_oracle_operator_pack_assignment,
            "oracle-operator-pack-handoff": cmd_oracle_operator_pack_handoff,
            "oracle-operator-pack-claim-lease": cmd_oracle_operator_pack_claim_lease,
            "oracle-operator-pack-claim-lifecycle": cmd_oracle_operator_pack_claim_lifecycle,
            "oracle-operator-pack-claim-operability": cmd_oracle_operator_pack_claim_operability,
            "oracle-operator-pack-lease-governance": cmd_oracle_operator_pack_lease_governance,
            "oracle-operator-pack-execution-readiness": cmd_oracle_operator_pack_execution_readiness,
            "oracle-operator-pack-dispatch-permission": cmd_oracle_operator_pack_dispatch_permission,
            "oracle-operator-pack-dispatch-outcome": cmd_oracle_operator_pack_dispatch_outcome,
            "oracle-operator-pack-execution-exception": cmd_oracle_operator_pack_execution_exception,
            "oracle-operator-pack-approval-needed": cmd_oracle_operator_pack_approval_needed,
            "oracle-operator-pack-approval-disposition": cmd_oracle_operator_pack_approval_disposition,
            "oracle-operator-pack-execution-authorization": cmd_oracle_operator_pack_execution_authorization,
            "oracle-operator-pack-execution-force": cmd_oracle_operator_pack_execution_force,
            "oracle-operator-pack-execution-finality": cmd_oracle_operator_pack_execution_finality,
            "oracle-operator-pack-terminal-resolution": cmd_oracle_operator_pack_terminal_resolution,
            "oracle-operator-pack-terminal-closure": cmd_oracle_operator_pack_terminal_closure,
            "oracle-operator-pack-terminal-archive": cmd_oracle_operator_pack_terminal_archive,
            "oracle-operator-pack-terminal-record": cmd_oracle_operator_pack_terminal_record,
            "oracle-operator-pack-terminal-record-publish": cmd_oracle_operator_pack_terminal_record_publish,
            "oracle-operator-pack-navigation": cmd_oracle_operator_pack_navigation,
            "oracle-operator-pack-workbench": cmd_oracle_operator_pack_workbench,
            "oracle-operator-pack-dashboard": cmd_oracle_operator_pack_dashboard,
            "oracle-operator-pack-timeline": cmd_oracle_operator_pack_timeline,
        },
    )
