"""Bounded runtime registration for operator queue reentry/return/action-outcome commands."""
from __future__ import annotations

import argparse

from strategy_validator.cli.oracle_queue_commands import (
    cmd_oracle_operator_action_outcome_ledger,
    cmd_oracle_operator_chronic_exit_certification,
    cmd_oracle_operator_chronic_exit_return_bridge,
    cmd_oracle_operator_chronic_instability_packet,
    cmd_oracle_operator_chronic_origin_restoration_audit_overlay,
    cmd_oracle_operator_chronic_origin_restoration_provenance,
    cmd_oracle_operator_chronic_remediation_mandate_ledger,
    cmd_oracle_operator_chronic_remediation_satisfaction,
    cmd_oracle_operator_chronic_watch_audit_convergence,
    cmd_oracle_operator_chronic_watch_handoff,
    cmd_oracle_operator_chronic_watch_outcome,
    cmd_oracle_operator_converged_normalization_attestation,
    cmd_oracle_operator_feedback_state,
    cmd_oracle_operator_freeze_release_attestation,
    cmd_oracle_operator_freeze_release_gate,
    cmd_oracle_operator_monitored_rejoin_activation,
    cmd_oracle_operator_monitored_rejoin_normalization_bridge,
    cmd_oracle_operator_monitored_rejoin_policy,
    cmd_oracle_operator_normalization_bridge_activation,
    cmd_oracle_operator_post_review_disposition,
    cmd_oracle_operator_provenance_aware_drift_policy,
    cmd_oracle_operator_recurrence_tribunal_disposition,
    cmd_oracle_operator_recurrence_tribunal_lane,
    cmd_oracle_operator_reentry_acceptance,
    cmd_oracle_operator_reentry_acknowledgement_timeout,
    cmd_oracle_operator_reentry_assignment,
    cmd_oracle_operator_reentry_completion,
    cmd_oracle_operator_reentry_completion_attestation,
    cmd_oracle_operator_reentry_post_review_gate,
    cmd_oracle_operator_reentry_queue_state,
    cmd_oracle_operator_reentry_reassignment,
    cmd_oracle_operator_reopen_lineage,
    cmd_oracle_operator_reopen_recurrence_policy,
    cmd_oracle_operator_restoration_audit,
    cmd_oracle_operator_return_activation,
    cmd_oracle_operator_return_authorization_ledger,
    cmd_oracle_operator_return_drift_breach,
    cmd_oracle_operator_return_monitoring,
    cmd_oracle_operator_return_reopen_loop,
)
from strategy_validator.cli.oracle_queue_transition_reentry_commands import register_oracle_queue_transition_reentry_commands

OPERATOR_QUEUE_TRANSITION_REENTRY_RUNNERS = {
    "oracle-operator-reentry-queue-state": cmd_oracle_operator_reentry_queue_state,
    "oracle-operator-reentry-assignment": cmd_oracle_operator_reentry_assignment,
    "oracle-operator-reentry-acceptance": cmd_oracle_operator_reentry_acceptance,
    "oracle-operator-reentry-acknowledgement-timeout": cmd_oracle_operator_reentry_acknowledgement_timeout,
    "oracle-operator-reentry-reassignment": cmd_oracle_operator_reentry_reassignment,
    "oracle-operator-reentry-completion": cmd_oracle_operator_reentry_completion,
    "oracle-operator-reentry-completion-attestation": cmd_oracle_operator_reentry_completion_attestation,
    "oracle-operator-reentry-post-review-gate": cmd_oracle_operator_reentry_post_review_gate,
    "oracle-operator-post-review-disposition": cmd_oracle_operator_post_review_disposition,
    "oracle-operator-return-authorization-ledger": cmd_oracle_operator_return_authorization_ledger,
    "oracle-operator-return-activation": cmd_oracle_operator_return_activation,
    "oracle-operator-return-monitoring": cmd_oracle_operator_return_monitoring,
    "oracle-operator-return-drift-breach": cmd_oracle_operator_return_drift_breach,
    "oracle-operator-return-reopen-loop": cmd_oracle_operator_return_reopen_loop,
    "oracle-operator-reopen-lineage": cmd_oracle_operator_reopen_lineage,
    "oracle-operator-reopen-recurrence-policy": cmd_oracle_operator_reopen_recurrence_policy,
    "oracle-operator-chronic-instability-packet": cmd_oracle_operator_chronic_instability_packet,
    "oracle-operator-recurrence-tribunal-lane": cmd_oracle_operator_recurrence_tribunal_lane,
    "oracle-operator-recurrence-tribunal-disposition": cmd_oracle_operator_recurrence_tribunal_disposition,
    "oracle-operator-chronic-remediation-mandate-ledger": cmd_oracle_operator_chronic_remediation_mandate_ledger,
    "oracle-operator-chronic-remediation-satisfaction": cmd_oracle_operator_chronic_remediation_satisfaction,
    "oracle-operator-freeze-release-gate": cmd_oracle_operator_freeze_release_gate,
    "oracle-operator-freeze-release-attestation": cmd_oracle_operator_freeze_release_attestation,
    "oracle-operator-chronic-exit-certification": cmd_oracle_operator_chronic_exit_certification,
    "oracle-operator-chronic-exit-return-bridge": cmd_oracle_operator_chronic_exit_return_bridge,
    "oracle-operator-monitored-rejoin-policy": cmd_oracle_operator_monitored_rejoin_policy,
    "oracle-operator-monitored-rejoin-activation": cmd_oracle_operator_monitored_rejoin_activation,
    "oracle-operator-chronic-watch-handoff": cmd_oracle_operator_chronic_watch_handoff,
    "oracle-operator-chronic-watch-outcome": cmd_oracle_operator_chronic_watch_outcome,
    "oracle-operator-monitored-rejoin-normalization-bridge": cmd_oracle_operator_monitored_rejoin_normalization_bridge,
    "oracle-operator-normalization-bridge-activation": cmd_oracle_operator_normalization_bridge_activation,
    "oracle-operator-chronic-watch-audit-convergence": cmd_oracle_operator_chronic_watch_audit_convergence,
    "oracle-operator-converged-normalization-attestation": cmd_oracle_operator_converged_normalization_attestation,
    "oracle-operator-chronic-origin-restoration-provenance": cmd_oracle_operator_chronic_origin_restoration_provenance,
    "oracle-operator-chronic-origin-restoration-audit-overlay": cmd_oracle_operator_chronic_origin_restoration_audit_overlay,
    "oracle-operator-provenance-aware-drift-policy": cmd_oracle_operator_provenance_aware_drift_policy,
    "oracle-operator-restoration-audit": cmd_oracle_operator_restoration_audit,
    "oracle-operator-action-outcome-ledger": cmd_oracle_operator_action_outcome_ledger,
    "oracle-operator-feedback-state": cmd_oracle_operator_feedback_state,
}


def register_oracle_operator_queue_transition_reentry_runtime_commands(
    sub: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    """Register bounded operator queue reentry/return/action-outcome runtime commands."""
    register_oracle_queue_transition_reentry_commands(sub, runners=OPERATOR_QUEUE_TRANSITION_REENTRY_RUNNERS)
