from __future__ import annotations

import argparse
import json
from pathlib import Path
from datetime import timedelta

from strategy_validator.application.governance_surface import (
    build_governance_queue_state,
    build_workboard_action_contract_payload,
)
from strategy_validator.application.operator_queue_commands import (
    build_queue_query_payload,
    build_transition_policy_payload,
    build_workboard_payload,
)
from strategy_validator.cli.command_registry import CommandSpec, register_commands
from strategy_validator.cli.oracle_cli_common import parse_utc
from strategy_validator.control_plane import (
    assess_governance_plane,
    build_operator_action_outcome_ledger_request,
    build_operator_control_plane_bundle_request,
    build_operator_decision_execution_request,
    build_operator_decision_journal_request,
    build_operator_feedback_state_request,
    build_operator_reentry_queue_state_request,
    build_operator_reentry_assignment_request,
    build_operator_reentry_acceptance_request,
    build_operator_reentry_acknowledgement_timeout_request,
    build_operator_reentry_reassignment_request,
    build_operator_reentry_completion_request,
    build_operator_reentry_completion_attestation_request,
    build_operator_reentry_post_review_gate_request,
    build_operator_post_review_disposition_request,
    build_operator_return_authorization_ledger_request,
    build_operator_return_activation_request,
    build_operator_return_monitoring_request,
    build_operator_restoration_audit_request,
    build_operator_return_drift_breach_request,
    build_operator_return_reopen_loop_request,
    build_operator_reopen_lineage_request,
    build_operator_reopen_recurrence_policy_request,
    build_operator_chronic_instability_packet_request,
    build_operator_recurrence_tribunal_lane_request,
    build_operator_recurrence_tribunal_disposition_request,
    build_operator_chronic_remediation_mandate_ledger_request,
    build_operator_chronic_remediation_satisfaction_request,
    build_operator_freeze_release_gate_request,
    build_operator_freeze_release_attestation_request,
    build_operator_chronic_exit_certification_request,
    build_operator_chronic_exit_return_bridge_request,
    build_operator_monitored_rejoin_policy_request,
    build_operator_monitored_rejoin_activation_request,
    build_operator_chronic_watch_handoff_request,
    build_operator_chronic_watch_outcome_request,
    build_operator_monitored_rejoin_normalization_bridge_request,
    build_operator_normalization_bridge_activation_request,
    build_operator_chronic_watch_audit_convergence_request,
    build_operator_converged_normalization_attestation_request,
    build_operator_chronic_origin_restoration_provenance_request,
    build_operator_provenance_aware_drift_policy_request,
    build_operator_chronic_origin_restoration_audit_overlay_request,
    build_operator_escalation_routing_request,
    build_operator_escalation_packet_request,
    build_operator_escalation_sla_request,
    build_operator_supervisor_review_request,
    build_operator_escalation_closure_request,
    build_operator_transition_policy_request,
    materialize_governance_work_queue_state,
    materialize_operator_action_outcome_ledger,
    materialize_operator_control_plane_bundle,
    materialize_operator_decision_execution,
    materialize_operator_decision_journal,
    materialize_operator_feedback_state,
    materialize_operator_reentry_queue_state,
    materialize_operator_reentry_assignment,
    materialize_operator_reentry_acceptance,
    materialize_operator_reentry_acknowledgement_timeout,
    materialize_operator_reentry_reassignment,
    materialize_operator_reentry_completion,
    materialize_operator_reentry_completion_attestation,
    materialize_operator_reentry_post_review_gate,
    materialize_operator_post_review_disposition,
    materialize_operator_return_authorization_ledger,
    materialize_operator_return_activation,
    materialize_operator_return_monitoring,
    materialize_operator_restoration_audit,
    materialize_operator_return_drift_breach,
    materialize_operator_return_reopen_loop,
    materialize_operator_reopen_lineage,
    materialize_operator_reopen_recurrence_policy,
    materialize_operator_chronic_instability_packet,
    materialize_operator_recurrence_tribunal_lane,
    materialize_operator_recurrence_tribunal_disposition,
    materialize_operator_chronic_remediation_mandate_ledger,
    materialize_operator_chronic_remediation_satisfaction,
    materialize_operator_freeze_release_gate,
    materialize_operator_freeze_release_attestation,
    materialize_operator_chronic_exit_certification,
    materialize_operator_chronic_exit_return_bridge,
    materialize_operator_monitored_rejoin_policy,
    materialize_operator_monitored_rejoin_activation,
    materialize_operator_chronic_watch_handoff,
    materialize_operator_chronic_watch_outcome,
    materialize_operator_monitored_rejoin_normalization_bridge,
    materialize_operator_normalization_bridge_activation,
    materialize_operator_chronic_watch_audit_convergence,
    materialize_operator_converged_normalization_attestation,
    materialize_operator_chronic_origin_restoration_provenance,
    materialize_operator_provenance_aware_drift_policy,
    materialize_operator_chronic_origin_restoration_audit_overlay,
    materialize_operator_escalation_routing,
    materialize_operator_escalation_packet,
    materialize_operator_escalation_sla,
    materialize_operator_supervisor_review,
    materialize_operator_escalation_closure,
    materialize_operator_transition_policy,
    materialize_operator_queue_snapshot,
    materialize_operator_workboard,
    materialize_operator_workboard_action_contract,
    run_operator_queue_query,
)
from strategy_validator.cli.oracle_queue_command_configs import (
    _configure_governance_surface_inputs,
    _configure_oracle_operator_queue_query,
    _configure_oracle_operator_workboard_query,
    _configure_oracle_operator_workboard_action_contract,
    _configure_oracle_operator_transition_policy,
    _configure_oracle_operator_decision_execution,
    _configure_oracle_operator_escalation_routing,
    _configure_oracle_operator_escalation_packet,
    _configure_oracle_operator_escalation_sla,
    _configure_oracle_operator_decision_journal,
    _configure_oracle_operator_supervisor_review,
    _configure_oracle_operator_escalation_closure,
    _configure_oracle_operator_reentry_queue_state,
    _configure_oracle_operator_reentry_assignment,
    _configure_oracle_operator_reentry_acceptance,
    _configure_oracle_operator_reentry_acknowledgement_timeout,
    _configure_oracle_operator_reentry_completion_attestation,
    _configure_oracle_operator_reentry_post_review_gate,
    _configure_oracle_operator_post_review_disposition,
    _configure_oracle_operator_return_authorization_ledger,
    _configure_oracle_operator_return_activation,
    _configure_oracle_operator_action_outcome_ledger,
    _configure_oracle_operator_feedback_state,
    _configure_oracle_operator_reentry_reassignment,
    _configure_oracle_operator_reentry_completion,
    _configure_oracle_operator_chronic_exit_return_bridge,
    _configure_oracle_operator_monitored_rejoin_policy,
    _configure_oracle_operator_monitored_rejoin_activation,
    _configure_oracle_operator_chronic_watch_handoff,
    _configure_oracle_operator_control_plane_bundle,
    _configure_oracle_operator_return_monitoring,
    _configure_oracle_operator_restoration_audit,
    _configure_oracle_operator_return_drift_breach,
    _configure_oracle_operator_return_reopen_loop,
    _configure_oracle_operator_chronic_watch_outcome,
    _configure_oracle_operator_monitored_rejoin_normalization_bridge,
    _configure_oracle_operator_normalization_bridge_activation,
    _configure_oracle_operator_chronic_watch_audit_convergence,
    _configure_oracle_operator_converged_normalization_attestation,
    _configure_oracle_operator_chronic_origin_restoration_provenance,
    _configure_oracle_operator_chronic_origin_restoration_audit_overlay,
    _configure_oracle_operator_provenance_aware_drift_policy,
    _configure_oracle_operator_reopen_lineage,
    _configure_oracle_operator_reopen_recurrence_policy,
    _configure_oracle_operator_chronic_instability_packet,
    _configure_oracle_operator_recurrence_tribunal_lane,
    _configure_oracle_operator_recurrence_tribunal_disposition,
    _configure_oracle_operator_chronic_remediation_mandate_ledger,
    _configure_oracle_operator_chronic_remediation_satisfaction,
    _configure_oracle_operator_freeze_release_gate,
    _configure_oracle_operator_freeze_release_attestation,
    _configure_oracle_operator_chronic_exit_certification,
)

from strategy_validator.cli.oracle_queue_runners import (
    cmd_oracle_operator_queue_query,
    cmd_oracle_operator_workboard_query,
    cmd_oracle_operator_workboard_action_contract,
    cmd_oracle_operator_transition_policy,
    cmd_oracle_operator_decision_execution,
    cmd_oracle_operator_escalation_routing,
    cmd_oracle_operator_escalation_packet,
    cmd_oracle_operator_escalation_sla,
    cmd_oracle_operator_decision_journal,
    cmd_oracle_operator_supervisor_review,
    cmd_oracle_operator_escalation_closure,
    cmd_oracle_operator_reentry_queue_state,
    cmd_oracle_operator_reentry_assignment,
    cmd_oracle_operator_reentry_acceptance,
    cmd_oracle_operator_reentry_acknowledgement_timeout,
    cmd_oracle_operator_reentry_completion_attestation,
    cmd_oracle_operator_reentry_post_review_gate,
    cmd_oracle_operator_post_review_disposition,
    cmd_oracle_operator_return_authorization_ledger,
    cmd_oracle_operator_return_activation,
    cmd_oracle_operator_action_outcome_ledger,
    cmd_oracle_operator_feedback_state,
    cmd_oracle_operator_reentry_reassignment,
    cmd_oracle_operator_reentry_completion,
    cmd_oracle_operator_chronic_exit_return_bridge,
    cmd_oracle_operator_monitored_rejoin_policy,
    cmd_oracle_operator_monitored_rejoin_activation,
    cmd_oracle_operator_chronic_watch_handoff,
    cmd_oracle_operator_control_plane_bundle,
    cmd_oracle_operator_return_monitoring,
    cmd_oracle_operator_restoration_audit,
    cmd_oracle_operator_return_drift_breach,
    cmd_oracle_operator_return_reopen_loop,
    cmd_oracle_operator_chronic_watch_outcome,
    cmd_oracle_operator_monitored_rejoin_normalization_bridge,
    cmd_oracle_operator_normalization_bridge_activation,
    cmd_oracle_operator_chronic_watch_audit_convergence,
    cmd_oracle_operator_converged_normalization_attestation,
    cmd_oracle_operator_chronic_origin_restoration_provenance,
    cmd_oracle_operator_chronic_origin_restoration_audit_overlay,
    cmd_oracle_operator_provenance_aware_drift_policy,
    cmd_oracle_operator_reopen_lineage,
    cmd_oracle_operator_reopen_recurrence_policy,
    cmd_oracle_operator_chronic_instability_packet,
    cmd_oracle_operator_recurrence_tribunal_lane,
    cmd_oracle_operator_recurrence_tribunal_disposition,
    cmd_oracle_operator_chronic_remediation_mandate_ledger,
    cmd_oracle_operator_chronic_remediation_satisfaction,
    cmd_oracle_operator_freeze_release_gate,
    cmd_oracle_operator_freeze_release_attestation,
    cmd_oracle_operator_chronic_exit_certification,
)



def register_oracle_queue_commands(subparsers: argparse._SubParsersAction[argparse.ArgumentParser], *, runners: dict[str, object]) -> None:
    register_commands(subparsers, [
        CommandSpec('oracle-operator-queue-query', 'Inspect the typed operator queue/work-item surface from governance policy inputs', _configure_oracle_operator_queue_query, runners['oracle-operator-queue-query']),
        CommandSpec('oracle-operator-workboard-query', 'Inspect the typed operator workboard surface from governance policy inputs', _configure_oracle_operator_workboard_query, runners['oracle-operator-workboard-query']),
        CommandSpec('oracle-operator-workboard-action-contract', 'Inspect the typed action-execution contract for operator workboard items', _configure_oracle_operator_workboard_action_contract, runners['oracle-operator-workboard-action-contract']),
        CommandSpec('oracle-operator-transition-policy', 'Inspect the governed transition policy for operator workboard actions', _configure_oracle_operator_transition_policy, runners['oracle-operator-transition-policy']),
        CommandSpec('oracle-operator-decision-journal', 'Materialize an append-safe replayable operator decision journal over workboard action contracts', _configure_oracle_operator_decision_journal, runners['oracle-operator-decision-journal']),
        CommandSpec('oracle-operator-decision-execution', 'Materialize a policy-governed execution report for operator workboard actions', _configure_oracle_operator_decision_execution, runners['oracle-operator-decision-execution']),
        CommandSpec('oracle-operator-escalation-routing', 'Materialize typed escalation routing destinations and remediation obligations for governed executions', _configure_oracle_operator_escalation_routing, runners['oracle-operator-escalation-routing']),
        CommandSpec('oracle-operator-escalation-packet', 'Materialize supervisor-ready escalation packets for routed escalations', _configure_oracle_operator_escalation_packet, runners['oracle-operator-escalation-packet']),
        CommandSpec('oracle-operator-escalation-sla', 'Materialize escalation SLA, aging, and breach posture for supervisor review packets', _configure_oracle_operator_escalation_sla, runners['oracle-operator-escalation-sla']),
        CommandSpec('oracle-operator-supervisor-review', 'Materialize supervisor dispositions for escalated packets', _configure_oracle_operator_supervisor_review, runners['oracle-operator-supervisor-review']),
        CommandSpec('oracle-operator-escalation-closure', 'Materialize escalation closure, requeue, or open-loop status from supervisor review', _configure_oracle_operator_escalation_closure, runners['oracle-operator-escalation-closure']),
        CommandSpec('oracle-operator-reentry-queue-state', 'Materialize requeued operator remediation work from escalation closure outcomes', _configure_oracle_operator_reentry_queue_state, runners['oracle-operator-reentry-queue-state']),
        CommandSpec('oracle-operator-reentry-assignment', 'Materialize assignment ownership and handoff posture for operator remediation reentry work', _configure_oracle_operator_reentry_assignment, runners['oracle-operator-reentry-assignment']),
        CommandSpec('oracle-operator-reentry-acceptance', 'Materialize assignee acknowledgement posture for operator remediation ownership handshakes', _configure_oracle_operator_reentry_acceptance, runners['oracle-operator-reentry-acceptance']),
        CommandSpec('oracle-operator-reentry-acknowledgement-timeout', 'Materialize timeout, reminder, and escalation policy for pending remediation acknowledgements', _configure_oracle_operator_reentry_acknowledgement_timeout, runners['oracle-operator-reentry-acknowledgement-timeout']),
        CommandSpec('oracle-operator-reentry-reassignment', 'Materialize reassignment and backup-owner routing over timed-out remediation acknowledgements', _configure_oracle_operator_reentry_reassignment, runners['oracle-operator-reentry-reassignment']),
        CommandSpec('oracle-operator-reentry-completion', 'Materialize remediation completion, evidence closure, and return-to-normal semantics over reentry cycles', _configure_oracle_operator_reentry_completion, runners['oracle-operator-reentry-completion']),
        CommandSpec('oracle-operator-reentry-completion-attestation', 'Materialize completion attestation and safe-return certification over remediation cycles', _configure_oracle_operator_reentry_completion_attestation, runners['oracle-operator-reentry-completion-attestation']),
        CommandSpec('oracle-operator-reentry-post-review-gate', 'Materialize post-remediation review gating and return authorization over completion attestations', _configure_oracle_operator_reentry_post_review_gate, runners['oracle-operator-reentry-post-review-gate']),
        CommandSpec('oracle-operator-post-review-disposition', 'Materialize durable post-remediation review dispositions over review-gate decisions', _configure_oracle_operator_post_review_disposition, runners['oracle-operator-post-review-disposition']),
        CommandSpec('oracle-operator-return-authorization-ledger', 'Materialize replayable return authorization history over post-review dispositions', _configure_oracle_operator_return_authorization_ledger, runners['oracle-operator-return-authorization-ledger']),
        CommandSpec('oracle-operator-return-activation', 'Materialize activation of authorized remediation returns back into normal operator flow', _configure_oracle_operator_return_activation, runners['oracle-operator-return-activation']),
        CommandSpec('oracle-operator-return-monitoring', 'Materialize post-return monitoring windows and normalization readiness over restored operator work', _configure_oracle_operator_return_monitoring, runners['oracle-operator-return-monitoring']),
        CommandSpec('oracle-operator-restoration-audit', 'Materialize restoration audit states and normalization outcomes over monitored returns', _configure_oracle_operator_restoration_audit, runners['oracle-operator-restoration-audit']),
        CommandSpec('oracle-operator-return-drift-breach', 'Materialize post-return drift breach posture and reopen requirements over restoration audits', _configure_oracle_operator_return_drift_breach, runners['oracle-operator-return-drift-breach']),
        CommandSpec('oracle-operator-return-reopen-loop', 'Materialize reentry reopen-loop state for breached or unstable post-return work', _configure_oracle_operator_return_reopen_loop, runners['oracle-operator-return-reopen-loop']),
        CommandSpec('oracle-operator-action-outcome-ledger', 'Materialize an append-safe replayable operator action outcome ledger over workboard contracts', _configure_oracle_operator_action_outcome_ledger, runners['oracle-operator-action-outcome-ledger']),
        CommandSpec('oracle-operator-feedback-state', 'Derive the current operator feedback state from latest action contracts and outcomes', _configure_oracle_operator_feedback_state, runners['oracle-operator-feedback-state']),

CommandSpec('oracle-operator-reopen-lineage', 'Materialize reopened remediation lineage over post-return reopen loop artifacts', _configure_oracle_operator_reopen_lineage, runners['oracle-operator-reopen-lineage']),
CommandSpec('oracle-operator-reopen-recurrence-policy', 'Materialize recurrence policy and escalation posture for reopened remediation lineage', _configure_oracle_operator_reopen_recurrence_policy, runners['oracle-operator-reopen-recurrence-policy']),
        CommandSpec('oracle-operator-chronic-instability-packet', 'Materialize chronic instability escalation packets for recurrent reopened remediation work', _configure_oracle_operator_chronic_instability_packet, runners['oracle-operator-chronic-instability-packet']),
        CommandSpec('oracle-operator-recurrence-tribunal-lane', 'Materialize tribunal lane routing for chronic or recurrent reopened remediation work', _configure_oracle_operator_recurrence_tribunal_lane, runners['oracle-operator-recurrence-tribunal-lane']),
        CommandSpec('oracle-operator-recurrence-tribunal-disposition', 'Materialize durable tribunal dispositions for recurrent or chronic reopened remediation work', _configure_oracle_operator_recurrence_tribunal_disposition, runners['oracle-operator-recurrence-tribunal-disposition']),
        CommandSpec('oracle-operator-chronic-remediation-mandate-ledger', 'Materialize replayable chronic-remediation mandate history over tribunal dispositions', _configure_oracle_operator_chronic_remediation_mandate_ledger, runners['oracle-operator-chronic-remediation-mandate-ledger']),
        CommandSpec('oracle-operator-chronic-remediation-satisfaction', 'Materialize chronic-remediation satisfaction evidence and freeze-release eligibility over mandate history', _configure_oracle_operator_chronic_remediation_satisfaction, runners['oracle-operator-chronic-remediation-satisfaction']),
        CommandSpec('oracle-operator-freeze-release-gate', 'Materialize freeze-release authorization decisions over chronic-remediation satisfaction evidence', _configure_oracle_operator_freeze_release_gate, runners['oracle-operator-freeze-release-gate']),
        CommandSpec('oracle-operator-freeze-release-attestation', 'Materialize evidence-backed freeze-release attestations over authorized chronic remediation release gates', _configure_oracle_operator_freeze_release_attestation, runners['oracle-operator-freeze-release-attestation']),
        CommandSpec('oracle-operator-chronic-exit-certification', 'Materialize chronic exit certification over freeze-release attestations for safe return-path rejoin', _configure_oracle_operator_chronic_exit_certification, runners['oracle-operator-chronic-exit-certification']),
        CommandSpec('oracle-operator-chronic-exit-return-bridge', 'Bridge chronic exit certification back into the typed return-authorization path', _configure_oracle_operator_chronic_exit_return_bridge, runners['oracle-operator-chronic-exit-return-bridge']),
        CommandSpec('oracle-operator-monitored-rejoin-policy', 'Materialize monitored rejoin policy over bridged chronic exit certification', _configure_oracle_operator_monitored_rejoin_policy, runners['oracle-operator-monitored-rejoin-policy']),
        CommandSpec('oracle-operator-monitored-rejoin-activation', 'Materialize activation of chronic monitored rejoin back into the return path', _configure_oracle_operator_monitored_rejoin_activation, runners['oracle-operator-monitored-rejoin-activation']),
        CommandSpec('oracle-operator-chronic-watch-handoff', 'Materialize chronic watch handoff into the return monitoring lane for monitored rejoin activations', _configure_oracle_operator_chronic_watch_handoff, runners['oracle-operator-chronic-watch-handoff']),
        CommandSpec('oracle-operator-chronic-watch-outcome', 'Materialize typed outcomes over chronic watch handoffs, including stable, active, and breached monitored rejoins', _configure_oracle_operator_chronic_watch_outcome, runners['oracle-operator-chronic-watch-outcome']),
        CommandSpec('oracle-operator-monitored-rejoin-normalization-bridge', 'Bridge chronic watch outcomes back into normalization, continued watch, or reopen routing', _configure_oracle_operator_monitored_rejoin_normalization_bridge, runners['oracle-operator-monitored-rejoin-normalization-bridge']),
        CommandSpec('oracle-operator-normalization-bridge-activation', 'Activate monitored rejoin normalization bridges into the standard return-monitoring and restoration-audit loop', _configure_oracle_operator_normalization_bridge_activation, runners['oracle-operator-normalization-bridge-activation']),
        CommandSpec('oracle-operator-chronic-watch-audit-convergence', 'Converge chronic watch normalization activations into the standard return-monitoring and restoration-audit evidence path', _configure_oracle_operator_chronic_watch_audit_convergence, runners['oracle-operator-chronic-watch-audit-convergence']),
        CommandSpec('oracle-operator-converged-normalization-attestation', 'Materialize attestation over chronic-origin normalization convergence before standard restoration resumes', _configure_oracle_operator_converged_normalization_attestation, runners['oracle-operator-converged-normalization-attestation']),
        CommandSpec('oracle-operator-chronic-origin-restoration-provenance', 'Materialize chronic-origin provenance for work that converged back into the standard restoration path', _configure_oracle_operator_chronic_origin_restoration_provenance, runners['oracle-operator-chronic-origin-restoration-provenance']),
        CommandSpec('oracle-operator-chronic-origin-restoration-audit-overlay', 'Materialize restoration-audit overlays for chronic-origin work that rejoined the standard path', _configure_oracle_operator_chronic_origin_restoration_audit_overlay, runners['oracle-operator-chronic-origin-restoration-audit-overlay']),
        CommandSpec('oracle-operator-provenance-aware-drift-policy', 'Materialize provenance-aware drift policy over chronic-origin restoration audit overlays', _configure_oracle_operator_provenance_aware_drift_policy, runners['oracle-operator-provenance-aware-drift-policy']),
        CommandSpec('oracle-operator-control-plane-bundle', 'Materialize a durable operator control-plane bundle across query, workboard, action contract, journal, outcomes, and feedback state', _configure_oracle_operator_control_plane_bundle, runners['oracle-operator-control-plane-bundle']),
    ])


