from __future__ import annotations

import argparse

from strategy_validator.cli.command_registry import CommandSpec, register_commands
from strategy_validator.cli.oracle_pack_command_configs import (
    _configure_oracle_operator_pack_query,
    _configure_oracle_operator_pack_workbench,
    _configure_oracle_operator_pack_navigation,
    _configure_oracle_operator_pack_dashboard,
    _configure_oracle_operator_pack_timeline,
    _configure_oracle_operator_pack_comparison,
    _configure_oracle_operator_pack_drift,
    _configure_oracle_operator_pack_escalation,
    _configure_oracle_operator_pack_assignment,
    _configure_oracle_operator_pack_claim_lease,
    _configure_oracle_operator_pack_lease_governance,
    _configure_oracle_operator_pack_execution_readiness,
    _configure_oracle_operator_pack_dispatch_outcome,
    _configure_oracle_operator_pack_approval_needed,
    _configure_oracle_operator_pack_approval_disposition,
    _configure_oracle_operator_pack_execution_authorization,
    _configure_oracle_operator_pack_execution_exception,
    _configure_oracle_operator_pack_execution_force,
    _configure_oracle_operator_pack_dispatch_permission,
    _configure_oracle_operator_pack_claim_operability,
    _configure_oracle_operator_pack_claim_lifecycle,
    _configure_oracle_operator_pack_handoff,
    _configure_oracle_operator_pack_terminal_resolution,
    _configure_oracle_operator_pack_terminal_archive,
    _configure_oracle_operator_pack_terminal_record,
    _configure_oracle_operator_pack_terminal_record_publish,
    _configure_oracle_operator_pack_terminal_closure,
    _configure_oracle_operator_pack_execution_finality,
 )
from strategy_validator.cli.oracle_pack_runners import (
    cmd_oracle_operator_pack_query,
    cmd_oracle_operator_pack_workbench,
    cmd_oracle_operator_pack_navigation,
    cmd_oracle_operator_pack_timeline,
    cmd_oracle_operator_pack_dashboard,
    cmd_oracle_operator_pack_comparison,
    cmd_oracle_operator_pack_drift,
    cmd_oracle_operator_pack_escalation,
    cmd_oracle_operator_pack_assignment,
    cmd_oracle_operator_pack_claim_lease,
    cmd_oracle_operator_pack_claim_operability,
    cmd_oracle_operator_pack_claim_lifecycle,
    cmd_oracle_operator_pack_lease_governance,
    cmd_oracle_operator_pack_execution_readiness,
    cmd_oracle_operator_pack_dispatch_outcome,
    cmd_oracle_operator_pack_execution_exception,
    cmd_oracle_operator_pack_approval_needed,
    cmd_oracle_operator_pack_approval_disposition,
    cmd_oracle_operator_pack_execution_authorization,
    cmd_oracle_operator_pack_execution_force,
    cmd_oracle_operator_pack_terminal_resolution,
    cmd_oracle_operator_pack_terminal_record_publish,
    cmd_oracle_operator_pack_terminal_closure,
    cmd_oracle_operator_pack_terminal_archive,
    cmd_oracle_operator_pack_terminal_record,
    cmd_oracle_operator_pack_execution_finality,
    cmd_oracle_operator_pack_dispatch_permission,
    cmd_oracle_operator_pack_handoff,
)


def register_oracle_pack_commands(
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser],
    *,
    runners: dict[str, object],
) -> None:
    register_commands(
        subparsers,
        [
            CommandSpec('oracle-operator-pack-query', 'Query the shared operator pack index for discoverable operator packs', _configure_oracle_operator_pack_query, runners['oracle-operator-pack-query']),
            CommandSpec('oracle-operator-pack-workbench', 'Render a structured operator workbench over the shared operator pack index', _configure_oracle_operator_pack_workbench, runners['oracle-operator-pack-workbench']),
            CommandSpec('oracle-operator-pack-navigation', 'Select latest relevant operator packs from the shared workbench/index', _configure_oracle_operator_pack_navigation, runners['oracle-operator-pack-navigation']),
            CommandSpec('oracle-operator-pack-dashboard', 'Render a structured operator pack dashboard over workbench plus navigation', _configure_oracle_operator_pack_dashboard, runners['oracle-operator-pack-dashboard']),
            CommandSpec('oracle-operator-pack-timeline', 'Render a structured operator pack timeline over indexed pack activity', _configure_oracle_operator_pack_timeline, runners['oracle-operator-pack-timeline']),
            CommandSpec('oracle-operator-pack-comparison', 'Render a structured operator pack comparison over recent indexed pack generations', _configure_oracle_operator_pack_comparison, runners['oracle-operator-pack-comparison']),
            CommandSpec('oracle-operator-pack-drift', 'Render a structured operator pack drift alert surface over worsening or sustained degraded indexed packs', _configure_oracle_operator_pack_drift, runners['oracle-operator-pack-drift']),
            CommandSpec('oracle-operator-pack-escalation', 'Render a structured operator pack escalation surface over drift plus operator routing context', _configure_oracle_operator_pack_escalation, runners['oracle-operator-pack-escalation']),
            CommandSpec('oracle-operator-pack-assignment', 'Render a structured operator pack assignment surface over escalation plus ownership context', _configure_oracle_operator_pack_assignment, runners['oracle-operator-pack-assignment']),
            CommandSpec('oracle-operator-pack-handoff', 'Render a structured operator pack handoff surface over assignment plus acknowledgement context', _configure_oracle_operator_pack_handoff, runners['oracle-operator-pack-handoff']),
            CommandSpec('oracle-operator-pack-claim-lease', 'Render a structured operator pack claim/lease surface over handoff plus workboard context', _configure_oracle_operator_pack_claim_lease, runners['oracle-operator-pack-claim-lease']),
            CommandSpec('oracle-operator-pack-claim-lifecycle', 'Render a structured operator pack claim lifecycle surface over claim/lease plus workboard context', _configure_oracle_operator_pack_claim_lifecycle, runners['oracle-operator-pack-claim-lifecycle']),
            CommandSpec('oracle-operator-pack-claim-operability', 'Render a structured operator pack claim-operability surface over execution readiness plus claim lifecycle', _configure_oracle_operator_pack_claim_operability, runners['oracle-operator-pack-claim-operability']),
            CommandSpec('oracle-operator-pack-lease-governance', 'Render a structured operator pack lease governance surface over claim lifecycle plus escalation context', _configure_oracle_operator_pack_lease_governance, runners['oracle-operator-pack-lease-governance']),
            CommandSpec('oracle-operator-pack-execution-readiness', 'Render a structured operator pack execution readiness surface over lease governance plus handoff context', _configure_oracle_operator_pack_execution_readiness, runners['oracle-operator-pack-execution-readiness']),
            CommandSpec('oracle-operator-pack-dispatch-permission', 'Render a structured operator pack dispatch-permission surface over execution readiness plus claim/lease context', _configure_oracle_operator_pack_dispatch_permission, runners['oracle-operator-pack-dispatch-permission']),
            CommandSpec('oracle-operator-pack-dispatch-outcome', 'Render a structured operator pack dispatch-outcome surface over dispatch permission plus lease-governance context', _configure_oracle_operator_pack_dispatch_outcome, runners['oracle-operator-pack-dispatch-outcome']),
            CommandSpec('oracle-operator-pack-execution-exception', 'Render a structured operator pack execution-exception surface over dispatch outcome plus lease-governance context', _configure_oracle_operator_pack_execution_exception, runners['oracle-operator-pack-execution-exception']),
            CommandSpec('oracle-operator-pack-approval-needed', 'Render a structured operator pack approval-needed surface over execution exception plus handoff context', _configure_oracle_operator_pack_approval_needed, runners['oracle-operator-pack-approval-needed']),
            CommandSpec('oracle-operator-pack-approval-disposition', 'Render a structured operator pack approval-disposition surface over approval-needed plus claim/lease context', _configure_oracle_operator_pack_approval_disposition, runners['oracle-operator-pack-approval-disposition']),
            CommandSpec('oracle-operator-pack-execution-authorization', 'Render a structured operator pack execution-authorization surface over approval disposition plus dispatch permission', _configure_oracle_operator_pack_execution_authorization, runners['oracle-operator-pack-execution-authorization']),
            CommandSpec('oracle-operator-pack-execution-force', 'Render a structured operator pack forced-execution surface over execution authorization plus execution exception', _configure_oracle_operator_pack_execution_force, runners['oracle-operator-pack-execution-force']),
            CommandSpec('oracle-operator-pack-execution-finality', 'Render a structured operator pack execution-finality surface over forced execution plus dispatch outcome', _configure_oracle_operator_pack_execution_finality, runners['oracle-operator-pack-execution-finality']),
            CommandSpec('oracle-operator-pack-terminal-resolution', 'Render a structured operator pack terminal-resolution surface over execution finality plus approval disposition', _configure_oracle_operator_pack_terminal_resolution, runners['oracle-operator-pack-terminal-resolution']),
            CommandSpec('oracle-operator-pack-terminal-closure', 'Render a structured operator pack terminal-closure surface over terminal resolution plus claim lifecycle', _configure_oracle_operator_pack_terminal_closure, runners['oracle-operator-pack-terminal-closure']),
            CommandSpec('oracle-operator-pack-terminal-archive', 'Render a structured operator pack terminal-archive surface over terminal closure plus pack registry', _configure_oracle_operator_pack_terminal_archive, runners['oracle-operator-pack-terminal-archive']),
            CommandSpec('oracle-operator-pack-terminal-record', 'Render a structured operator pack terminal-record surface over terminal archive plus pack registry index', _configure_oracle_operator_pack_terminal_record, runners['oracle-operator-pack-terminal-record']),
            CommandSpec('oracle-operator-pack-terminal-record-publish', 'Publish a durable operator terminal-record bundle plus manifest/index', _configure_oracle_operator_pack_terminal_record_publish, runners['oracle-operator-pack-terminal-record-publish']),
        ],
    )



__all__ = [
    'register_oracle_pack_commands',
    'cmd_oracle_operator_pack_query',
    'cmd_oracle_operator_pack_workbench',
    'cmd_oracle_operator_pack_navigation',
    'cmd_oracle_operator_pack_timeline',
    'cmd_oracle_operator_pack_dashboard',
    'cmd_oracle_operator_pack_comparison',
    'cmd_oracle_operator_pack_drift',
    'cmd_oracle_operator_pack_escalation',
    'cmd_oracle_operator_pack_assignment',
    'cmd_oracle_operator_pack_claim_lease',
    'cmd_oracle_operator_pack_claim_operability',
    'cmd_oracle_operator_pack_claim_lifecycle',
    'cmd_oracle_operator_pack_lease_governance',
    'cmd_oracle_operator_pack_execution_readiness',
    'cmd_oracle_operator_pack_dispatch_outcome',
    'cmd_oracle_operator_pack_execution_exception',
    'cmd_oracle_operator_pack_approval_needed',
    'cmd_oracle_operator_pack_approval_disposition',
    'cmd_oracle_operator_pack_execution_authorization',
    'cmd_oracle_operator_pack_execution_force',
    'cmd_oracle_operator_pack_terminal_resolution',
    'cmd_oracle_operator_pack_terminal_record_publish',
    'cmd_oracle_operator_pack_terminal_closure',
    'cmd_oracle_operator_pack_terminal_archive',
    'cmd_oracle_operator_pack_terminal_record',
    'cmd_oracle_operator_pack_execution_finality',
    'cmd_oracle_operator_pack_dispatch_permission',
    'cmd_oracle_operator_pack_handoff',
]
