from __future__ import annotations

import argparse

from strategy_validator.cli.oracle_event_constitutional_commands import register_oracle_event_constitutional_commands
from strategy_validator.cli.oracle_event_projection_runners import (
    cmd_oracle_derived_view,
    cmd_oracle_event_checkpoint,
    cmd_oracle_event_log_append,
    cmd_oracle_horizon_checkpoint,
    cmd_oracle_horizon_view,
    cmd_oracle_rolling_review,
    cmd_oracle_rolling_review_checkpoint,
    cmd_verify_oracle_event_checkpoint,
)
from strategy_validator.cli.oracle_event_constitutional_runners import (
    cmd_oracle_annual_lane_append,
    cmd_oracle_annual_review,
    cmd_oracle_annual_review_evidence,
    cmd_oracle_constitutional_digest,
    cmd_oracle_constitutional_digest_evidence,
    cmd_oracle_constitutional_gate,
    cmd_oracle_constitutional_lane_append,
    cmd_oracle_diagnose,
    cmd_oracle_doctrine_drift,
    cmd_oracle_doctrine_drift_evidence,
    cmd_oracle_doctrine_lane_append,
    cmd_oracle_doctrine_lineage_index,
    cmd_oracle_doctrine_lineage_verify,
    cmd_oracle_explain,
    cmd_oracle_incident_pack,
    cmd_oracle_memory_append,
    cmd_oracle_memory_review,
    cmd_oracle_memory_review_evidence,
    cmd_oracle_memory_summary,
    cmd_oracle_monthly_digest,
    cmd_oracle_monthly_digest_evidence,
    cmd_oracle_monthly_lane_append,
    cmd_oracle_quarterly_lane_append,
    cmd_oracle_quarterly_review,
    cmd_oracle_quarterly_review_evidence,
    cmd_oracle_replay_audit,
    cmd_oracle_review_lane_append,
    cmd_oracle_semiannual_audit,
    cmd_oracle_semiannual_audit_evidence,
    cmd_oracle_semiannual_lane_append,
    cmd_oracle_status_pack,
    cmd_oracle_transition_evidence,
    cmd_oracle_weekly_digest,
    cmd_oracle_weekly_digest_evidence,
    cmd_verify_oracle_annual_review_evidence,
    cmd_verify_oracle_constitutional_digest_evidence,
    cmd_verify_oracle_doctrine_drift_evidence,
    cmd_verify_oracle_memory_review_evidence,
    cmd_verify_oracle_monthly_digest_evidence,
    cmd_verify_oracle_quarterly_review_evidence,
    cmd_verify_oracle_semiannual_audit_evidence,
    cmd_verify_oracle_transition_evidence,
    cmd_verify_oracle_weekly_digest_evidence,
)

EVENT_RUNNERS = {
    "oracle-derived-view": cmd_oracle_derived_view,
    "oracle-event-checkpoint": cmd_oracle_event_checkpoint,
    "oracle-event-log-append": cmd_oracle_event_log_append,
    "oracle-horizon-checkpoint": cmd_oracle_horizon_checkpoint,
    "oracle-horizon-view": cmd_oracle_horizon_view,
    "oracle-rolling-review": cmd_oracle_rolling_review,
    "oracle-rolling-review-checkpoint": cmd_oracle_rolling_review_checkpoint,
    "verify-oracle-event-checkpoint": cmd_verify_oracle_event_checkpoint,
    "oracle-annual-lane-append": cmd_oracle_annual_lane_append,
    "oracle-annual-review": cmd_oracle_annual_review,
    "oracle-annual-review-evidence": cmd_oracle_annual_review_evidence,
    "oracle-constitutional-digest": cmd_oracle_constitutional_digest,
    "oracle-constitutional-digest-evidence": cmd_oracle_constitutional_digest_evidence,
    "oracle-constitutional-gate": cmd_oracle_constitutional_gate,
    "oracle-constitutional-lane-append": cmd_oracle_constitutional_lane_append,
    "oracle-diagnose": cmd_oracle_diagnose,
    "oracle-doctrine-drift": cmd_oracle_doctrine_drift,
    "oracle-doctrine-drift-evidence": cmd_oracle_doctrine_drift_evidence,
    "oracle-doctrine-lane-append": cmd_oracle_doctrine_lane_append,
    "oracle-doctrine-lineage-index": cmd_oracle_doctrine_lineage_index,
    "oracle-doctrine-lineage-verify": cmd_oracle_doctrine_lineage_verify,
    "oracle-explain": cmd_oracle_explain,
    "oracle-incident-pack": cmd_oracle_incident_pack,
    "oracle-memory-append": cmd_oracle_memory_append,
    "oracle-memory-review": cmd_oracle_memory_review,
    "oracle-memory-review-evidence": cmd_oracle_memory_review_evidence,
    "oracle-memory-summary": cmd_oracle_memory_summary,
    "oracle-monthly-digest": cmd_oracle_monthly_digest,
    "oracle-monthly-digest-evidence": cmd_oracle_monthly_digest_evidence,
    "oracle-monthly-lane-append": cmd_oracle_monthly_lane_append,
    "oracle-quarterly-lane-append": cmd_oracle_quarterly_lane_append,
    "oracle-quarterly-review": cmd_oracle_quarterly_review,
    "oracle-quarterly-review-evidence": cmd_oracle_quarterly_review_evidence,
    "oracle-replay-audit": cmd_oracle_replay_audit,
    "oracle-review-lane-append": cmd_oracle_review_lane_append,
    "oracle-semiannual-audit": cmd_oracle_semiannual_audit,
    "oracle-semiannual-audit-evidence": cmd_oracle_semiannual_audit_evidence,
    "oracle-semiannual-lane-append": cmd_oracle_semiannual_lane_append,
    "oracle-status-pack": cmd_oracle_status_pack,
    "oracle-transition-evidence": cmd_oracle_transition_evidence,
    "oracle-weekly-digest": cmd_oracle_weekly_digest,
    "oracle-weekly-digest-evidence": cmd_oracle_weekly_digest_evidence,
    "verify-oracle-annual-review-evidence": cmd_verify_oracle_annual_review_evidence,
    "verify-oracle-constitutional-digest-evidence": cmd_verify_oracle_constitutional_digest_evidence,
    "verify-oracle-doctrine-drift-evidence": cmd_verify_oracle_doctrine_drift_evidence,
    "verify-oracle-memory-review-evidence": cmd_verify_oracle_memory_review_evidence,
    "verify-oracle-monthly-digest-evidence": cmd_verify_oracle_monthly_digest_evidence,
    "verify-oracle-quarterly-review-evidence": cmd_verify_oracle_quarterly_review_evidence,
    "verify-oracle-semiannual-audit-evidence": cmd_verify_oracle_semiannual_audit_evidence,
    "verify-oracle-transition-evidence": cmd_verify_oracle_transition_evidence,
    "verify-oracle-weekly-digest-evidence": cmd_verify_oracle_weekly_digest_evidence,
}


def register_oracle_event_runtime_commands(
    sub: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    register_oracle_event_constitutional_commands(sub, runners=EVENT_RUNNERS)
