from __future__ import annotations

import argparse

from strategy_validator.cli.command_registry import CommandSpec, register_commands
from strategy_validator.cli.oracle_queue_command_configs import (
    _configure_oracle_operator_action_outcome_ledger,
    _configure_oracle_operator_chronic_exit_certification,
    _configure_oracle_operator_chronic_exit_return_bridge,
    _configure_oracle_operator_chronic_instability_packet,
    _configure_oracle_operator_chronic_origin_restoration_audit_overlay,
    _configure_oracle_operator_chronic_origin_restoration_provenance,
    _configure_oracle_operator_chronic_remediation_mandate_ledger,
    _configure_oracle_operator_chronic_remediation_satisfaction,
    _configure_oracle_operator_chronic_watch_audit_convergence,
    _configure_oracle_operator_chronic_watch_handoff,
    _configure_oracle_operator_chronic_watch_outcome,
    _configure_oracle_operator_converged_normalization_attestation,
    _configure_oracle_operator_feedback_state,
    _configure_oracle_operator_freeze_release_attestation,
    _configure_oracle_operator_freeze_release_gate,
    _configure_oracle_operator_monitored_rejoin_activation,
    _configure_oracle_operator_monitored_rejoin_normalization_bridge,
    _configure_oracle_operator_monitored_rejoin_policy,
    _configure_oracle_operator_normalization_bridge_activation,
    _configure_oracle_operator_post_review_disposition,
    _configure_oracle_operator_provenance_aware_drift_policy,
    _configure_oracle_operator_recurrence_tribunal_disposition,
    _configure_oracle_operator_recurrence_tribunal_lane,
    _configure_oracle_operator_reentry_acceptance,
    _configure_oracle_operator_reentry_acknowledgement_timeout,
    _configure_oracle_operator_reentry_assignment,
    _configure_oracle_operator_reentry_completion,
    _configure_oracle_operator_reentry_completion_attestation,
    _configure_oracle_operator_reentry_post_review_gate,
    _configure_oracle_operator_reentry_queue_state,
    _configure_oracle_operator_reentry_reassignment,
    _configure_oracle_operator_reopen_lineage,
    _configure_oracle_operator_reopen_recurrence_policy,
    _configure_oracle_operator_restoration_audit,
    _configure_oracle_operator_return_activation,
    _configure_oracle_operator_return_authorization_ledger,
    _configure_oracle_operator_return_drift_breach,
    _configure_oracle_operator_return_monitoring,
    _configure_oracle_operator_return_reopen_loop,
)


def register_oracle_queue_transition_reentry_commands(
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser],
    *,
    runners: dict[str, object],
) -> None:
    register_commands(
        subparsers,
        [
            CommandSpec('oracle-operator-reentry-queue-state', 'Materialize requeued operator remediation work from escalation closure outcomes', _configure_oracle_operator_reentry_queue_state, runners['oracle-operator-reentry-queue-state']),
            CommandSpec('oracle-operator-reentry-assignment', 'Materialize assignment ownership and handoff posture for operator remediation reentry work', _configure_oracle_operator_reentry_assignment, runners['oracle-operator-reentry-assignment']),
            CommandSpec('oracle-operator-reentry-acceptance', 'Materialize assignee acknowledgement posture for operator remediation ownership handshakes', _configure_oracle_operator_reentry_acceptance, runners['oracle-operator-reentry-acceptance']),
            CommandSpec('oracle-operator-reentry-acknowledgement-timeout', 'Materialize timeout, reminder, and escalation policy for pending remediation acknowledgements', _configure_oracle_operator_reentry_acknowledgement_timeout, runners['oracle-operator-reentry-acknowledgement-timeout']),
            CommandSpec('oracle-operator-reentry-reassignment', 'Materialize reassignment and backup-owner routing over timed-out remediation acknowledgements', _configure_oracle_operator_reentry_reassignment, runners['oracle-operator-reentry-reassignment']),
            CommandSpec('oracle-operator-reentry-completion', 'Materialize remediation completion, evidence closure, and return-to-normal semantics over reentry cycles', _configure_oracle_operator_reentry_completion, runners['oracle-operator-reentry-completion']),
            CommandSpec('oracle-operator-reentry-completion-attestation', 'Materialize completion attestation and safe-return certification over remediation cycles', _configure_oracle_operator_reentry_completion_attestation, runners['oracle-operator-reentry-completion-attestation']),
            CommandSpec('oracle-operator-reentry-post-review-gate', 'Materialize post-remediation review gating and return authorization over completion attestations', _configure_oracle_operator_reentry_post_review_gate, runners['oracle-operator-reentry-post-review-gate']),
            CommandSpec('oracle-operator-post-review-disposition', 'Materialize durable post-remediation review dispositions over review-gate decisions', _configure_oracle_operator_post_review_disposition, runners['oracle-operator-post-review-disposition']),
            CommandSpec('oracle-operator-return-authorization-ledger', 'Materialize replayable return authorization history over post-review dispositions', _configure_oracle_operator_return_authorization_ledger, runners['oracle-operator-return-authorization-ledger']),
            CommandSpec('oracle-operator-return-activation', 'Materialize activation of authorized remediation returns back into normal operator flow', _configure_oracle_operator_return_activation, runners['oracle-operator-return-activation']),
            CommandSpec('oracle-operator-return-monitoring', 'Materialize post-return monitoring windows and normalization readiness over restored operator work', _configure_oracle_operator_return_monitoring, runners['oracle-operator-return-monitoring']),
            CommandSpec('oracle-operator-restoration-audit', 'Materialize restoration audit states and normalization outcomes over monitored returns', _configure_oracle_operator_restoration_audit, runners['oracle-operator-restoration-audit']),
            CommandSpec('oracle-operator-return-drift-breach', 'Materialize drift, relapse, and breach signals over monitored returns', _configure_oracle_operator_return_drift_breach, runners['oracle-operator-return-drift-breach']),
            CommandSpec('oracle-operator-return-reopen-loop', 'Materialize re-open loops and escalation posture over breached returns', _configure_oracle_operator_return_reopen_loop, runners['oracle-operator-return-reopen-loop']),
            CommandSpec('oracle-operator-action-outcome-ledger', 'Materialize append-safe action-outcome ledgers over operator execution and review cycles', _configure_oracle_operator_action_outcome_ledger, runners['oracle-operator-action-outcome-ledger']),
            CommandSpec('oracle-operator-feedback-state', 'Materialize durable operator feedback-state over governed action-outcome ledgers', _configure_oracle_operator_feedback_state, runners['oracle-operator-feedback-state']),
            CommandSpec('oracle-operator-reopen-lineage', 'Materialize deterministic lineage over reopened operator return loops', _configure_oracle_operator_reopen_lineage, runners['oracle-operator-reopen-lineage']),
            CommandSpec('oracle-operator-reopen-recurrence-policy', 'Materialize recurrence policy over repeated reopen loops to decide chronic-instability escalation', _configure_oracle_operator_reopen_recurrence_policy, runners['oracle-operator-reopen-recurrence-policy']),
            CommandSpec('oracle-operator-chronic-instability-packet', 'Materialize chronic-instability packets over repeated reopen loops', _configure_oracle_operator_chronic_instability_packet, runners['oracle-operator-chronic-instability-packet']),
            CommandSpec('oracle-operator-recurrence-tribunal-lane', 'Materialize tribunal lanes for chronic-instability packets', _configure_oracle_operator_recurrence_tribunal_lane, runners['oracle-operator-recurrence-tribunal-lane']),
            CommandSpec('oracle-operator-recurrence-tribunal-disposition', 'Materialize tribunal dispositions over chronic-instability lanes', _configure_oracle_operator_recurrence_tribunal_disposition, runners['oracle-operator-recurrence-tribunal-disposition']),
            CommandSpec('oracle-operator-chronic-remediation-mandate-ledger', 'Materialize mandate ledgers for tribunal-ordered chronic remediation packages', _configure_oracle_operator_chronic_remediation_mandate_ledger, runners['oracle-operator-chronic-remediation-mandate-ledger']),
            CommandSpec('oracle-operator-chronic-remediation-satisfaction', 'Materialize remediation satisfaction and sufficiency posture over mandate ledgers', _configure_oracle_operator_chronic_remediation_satisfaction, runners['oracle-operator-chronic-remediation-satisfaction']),
            CommandSpec('oracle-operator-freeze-release-gate', 'Materialize freeze-release gate posture over satisfied chronic-remediation mandates', _configure_oracle_operator_freeze_release_gate, runners['oracle-operator-freeze-release-gate']),
            CommandSpec('oracle-operator-freeze-release-attestation', 'Materialize release attestations over freeze-release gate outcomes', _configure_oracle_operator_freeze_release_attestation, runners['oracle-operator-freeze-release-attestation']),
            CommandSpec('oracle-operator-chronic-exit-certification', 'Materialize chronic-exit certification over approved freeze-release attestations', _configure_oracle_operator_chronic_exit_certification, runners['oracle-operator-chronic-exit-certification']),
            CommandSpec('oracle-operator-chronic-exit-return-bridge', 'Materialize the bridge from chronic-exit certification into monitored return', _configure_oracle_operator_chronic_exit_return_bridge, runners['oracle-operator-chronic-exit-return-bridge']),
            CommandSpec('oracle-operator-monitored-rejoin-policy', 'Materialize monitored-rejoin policy over certified chronic exits', _configure_oracle_operator_monitored_rejoin_policy, runners['oracle-operator-monitored-rejoin-policy']),
            CommandSpec('oracle-operator-monitored-rejoin-activation', 'Materialize monitored-rejoin activation over approved monitored-rejoin policy', _configure_oracle_operator_monitored_rejoin_activation, runners['oracle-operator-monitored-rejoin-activation']),
            CommandSpec('oracle-operator-chronic-watch-handoff', 'Materialize chronic-watch handoff packets over activated monitored rejoins', _configure_oracle_operator_chronic_watch_handoff, runners['oracle-operator-chronic-watch-handoff']),
            CommandSpec('oracle-operator-chronic-watch-outcome', 'Materialize chronic-watch outcomes over monitored rejoin handoffs', _configure_oracle_operator_chronic_watch_outcome, runners['oracle-operator-chronic-watch-outcome']),
            CommandSpec('oracle-operator-monitored-rejoin-normalization-bridge', 'Materialize the normalization bridge from chronic-watch outcomes into normal operations', _configure_oracle_operator_monitored_rejoin_normalization_bridge, runners['oracle-operator-monitored-rejoin-normalization-bridge']),
            CommandSpec('oracle-operator-normalization-bridge-activation', 'Materialize activation of normalization bridges over approved chronic-watch outcomes', _configure_oracle_operator_normalization_bridge_activation, runners['oracle-operator-normalization-bridge-activation']),
            CommandSpec('oracle-operator-chronic-watch-audit-convergence', 'Materialize audit convergence over normalization-bridge activations', _configure_oracle_operator_chronic_watch_audit_convergence, runners['oracle-operator-chronic-watch-audit-convergence']),
            CommandSpec('oracle-operator-converged-normalization-attestation', 'Materialize normalization attestations over converged chronic-watch audits', _configure_oracle_operator_converged_normalization_attestation, runners['oracle-operator-converged-normalization-attestation']),
            CommandSpec('oracle-operator-chronic-origin-restoration-provenance', 'Materialize restoration provenance over converged normalizations', _configure_oracle_operator_chronic_origin_restoration_provenance, runners['oracle-operator-chronic-origin-restoration-provenance']),
            CommandSpec('oracle-operator-chronic-origin-restoration-audit-overlay', 'Materialize restoration audit overlays over chronic-origin normalization paths', _configure_oracle_operator_chronic_origin_restoration_audit_overlay, runners['oracle-operator-chronic-origin-restoration-audit-overlay']),
            CommandSpec('oracle-operator-provenance-aware-drift-policy', 'Materialize provenance-aware drift policy over restored chronic-origin operator state', _configure_oracle_operator_provenance_aware_drift_policy, runners['oracle-operator-provenance-aware-drift-policy']),
        ],
    )


__all__ = ['register_oracle_queue_transition_reentry_commands']
