from __future__ import annotations

from collections.abc import Callable, Mapping
import argparse

Runner = Callable[[argparse.Namespace], int]


def register_oracle_strategy_reporting_commands(
    sub: argparse._SubParsersAction[argparse.ArgumentParser],
    *,
    runners: Mapping[str, Runner],
) -> None:
    oa = sub.add_parser("oracle-advisory", help="Build an advisory-only oracle morning attestation from deterministic sensor inputs")
    oa.add_argument("input", help="Oracle advisory input JSON path")
    oa.add_argument("--output", default="", help="Write ORACLE_MORNING_ATTESTATION.json path")
    oa.add_argument("--markdown-output", default="", help="Write ORACLE_MORNING_ATTESTATION.md path")
    oa.set_defaults(_run=runners["cmd_oracle_advisory"])

    osi = sub.add_parser("oracle-sensor-ingest", help="Normalize raw macro, semantic, and microstructure payloads into canonical oracle advisory sensors")
    osi.add_argument("input", help="Path to ORACLE_SENSOR_INGESTION_INPUT.json")
    osi.add_argument("--output", default="", help="Write ORACLE_SENSOR_INGESTION_REPORT.json path")
    osi.add_argument("--advisory-input-output", default="", help="Write normalized ORACLE_ADVISORY_INPUT.json path")
    osi.add_argument("--markdown-output", default="", help="Write ORACLE_SENSOR_INGESTION_REPORT.md path")
    osi.set_defaults(_run=runners["cmd_oracle_sensor_ingest"])

    osf = sub.add_parser("oracle-signal-fusion", help="Fuse normalized oracle sensors into strategic posture, doctrine stress, and opportunity/caution guidance")
    osf.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    osf.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    osf.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    osf.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    osf.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    osf.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_FUSION_REPORT.json path")
    osf.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_FUSION_REPORT.md path")
    osf.set_defaults(_run=runners["cmd_oracle_signal_fusion"])

    ooq = sub.add_parser("oracle-opportunity-queue", help="Rank opportunity, caution, and research-review items from the fused strategic stack")
    ooq.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    ooq.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ooq.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path to enrich queue urgency")
    ooq.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    ooq.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ooq.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ooq.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    ooq.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ooq.add_argument("--output", default="", help="Write ORACLE_OPPORTUNITY_QUEUE_REPORT.json path")
    ooq.add_argument("--markdown-output", default="", help="Write ORACLE_OPPORTUNITY_QUEUE_REPORT.md path")
    ooq.set_defaults(_run=runners["cmd_oracle_opportunity_queue"])

    ospo = sub.add_parser("oracle-strategy-health-posterior", help="Update strategy-level posterior confidence using the fused strategic posture")
    ospo.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    ospo.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ospo.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ospo.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ospo.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    ospo.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ospo.add_argument("--output", default="", help="Write ORACLE_STRATEGY_HEALTH_POSTERIOR_REPORT.json path")
    ospo.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGY_HEALTH_POSTERIOR_REPORT.md path")
    ospo.set_defaults(_run=runners["cmd_oracle_strategy_health_posterior"])

    orts = sub.add_parser("oracle-regime-transition-signal", help="Compare two strategic fusion reports and classify regime transition drift or break risk")
    orts.add_argument("previous_fusion_report", help="Earlier ORACLE_STRATEGIC_FUSION_REPORT.json path")
    orts.add_argument("current_fusion_report", help="Later ORACLE_STRATEGIC_FUSION_REPORT.json path")
    orts.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    orts.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    orts.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    orts.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    orts.add_argument("--output", default="", help="Write ORACLE_REGIME_TRANSITION_SIGNAL_REPORT.json path")
    orts.add_argument("--markdown-output", default="", help="Write ORACLE_REGIME_TRANSITION_SIGNAL_REPORT.md path")
    orts.set_defaults(_run=runners["cmd_oracle_regime_transition_signal"])

    otm = sub.add_parser("oracle-thesis-memory", help="Track how core strategic theses are strengthening, weakening, or reversing over time")
    otm.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    otm.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    otm.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path")
    otm.add_argument("--previous-thesis-memory-report", default="", help="Optional earlier ORACLE_THESIS_MEMORY_REPORT.json path")
    otm.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    otm.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    otm.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    otm.add_argument("--repo-root", default="", help="Optional repo root for artifact evidence discovery")
    otm.add_argument("--search-root", default="", help="Optional search root for artifact evidence discovery")
    otm.add_argument("--output", default="", help="Write ORACLE_THESIS_MEMORY_REPORT.json path")
    otm.add_argument("--markdown-output", default="", help="Write ORACLE_THESIS_MEMORY_REPORT.md path")
    otm.set_defaults(_run=runners["cmd_oracle_thesis_memory"])

    osb = sub.add_parser("oracle-strategic-briefing", help="Emit a forward-looking strategic briefing from fused signals, posterior updates, queues, thesis memory, and scenario analysis")
    ose = sub.add_parser("oracle-strategic-stack-evidence", help="Seal a strategic input and strategic briefing into canonical signed evidence")
    ose.add_argument("input")
    ose.add_argument("briefing_report")
    ose.add_argument("--repo-root")
    ose.add_argument("--markdown-path")
    ose.add_argument("--artifact", action="append", default=[])
    ose.add_argument("--signing-private-key")
    ose.add_argument("--output")
    ose.add_argument("--dsse-output")
    ose.set_defaults(_run=runners["cmd_oracle_strategic_stack_evidence"])

    vose = sub.add_parser("verify-oracle-strategic-stack-evidence", help="Verify oracle strategic stack evidence digests and optional DSSE signature")
    vose.add_argument("manifest")
    vose.add_argument("--repo-root")
    vose.add_argument("--dsse")
    vose.add_argument("--public-key")
    vose.add_argument("--output")
    vose.set_defaults(_run=runners["cmd_verify_oracle_strategic_stack_evidence"])

    osae = sub.add_parser("oracle-strategic-artifact-evidence", help="Seal a strategist artifact into canonical signed evidence")
    osae.add_argument("report")
    osae.add_argument("--repo-root")
    osae.add_argument("--markdown-path")
    osae.add_argument("--artifact", action="append", default=[])
    osae.add_argument("--signing-private-key")
    osae.add_argument("--output")
    osae.add_argument("--dsse-output")
    osae.set_defaults(_run=runners["cmd_oracle_strategic_artifact_evidence"])

    vosae = sub.add_parser("verify-oracle-strategic-artifact-evidence", help="Verify oracle strategic artifact evidence digests and optional DSSE signature")
    vosae.add_argument("manifest")
    vosae.add_argument("--repo-root")
    vosae.add_argument("--dsse")
    vosae.add_argument("--public-key")
    vosae.add_argument("--output")
    vosae.set_defaults(_run=runners["cmd_verify_oracle_strategic_artifact_evidence"])

    osb.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    osb.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path for what-changed analysis")
    osb.add_argument("--previous-thesis-memory-report", default="", help="Optional earlier ORACLE_THESIS_MEMORY_REPORT.json path")
    osb.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    osb.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    osb.add_argument("--strategic-tension-report", default="", help="Optional ORACLE_STRATEGIC_TENSION_REPORT.json path")
    osb.add_argument("--strategic-narrative-report", default="", help="Optional ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    osb.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    osb.add_argument("--contradiction-resolution-report", default="", help="Optional ORACLE_CONTRADICTION_RESOLUTION_REPORT.json path")
    osb.add_argument("--strategic-intervention-report", default="", help="Optional ORACLE_STRATEGIC_INTERVENTION_REPORT.json path")
    osb.add_argument("--strategic-campaign-report", default="", help="Optional ORACLE_STRATEGIC_CAMPAIGN_REPORT.json path")
    osb.add_argument("--strategic-campaign-execution-report", default="", help="Optional ORACLE_STRATEGIC_CAMPAIGN_EXECUTION_REPORT.json path")
    osb.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_BRIEFING_REPORT.json path")
    osb.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_BRIEFING_REPORT.md path")
    osb.set_defaults(_run=runners["cmd_oracle_strategic_briefing"])

    osl = sub.add_parser("oracle-scenario-lab", help="Stress the current advisory stack with downside, upside, and doctrine-pressure counterfactual scenarios")
    osl.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    osl.add_argument("--fusion-report", default="", help="Optional baseline ORACLE_STRATEGIC_FUSION_REPORT.json path")
    osl.add_argument("--scenario-plan", default="", help="Optional ORACLE_SCENARIO_PLAN_INPUT.json path")
    osl.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    osl.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    osl.add_argument("--repo-root", default="", help="Optional repo root used to discover exact artifact evidence")
    osl.add_argument("--search-root", default="", help="Optional search root used to discover exact artifact evidence")
    osl.add_argument("--output", default="", help="Write ORACLE_SCENARIO_LAB_REPORT.json path")
    osl.add_argument("--markdown-output", default="", help="Write ORACLE_SCENARIO_LAB_REPORT.md path")
    osl.set_defaults(_run=runners["cmd_oracle_scenario_lab"])

    osc = sub.add_parser("oracle-strategy-cohort", help="Rank strategies by resilience across posterior confidence, queue pressure, thesis drift, and scenario downside floors")
    osc.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    osc.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    osc.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path")
    osc.add_argument("--previous-thesis-memory-report", default="", help="Optional earlier ORACLE_THESIS_MEMORY_REPORT.json path")
    osc.add_argument("--scenario-plan", default="", help="Optional ORACLE_SCENARIO_PLAN_INPUT.json path")
    osc.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    osc.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    osc.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    osc.add_argument("--repo-root", default="", help="Optional repo root used to discover exact artifact evidence")
    osc.add_argument("--search-root", default="", help="Optional search root used to discover exact artifact evidence")
    osc.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    osc.add_argument("--output", default="", help="Write ORACLE_STRATEGY_COHORT_REPORT.json path")
    osc.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGY_COHORT_REPORT.md path")
    osc.set_defaults(_run=runners["cmd_oracle_strategy_cohort"])

    oda = sub.add_parser("oracle-doctrine-adaptation", help="Advise which doctrine clauses should be monitored, reviewed, adapted, or frozen under current strategic pressure")
    oda.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    oda.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    oda.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path")
    oda.add_argument("--previous-thesis-memory-report", default="", help="Optional earlier ORACLE_THESIS_MEMORY_REPORT.json path")
    oda.add_argument("--scenario-plan", default="", help="Optional ORACLE_SCENARIO_PLAN_INPUT.json path")
    oda.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    oda.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    oda.add_argument("--output", default="", help="Write ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    oda.add_argument("--markdown-output", default="", help="Write ORACLE_DOCTRINE_ADAPTATION_REPORT.md path")
    oda.set_defaults(_run=runners["cmd_oracle_doctrine_adaptation"])

    orp = sub.add_parser("oracle-research-planner", help="Rank the next strategic investigations from queue pressure, thesis drift, doctrine adaptation, cohort stress, and scenario downside")
    orp.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    orp.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    orp.add_argument("--previous-fusion-report", default="", help="Optional earlier ORACLE_STRATEGIC_FUSION_REPORT.json path")
    orp.add_argument("--previous-thesis-memory-report", default="", help="Optional earlier ORACLE_THESIS_MEMORY_REPORT.json path")
    orp.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    orp.add_argument("--scenario-plan", default="", help="Optional ORACLE_SCENARIO_PLAN_INPUT.json path")
    orp.add_argument("--output", default="", help="Write ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    orp.add_argument("--markdown-output", default="", help="Write ORACLE_RESEARCH_PRIORITY_REPORT.md path")
    orp.set_defaults(_run=runners["cmd_oracle_research_planner"])

    orem = sub.add_parser("oracle-research-execution-memory", help="Record which ranked investigations were actually executed and how they changed theses, cohorts, and doctrine pressure")
    orem.add_argument("research_priority_report", help="Path to ORACLE_RESEARCH_PRIORITY_REPORT.json")
    orem.add_argument("--outcome-input", required=True, help="Path to ORACLE_INVESTIGATION_OUTCOME_INPUT.json")
    orem.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    orem.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    orem.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    orem.add_argument("--output", default="", help="Write ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    orem.add_argument("--markdown-output", default="", help="Write ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.md path")
    orem.set_defaults(_run=runners["cmd_oracle_research_execution_memory"])

    otg = sub.add_parser("oracle-thesis-graph", help="Map how theses, doctrine clauses, strategy cohorts, priorities, and investigation outcomes depend on each other")
    otg.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    otg.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    otg.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    otg.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    otg.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    otg.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    otg.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    otg.add_argument("--repo-root", default="", help="Optional repo root for artifact evidence discovery")
    otg.add_argument("--search-root", default="", help="Optional search root for artifact evidence discovery")
    otg.add_argument("--output", default="", help="Write ORACLE_THESIS_GRAPH_REPORT.json path")
    otg.add_argument("--markdown-output", default="", help="Write ORACLE_THESIS_GRAPH_REPORT.md path")
    otg.set_defaults(_run=runners["cmd_oracle_thesis_graph"])

    ost = sub.add_parser("oracle-strategic-tension", help="Detect contradictions and dangerous consensus tension across posture, doctrine, scenarios, cohorts, thesis drift, and investigation feedback")
    ost.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    ost.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ost.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    ost.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    ost.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ost.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ost.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    ost.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    ost.add_argument("--repo-root", default="", help="Optional repo root for exact strategic artifact evidence discovery")
    ost.add_argument("--search-root", default="", help="Optional search root for exact strategic artifact evidence discovery")
    ost.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_TENSION_REPORT.json path")
    ost.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_TENSION_REPORT.md path")
    ost.set_defaults(_run=runners["cmd_oracle_strategic_tension"])

    osn = sub.add_parser("oracle-strategic-narrative", help="Explain what is driving conviction, fragility, and trust bias across the strategic stack")
    osn.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    osn.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    osn.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    osn.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    osn.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    osn.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    osn.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    osn.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    osn.add_argument("--strategic-tension-report", default="", help="Optional ORACLE_STRATEGIC_TENSION_REPORT.json path")
    osn.add_argument("--repo-root", default="", help="Optional repo root for exact strategic artifact evidence discovery")
    osn.add_argument("--search-root", default="", help="Optional search root for exact strategic artifact evidence discovery")
    osn.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    osn.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_NARRATIVE_REPORT.md path")
    osn.set_defaults(_run=runners["cmd_oracle_strategic_narrative"])

    osm = sub.add_parser("oracle-strategic-memory-horizon", help="Track conviction drift and changing driver dominance across recent strategic narrative observations")
    osm.add_argument("current_report", help="Latest ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    osm.add_argument("--history-report", action="append", default=[], help="Optional earlier ORACLE_STRATEGIC_NARRATIVE_REPORT.json path; repeat to extend the memory horizon")
    osm.add_argument("--verified-history-bundle", action="append", default=[], help="Repeatable narrative_path:manifest_path:verification_path triple for sealed prior strategic runs")
    osm.add_argument("--require-sealed-history", action="store_true", help="Exclude plain --history-report inputs and build belief drift only from verified strategic stack bundles")
    osm.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    osm.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.md path")
    osm.set_defaults(_run=runners["cmd_oracle_strategic_memory_horizon"])

    ocr = sub.add_parser("oracle-contradiction-resolution", help="Rank which contradiction chain should be resolved first for the biggest gain in conviction quality")
    ocr.add_argument("input", help="ORACLE_ADVISORY_INPUT.json path")
    ocr.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ocr.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    ocr.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    ocr.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ocr.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ocr.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    ocr.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    ocr.add_argument("--strategic-tension-report", default="", help="Optional ORACLE_STRATEGIC_TENSION_REPORT.json path")
    ocr.add_argument("--strategic-narrative-report", default="", help="Optional ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    ocr.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    ocr.add_argument("--repo-root", default="", help="Optional repository root used for exact evidence discovery")
    ocr.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ocr.add_argument("--output", default="", help="Write ORACLE_CONTRADICTION_RESOLUTION_REPORT.json path")
    ocr.add_argument("--markdown-output", default="", help="Write ORACLE_CONTRADICTION_RESOLUTION_REPORT.md path")
    ocr.set_defaults(_run=runners["cmd_oracle_contradiction_resolution"])

    ois = sub.add_parser("oracle-strategic-intervention", help="Simulate which contradiction-resolving intervention would improve conviction, fragility, doctrine pressure, queue pressure, and cohort resilience the most")
    ois.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    ois.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ois.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    ois.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    ois.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ois.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ois.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    ois.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    ois.add_argument("--strategic-tension-report", default="", help="Optional ORACLE_STRATEGIC_TENSION_REPORT.json path")
    ois.add_argument("--strategic-narrative-report", default="", help="Optional ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    ois.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    ois.add_argument("--contradiction-resolution-report", default="", help="Optional ORACLE_CONTRADICTION_RESOLUTION_REPORT.json path")
    ois.add_argument("--repo-root", default="", help="Optional repository root used for artifact-evidence discovery")
    ois.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ois.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_INTERVENTION_REPORT.json path")
    ois.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_INTERVENTION_REPORT.md path")
    ois.set_defaults(_run=runners["cmd_oracle_strategic_intervention"])

    ocp = sub.add_parser("oracle-strategic-campaign", help="Group interventions, investigations, doctrine actions, and hedges into multi-step strategic campaigns")
    ocp.add_argument("input", help="Path to ORACLE_ADVISORY_INPUT.json")
    ocp.add_argument("--fusion-report", default="", help="Optional ORACLE_STRATEGIC_FUSION_REPORT.json path")
    ocp.add_argument("--thesis-memory-report", default="", help="Optional ORACLE_THESIS_MEMORY_REPORT.json path")
    ocp.add_argument("--strategy-cohort-report", default="", help="Optional ORACLE_STRATEGY_COHORT_REPORT.json path")
    ocp.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ocp.add_argument("--research-priority-report", default="", help="Optional ORACLE_RESEARCH_PRIORITY_REPORT.json path")
    ocp.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    ocp.add_argument("--thesis-graph-report", default="", help="Optional ORACLE_THESIS_GRAPH_REPORT.json path")
    ocp.add_argument("--strategic-tension-report", default="", help="Optional ORACLE_STRATEGIC_TENSION_REPORT.json path")
    ocp.add_argument("--strategic-narrative-report", default="", help="Optional ORACLE_STRATEGIC_NARRATIVE_REPORT.json path")
    ocp.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    ocp.add_argument("--contradiction-resolution-report", default="", help="Optional ORACLE_CONTRADICTION_RESOLUTION_REPORT.json path")
    ocp.add_argument("--strategic-intervention-report", default="", help="Optional ORACLE_STRATEGIC_INTERVENTION_REPORT.json path")
    ocp.add_argument("--repo-root", default="", help="Optional repository root used for artifact-evidence discovery")
    ocp.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ocp.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_CAMPAIGN_REPORT.json path")
    ocp.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_CAMPAIGN_REPORT.md path")
    ocp.set_defaults(_run=runners["cmd_oracle_strategic_campaign"])

    ocx = sub.add_parser("oracle-strategic-campaign-state", help="Track campaign execution state across queued, active, blocked, drifting, completed, and invalidated campaigns")
    ocx.add_argument("campaign_report", help="ORACLE_STRATEGIC_CAMPAIGN_REPORT.json path")
    ocx.add_argument("--execution-input", default="", help="Optional ORACLE_STRATEGIC_CAMPAIGN_EXECUTION_INPUT.json path")
    ocx.add_argument("--research-execution-memory-report", default="", help="Optional ORACLE_RESEARCH_EXECUTION_MEMORY_REPORT.json path")
    ocx.add_argument("--doctrine-adaptation-report", default="", help="Optional ORACLE_DOCTRINE_ADAPTATION_REPORT.json path")
    ocx.add_argument("--strategic-memory-horizon-report", default="", help="Optional ORACLE_STRATEGIC_MEMORY_HORIZON_REPORT.json path")
    ocx.add_argument("--repo-root", default="", help="Optional repository root used for artifact-evidence discovery")
    ocx.add_argument("--search-root", default="", help="Optional artifact search root used for exact evidence discovery")
    ocx.add_argument("--output", default="", help="Write ORACLE_STRATEGIC_CAMPAIGN_EXECUTION_REPORT.json path")
    ocx.add_argument("--markdown-output", default="", help="Write ORACLE_STRATEGIC_CAMPAIGN_EXECUTION_REPORT.md path")
    ocx.set_defaults(_run=runners["cmd_oracle_strategic_campaign_execution"])

    oe = sub.add_parser("oracle-evidence", help="Build a signed oracle evidence manifest from a frozen advisory input")
    oe.add_argument("input", help="Oracle advisory input JSON path")
    oe.add_argument("--attestation-output", default="", help="Write ORACLE_MORNING_ATTESTATION.json path")
    oe.add_argument("--markdown-output", default="", help="Write ORACLE_MORNING_ATTESTATION.md path")
    oe.add_argument("--closure-snapshot", default="", help="Optional linked CLOSURE_SNAPSHOT.json path")
    oe.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
    oe.add_argument("--signing-private-key", default="", help="Optional Ed25519 private key PEM for DSSE signing")
    oe.add_argument("--output", default="", help="Write ORACLE_EVIDENCE.json path")
    oe.add_argument("--dsse-output", default="", help="Write ORACLE_EVIDENCE.dsse.json path")
    oe.set_defaults(_run=runners["cmd_oracle_evidence"])

    vo = sub.add_parser("verify-oracle-evidence", help="Verify oracle evidence digests and optional DSSE signature")
    vo.add_argument("manifest", help="Oracle evidence manifest JSON path")
    vo.add_argument("--repo-root", default="", help="Optional repository root used for artifact path resolution")
    vo.add_argument("--dsse", default="", help="Optional DSSE envelope JSON path")
    vo.add_argument("--public-key", default="", help="Optional Ed25519 public key PEM")
    vo.add_argument("--output", default="", help="Write oracle evidence verification JSON path")
    vo.set_defaults(_run=runners["cmd_verify_oracle_evidence"])
