from __future__ import annotations

import argparse
from pathlib import Path

def _common_pack_filters(parser: argparse.ArgumentParser, *, include_current_pack_kind: bool = False, include_preferred: bool = False) -> None:
    parser.add_argument('--search-root', required=True, help='Artifact search root containing ORACLE_OPERATOR_PACK_INDEX.json files')
    parser.add_argument('--repo-root', default='', help='Optional repository root used for path resolution')
    if include_current_pack_kind:
        parser.add_argument('--current-pack-kind', default='', help='Optional current pack kind context')
    if include_preferred:
        parser.add_argument('--preferred-pack-kind', action='append', default=[], help='Preferred pack kind ordering; may be passed multiple times')
    parser.add_argument('--pack-kind', action='append', default=[], help='Optional pack kind filter; may be passed multiple times')
    parser.add_argument('--trust-status', action='append', default=[], help='Optional trust status filter; may be passed multiple times')
    parser.add_argument('--summary-line-contains', default='', help='Optional substring filter over indexed summary lines')
    parser.add_argument('--output-artifact-label-contains', default='', help='Optional substring filter over indexed output artifact labels')


def _configure_oracle_operator_pack_query(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser)
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_QUERY_REPORT.json path')


def _configure_oracle_operator_pack_workbench(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser)
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_WORKBENCH.json path')


def _configure_oracle_operator_pack_navigation(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True, include_preferred=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum number of selected navigation items')
    parser.add_argument('--exclude-current-pack-kind', action='store_true', help='Exclude the current pack kind from selected navigation items')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_NAVIGATION.json path')


def _configure_oracle_operator_pack_dashboard(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True, include_preferred=True)
    parser.add_argument('--max-navigation-items', type=int, default=3, help='Maximum selected navigation items to include')
    parser.add_argument('--max-column-items', type=int, default=3, help='Maximum pack-kind overview columns to include')
    parser.add_argument('--include-current-pack-kind', action=argparse.BooleanOptionalAction, default=True, help='Whether to include the current pack kind in selected navigation')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_DASHBOARD.json path')


def _configure_oracle_operator_pack_timeline(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=8, help='Maximum timeline activity items to include')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_TIMELINE.json path')


def _configure_oracle_operator_pack_comparison(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum comparison items to include')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_COMPARISON.json path')


def _configure_oracle_operator_pack_drift(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum drift alert items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_DRIFT.json path')


def _configure_oracle_operator_pack_escalation(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum escalation items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_ESCALATION.json path')


def _configure_oracle_operator_pack_assignment(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum assignment items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix such as team or shift identifier')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_ASSIGNMENT.json path')



def _configure_oracle_operator_pack_claim_lease(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum claim/lease items to include')
    parser.add_argument('--queue-key')
    parser.add_argument('--review-target')
    parser.add_argument('--priority-band')
    parser.add_argument('--action-owner-lane')
    parser.add_argument('--backup-owner-lane')
    parser.add_argument('--ack-owner-lane')
    parser.add_argument('--board-label')
    parser.add_argument('--owner-label-prefix')
    parser.add_argument('--lease-label-prefix')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2)
    parser.add_argument('--output', type=Path)


def _configure_oracle_operator_pack_lease_governance(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum lease governance items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease owner label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional claim lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_LEASE_GOVERNANCE.json path')


def _configure_oracle_operator_pack_execution_readiness(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum execution-readiness items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional execution readiness label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_EXECUTION_READINESS.json path')




def _configure_oracle_operator_pack_dispatch_outcome(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum dispatch-outcome items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional execution readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch permission label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_DISPATCH_OUTCOME.json path')




def _configure_oracle_operator_pack_approval_needed(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum approval-needed items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Consecutive degraded appearances required for sustained degraded classification')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator board label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional execution exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval memo label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_APPROVAL_NEEDED.json path')


def _configure_oracle_operator_pack_approval_disposition(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum approval-disposition items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Consecutive degraded appearances required for sustained degraded classification')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator board label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional execution exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval memo label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional sign-off/disposition label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_APPROVAL_DISPOSITION.json path')


def _configure_oracle_operator_pack_execution_authorization(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum execution-authorization items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Consecutive degraded appearances required for sustained degraded classification')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator board label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional execution exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval memo label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional sign-off/disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional execution authorization label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_EXECUTION_AUTHORIZATION.json path')

def _configure_oracle_operator_pack_execution_exception(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum execution-exception items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Consecutive degraded appearances required for sustained degraded classification')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator board label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional execution exception label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_EXECUTION_EXCEPTION.json path')

def _configure_oracle_operator_pack_execution_force(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum execution-force items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional execution readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch permission label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional dispatch outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional execution exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval-needed label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional approval disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional execution authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional forced execution label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_EXECUTION_FORCE.json path')


def _configure_oracle_operator_pack_dispatch_permission(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum dispatch-permission items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional execution readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch permission label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_DISPATCH_PERMISSION.json path')


def _configure_oracle_operator_pack_claim_operability(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum claim-operability items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional execution readiness label prefix')
    parser.add_argument('--operability-label-prefix', default='', help='Optional claim operability label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_CLAIM_OPERABILITY.json path')


def _configure_oracle_operator_pack_claim_lifecycle(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum claim lifecycle items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix for rendered ownership labels')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix for rendered lease labels')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix for rendered lifecycle labels')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_CLAIM_LIFECYCLE.json path')


def _configure_oracle_operator_pack_handoff(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=4, help='Maximum handoff items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged')
    parser.add_argument('--queue-key', default='', help='Optional operator queue key context')
    parser.add_argument('--review-target', default='', help='Optional operator review target context')
    parser.add_argument('--priority-band', default='', help='Optional operator priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional operator owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane override')
    parser.add_argument('--board-label', default='', help='Optional operator workboard label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix such as team or shift identifier')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_HANDOFF.json path')




def _configure_oracle_operator_pack_terminal_resolution(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum terminal-resolution items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak for upstream drift surfaces')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional owner lane context')
    parser.add_argument('--board-label', default='', help='Optional board label context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane override')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane override')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional force label prefix')
    parser.add_argument('--finality-label-prefix', default='', help='Optional finality label prefix')
    parser.add_argument('--resolution-label-prefix', default='', help='Optional terminal-resolution label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_TERMINAL_RESOLUTION.json path')





def _configure_oracle_operator_pack_terminal_archive(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum terminal-archive items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak for upstream drift surfaces')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional owner lane context')
    parser.add_argument('--board-label', default='', help='Optional board label context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane override')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane override')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional force label prefix')
    parser.add_argument('--finality-label-prefix', default='', help='Optional finality label prefix')
    parser.add_argument('--resolution-label-prefix', default='', help='Optional terminal-resolution label prefix')
    parser.add_argument('--closure-label-prefix', default='', help='Optional terminal-closure label prefix')
    parser.add_argument('--archive-label-prefix', default='', help='Optional terminal-archive label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_TERMINAL_ARCHIVE.json path')


def _configure_oracle_operator_pack_terminal_record(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum terminal-record items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak for upstream drift surfaces')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional owner lane context')
    parser.add_argument('--board-label', default='', help='Optional board label context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane override')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane override')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional force label prefix')
    parser.add_argument('--finality-label-prefix', default='', help='Optional finality label prefix')
    parser.add_argument('--resolution-label-prefix', default='', help='Optional terminal-resolution label prefix')
    parser.add_argument('--closure-label-prefix', default='', help='Optional terminal-closure label prefix')
    parser.add_argument('--archive-label-prefix', default='', help='Optional terminal-archive label prefix')
    parser.add_argument('--record-label-prefix', default='', help='Optional terminal-record label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_TERMINAL_RECORD.json path')


def _configure_oracle_operator_pack_terminal_record_publish(parser: argparse.ArgumentParser) -> None:
    _configure_oracle_operator_pack_terminal_record(parser)
    parser.add_argument('--publication-root', required=True, help='Directory where durable terminal-record bundle is written')
    parser.add_argument('--index-path', default='', help='Optional explicit ORACLE_OPERATOR_TERMINAL_RECORD_INDEX.json path')
    parser.add_argument('--manifest-output', default='', help='Optional path to also write the publication manifest payload')

def _configure_oracle_operator_pack_terminal_closure(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum terminal-closure items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak for upstream drift surfaces')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional owner lane context')
    parser.add_argument('--board-label', default='', help='Optional board label context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane override')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane override')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional force label prefix')
    parser.add_argument('--finality-label-prefix', default='', help='Optional finality label prefix')
    parser.add_argument('--resolution-label-prefix', default='', help='Optional terminal-resolution label prefix')
    parser.add_argument('--closure-label-prefix', default='', help='Optional terminal-closure label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_TERMINAL_CLOSURE.json path')

def _configure_oracle_operator_pack_execution_finality(parser: argparse.ArgumentParser) -> None:
    _common_pack_filters(parser, include_current_pack_kind=True)
    parser.add_argument('--max-items', type=int, default=3, help='Maximum final terminal-decision items to include')
    parser.add_argument('--sustained-degraded-threshold', type=int, default=2, help='Minimum degraded streak count before sustained degradation is flagged upstream')
    parser.add_argument('--queue-key', default='', help='Optional queue key context')
    parser.add_argument('--review-target', default='', help='Optional review target context')
    parser.add_argument('--priority-band', default='', help='Optional priority band context')
    parser.add_argument('--action-owner-lane', default='', help='Optional owner lane context')
    parser.add_argument('--backup-owner-lane', default='', help='Optional backup owner lane context')
    parser.add_argument('--ack-owner-lane', default='', help='Optional acknowledgement owner lane context')
    parser.add_argument('--board-label', default='', help='Optional board label context')
    parser.add_argument('--owner-label-prefix', default='', help='Optional owner label prefix')
    parser.add_argument('--lease-label-prefix', default='', help='Optional lease label prefix')
    parser.add_argument('--lifecycle-label-prefix', default='', help='Optional lifecycle label prefix')
    parser.add_argument('--governance-label-prefix', default='', help='Optional governance label prefix')
    parser.add_argument('--readiness-label-prefix', default='', help='Optional readiness label prefix')
    parser.add_argument('--dispatch-label-prefix', default='', help='Optional dispatch label prefix')
    parser.add_argument('--outcome-label-prefix', default='', help='Optional outcome label prefix')
    parser.add_argument('--exception-label-prefix', default='', help='Optional exception label prefix')
    parser.add_argument('--approval-label-prefix', default='', help='Optional approval label prefix')
    parser.add_argument('--disposition-label-prefix', default='', help='Optional disposition label prefix')
    parser.add_argument('--authorization-label-prefix', default='', help='Optional authorization label prefix')
    parser.add_argument('--force-label-prefix', default='', help='Optional force label prefix')
    parser.add_argument('--finality-label-prefix', default='', help='Optional finality label prefix')
    parser.add_argument('--output', default='', help='Write ORACLE_OPERATOR_PACK_EXECUTION_FINALITY.json path')

