"""Runtime file templates for the single-tenant deployment bundle."""
from __future__ import annotations

def _bundle_gitignore() -> str:
    return """# Generated single-tenant handoff bundle local guardrails.
# Keep real secrets and deployment evidence out of source control.
deployment.env
.env
*.env
evidence/
*.sqlite3
*.sqlite3-*
*.db
*.db-*
backups/
pre-restore/
"""


def _compose_template() -> str:
    return """# Backend-only single-tenant deployment template.
# Generated by strategy-validator-single-tenant-bundle.
# Do not commit real deployment.env files.
services:
  strategy-validator-api:
    image: ${STRATEGY_VALIDATOR_IMAGE:-strategy-validator-api:local}
    container_name: strategy-validator-api
    restart: unless-stopped
    env_file:
      - ${STRATEGY_VALIDATOR_COMPOSE_ENV_FILE:-./deployment.env}
    ports:
      - "127.0.0.1:${STRATEGY_VALIDATOR_HOST_PORT:-8000}:8000"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=64m
    volumes:
      - strategy-validator-ledger:/var/lib/strategy-validator
      - strategy-validator-backups:/var/backups/strategy-validator
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=3).read()"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  strategy-validator-ledger:
    name: strategy-validator-ledger
  strategy-validator-backups:
    name: strategy-validator-backups
"""


def _systemd_template() -> str:
    return r"""# Backend-only single-tenant Docker service template.
# Copy to /etc/systemd/system/strategy-validator.service and adjust paths/image.
[Unit]
Description=Strategy Validator single-tenant backend API
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
Environment=STRATEGY_VALIDATOR_IMAGE=strategy-validator-api:local
Environment=STRATEGY_VALIDATOR_HOST_PORT=8000
EnvironmentFile=/etc/strategy-validator/deployment.env
ExecStartPre=/usr/bin/docker run --rm --user 0:0 \
  --read-only \
  --tmpfs /tmp:rw,nosuid,nodev,noexec,size=64m \
  --cap-drop ALL \
  --security-opt no-new-privileges:true \
  -v /etc/strategy-validator:/deployment-env:ro \
  ${STRATEGY_VALIDATOR_IMAGE} \
  strategy-validator-deployment-env-check /deployment-env/deployment.env --require-valid --json
ExecStartPre=-/usr/bin/docker rm -f strategy-validator-api
ExecStart=/usr/bin/docker run --rm --name strategy-validator-api \
  --env-file /etc/strategy-validator/deployment.env \
  -p 127.0.0.1:${STRATEGY_VALIDATOR_HOST_PORT}:8000 \
  --read-only \
  --tmpfs /tmp:rw,nosuid,nodev,noexec,size=64m \
  --cap-drop ALL \
  --security-opt no-new-privileges:true \
  -v strategy-validator-ledger:/var/lib/strategy-validator \
  -v strategy-validator-backups:/var/backups/strategy-validator \
  ${STRATEGY_VALIDATOR_IMAGE}
ExecStop=-/usr/bin/docker stop strategy-validator-api
Restart=on-failure
RestartSec=5s
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
"""

__all__ = (
    "_bundle_gitignore",
    "_compose_template",
    "_systemd_template",
)
