"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffClearanceReleaseCustodyBoard } from "@/hooks/useUiSemanticValidatorHandoffClearanceReleaseCustodyBoard";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
function text(value: unknown): string { return value === null || value === undefined || value === "" ? "—" : String(value); }
function countRows(counts?: Record<string, number>) { return Object.entries(counts ?? {}).map(([k, v]) => ({ k, v: String(v) })); }
export default function Page() { const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffClearanceReleaseCustodyBoard({limit:200}); const summary=q.data?.summary ?? {}; if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE RELEASE CUSTODY BOARD</h1><p className="muted">{config.error.message}</p></div>; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE RELEASE CUSTODY BOARD</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/clearance-release-custody-board · read-only custody transfer observations derived from release handoffs</p>{q.isLoading && <p className="muted">Loading…</p>}{q.isError && <p className="term-error">{q.error.message}</p>}{q.data && <><PaneGrid cols={3}><Pane title="Release custody" badge={<StatusBadge raw={q.data.degraded.length ? "DEGRADED" : "OK"} />}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"rows",v:text(summary.release_custody_count_returned)},{k:"fail_closed",v:text(summary.fail_closed_count)}]} /></Pane><Pane title="Authority firewall"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"write",v:q.data.release_custody_write_authority},{k:"approval",v:q.data.operator_approval_authority},{k:"execution",v:q.data.execution_authority}]} /></Pane><Pane title="Latest"><TermKV rows={[{k:"id",v:text(q.data.latest?.release_custody_id)},{k:"lane",v:text(q.data.latest?.evidence_lane)},{k:"status",v:text(q.data.latest?.release_custody_status)},{k:"readiness",v:text(q.data.latest?.release_custody_readiness)}]} /></Pane></PaneGrid><Pane title="Release custody rows"><table className="term-table"><thead><tr><th>#</th><th>lane</th><th>status</th><th>readiness</th><th>source</th><th>gate</th><th>instruction</th></tr></thead><tbody>{q.data.release_custodies.map((r,i)=><tr key={`${r.release_custody_id}:${i}`}><td><code>{r.ordinal}</code></td><td><code>{r.evidence_lane}</code></td><td><StatusBadge raw={r.release_custody_status} /></td><td><StatusBadge raw={r.release_custody_readiness} /></td><td><StatusBadge raw={r.source_release_handoff_status} /></td><td><code>{r.release_custody_gate}</code></td><td>{r.release_custody_instruction}</td></tr>)}</tbody></table></Pane><PaneGrid cols={3}><Pane title="Statuses"><TermKV rows={countRows(q.data.release_custody_status_counts)} /></Pane><Pane title="Readiness"><TermKV rows={countRows(q.data.release_custody_readiness_counts)} /></Pane><Pane title="Evidence lanes"><TermKV rows={countRows(q.data.evidence_lane_counts)} /></Pane></PaneGrid><Pane title="Guardrails"><ul className="term-list">{q.data.guardrails.map((line)=><li key={line}>{line}</li>)}</ul></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/clearance-release-custody-board JSON" data={q.data} /></>}</div>; }
