"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffClearanceGate } from "@/hooks/useUiSemanticValidatorHandoffClearanceGate";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffClearanceGate({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE GATE</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE GATE</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/clearance-gate · read-only clearance visibility derived from resolution plan</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Clearance inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"gates",v:String(s.clearance_gate_count_returned??0)},{k:"blocked",v:String(s.blocked_gate_count??0)},{k:"candidate_review",v:String(s.candidate_for_operator_clearance_review_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"approval",v:q.data.operator_approval_authority},{k:"signoff",v:q.data.signoff_authority},{k:"ack",v:q.data.resolution_step_acknowledgment_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"gate",v:String(q.data.latest?.clearance_gate_id??"—")},{k:"status",v:String(q.data.latest?.clearance_status??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")},{k:"blocked",v:String(q.data.latest?.handoff_clearance_blocked??"—")}]}/></Pane></PaneGrid><Pane title="Clearance gates"><table className="term-table"><thead><tr><th>#</th><th>status</th><th>priority</th><th>severity</th><th>experiment</th><th>condition</th></tr></thead><tbody>{q.data.clearance_gates.map((r,i)=><tr key={`${r.clearance_gate_id}:${i}`}><td><code>{r.ordinal}</code></td><td><StatusBadge raw={r.clearance_status}/></td><td><StatusBadge raw={r.priority}/></td><td><StatusBadge raw={r.severity}/></td><td><code>{r.experiment_id??"—"}</code></td><td><code>{r.clearance_condition}</code></td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/clearance-gate JSON" data={q.data}/></>}</div>; }
