from __future__ import annotations

"""Queue, governance, and workboard state surfaces."""

EXPORTS_QUEUE_GOVERNANCE = {
    'OracleGovernanceWorkQueueRequest': 'strategy_validator.control_plane.operator_queue_service',
    'OracleGovernanceWorkQueueState': 'strategy_validator.control_plane.operator_queue_service',
    'build_governance_work_queue_request': 'strategy_validator.control_plane.operator_queue_service',
    'materialize_governance_work_queue_state': 'strategy_validator.control_plane.operator_queue_service',
    'OracleOperatorWorkboard': 'strategy_validator.control_plane.operator_workboard',
    'OracleOperatorWorkboardEntry': 'strategy_validator.control_plane.operator_workboard',
    'OracleOperatorWorkboardRequest': 'strategy_validator.control_plane.operator_workboard',
    'build_operator_workboard_request': 'strategy_validator.control_plane.operator_workboard',
    'materialize_operator_workboard': 'strategy_validator.control_plane.operator_workboard',
    'OracleOperatorWorkboardActionContract': 'strategy_validator.control_plane.operator_workboard_actions',
    'OracleOperatorWorkboardActionContractItem': 'strategy_validator.control_plane.operator_workboard_actions',
    'OracleOperatorWorkboardActionContractRequest': 'strategy_validator.control_plane.operator_workboard_actions',
    'build_operator_workboard_action_contract_request': 'strategy_validator.control_plane.operator_workboard_actions',
    'materialize_operator_workboard_action_contract': 'strategy_validator.control_plane.operator_workboard_actions',
    'OracleOperatorTransitionPolicy': 'strategy_validator.control_plane.operator_transition_policy',
    'OracleOperatorTransitionPolicyItem': 'strategy_validator.control_plane.operator_transition_policy',
    'OracleOperatorTransitionPolicyRequest': 'strategy_validator.control_plane.operator_transition_policy',
    'build_operator_transition_policy_request': 'strategy_validator.control_plane.operator_transition_policy',
    'materialize_operator_transition_policy': 'strategy_validator.control_plane.operator_transition_policy',
    'OracleOperatorQueueSnapshotRequest': 'strategy_validator.control_plane.operator_queue_snapshot',
    'OracleOperatorQueueSnapshot': 'strategy_validator.control_plane.operator_queue_snapshot',
    'OracleOperatorWorkItem': 'strategy_validator.control_plane.operator_queue_snapshot',
    'OracleOperatorQueueQueryRequest': 'strategy_validator.control_plane.operator_queue_query',
    'OracleOperatorQueueQueryResult': 'strategy_validator.control_plane.operator_queue_query',
    'OracleOperatorQueueQueryWorkItem': 'strategy_validator.control_plane.operator_queue_query',
    'build_operator_queue_query_request': 'strategy_validator.control_plane.operator_queue_query',
    'run_operator_queue_query': 'strategy_validator.control_plane.operator_queue_query',
    'build_operator_queue_snapshot_request': 'strategy_validator.control_plane.operator_queue_snapshot',
    'materialize_operator_queue_snapshot': 'strategy_validator.control_plane.operator_queue_snapshot',
    'OracleGovernanceClaimEnvelope': 'strategy_validator.control_plane.governance_envelopes',
    'OracleGovernanceDispatchEnvelope': 'strategy_validator.control_plane.governance_envelopes',
    'OracleGovernanceReviewEnvelope': 'strategy_validator.control_plane.governance_envelopes',
    'OracleGovernanceRoutingEnvelope': 'strategy_validator.control_plane.governance_envelopes',
    'build_governance_review_sort_key': 'strategy_validator.control_plane.governance_review_dispatch',
    'materialize_governance_claim_envelope': 'strategy_validator.control_plane.governance_claim_workflows',
    'materialize_governance_dispatch_envelope': 'strategy_validator.control_plane.governance_review_dispatch',
    'materialize_governance_review_envelope': 'strategy_validator.control_plane.governance_review_dispatch',
    'materialize_governance_routing_envelope': 'strategy_validator.control_plane.governance_review_dispatch',
}
