from __future__ import annotations

"""Decision execution, operator journals, and integrity-tracking surfaces."""

EXPORTS_DECISION_INTEGRITY = {
    'OracleOperatorDecisionExecution': 'strategy_validator.control_plane.operator_decision_execution',
    'OracleOperatorDecisionExecutionItem': 'strategy_validator.control_plane.operator_decision_execution',
    'OracleOperatorDecisionExecutionRequest': 'strategy_validator.control_plane.operator_decision_execution',
    'build_operator_decision_execution_request': 'strategy_validator.control_plane.operator_decision_execution',
    'materialize_operator_decision_execution': 'strategy_validator.control_plane.operator_decision_execution',
    'OracleOperatorDecisionJournal': 'strategy_validator.control_plane.operator_decision_journal',
    'OracleOperatorDecisionJournalEvent': 'strategy_validator.control_plane.operator_decision_journal',
    'OracleOperatorDecisionJournalRequest': 'strategy_validator.control_plane.operator_decision_journal',
    'build_operator_decision_journal_request': 'strategy_validator.control_plane.operator_decision_journal',
    'materialize_operator_decision_journal': 'strategy_validator.control_plane.operator_decision_journal',
    'OracleOperatorActionOutcomeLedger': 'strategy_validator.control_plane.operator_action_outcome_ledger',
    'OracleOperatorActionOutcomeLedgerEntry': 'strategy_validator.control_plane.operator_action_outcome_ledger',
    'OracleOperatorActionOutcomeLedgerRequest': 'strategy_validator.control_plane.operator_action_outcome_ledger',
    'build_operator_action_outcome_ledger_request': 'strategy_validator.control_plane.operator_action_outcome_ledger',
    'materialize_operator_action_outcome_ledger': 'strategy_validator.control_plane.operator_action_outcome_ledger',
    'OracleOperatorFeedbackState': 'strategy_validator.control_plane.operator_feedback_state',
    'OracleOperatorFeedbackStateItem': 'strategy_validator.control_plane.operator_feedback_state',
    'OracleOperatorFeedbackStateRequest': 'strategy_validator.control_plane.operator_feedback_state',
    'build_operator_feedback_state_request': 'strategy_validator.control_plane.operator_feedback_state',
    'materialize_operator_feedback_state': 'strategy_validator.control_plane.operator_feedback_state',
    'OracleOperatorSupervisorReview': 'strategy_validator.control_plane.operator_supervisor_review',
    'OracleOperatorSupervisorReviewItem': 'strategy_validator.control_plane.operator_supervisor_review',
    'OracleOperatorSupervisorReviewRequest': 'strategy_validator.control_plane.operator_supervisor_review',
    'build_operator_supervisor_review_request': 'strategy_validator.control_plane.operator_supervisor_review',
    'materialize_operator_supervisor_review': 'strategy_validator.control_plane.operator_supervisor_review',
    'OracleOperatorEscalationClosure': 'strategy_validator.control_plane.operator_escalation_closure',
    'OracleOperatorEscalationClosureItem': 'strategy_validator.control_plane.operator_escalation_closure',
    'OracleOperatorEscalationClosureRequest': 'strategy_validator.control_plane.operator_escalation_closure',
    'build_operator_escalation_closure_request': 'strategy_validator.control_plane.operator_escalation_closure',
    'materialize_operator_escalation_closure': 'strategy_validator.control_plane.operator_escalation_closure',
    'OracleOperatorControlPlaneBundle': 'strategy_validator.control_plane.operator_control_plane_bundle',
    'OracleOperatorControlPlaneBundleRequest': 'strategy_validator.control_plane.operator_control_plane_bundle',
    'build_operator_control_plane_bundle_request': 'strategy_validator.control_plane.operator_control_plane_bundle',
    'materialize_operator_control_plane_bundle': 'strategy_validator.control_plane.operator_control_plane_bundle',
    'render_operator_control_plane_bundle_markdown_lines': 'strategy_validator.control_plane.operator_control_plane_bundle',
}
