"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffClearanceDossier } from "@/hooks/useUiSemanticValidatorHandoffClearanceDossier";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffClearanceDossier({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE DOSSIER</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE DOSSIER</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/clearance-dossier · read-only operator review dossier derived from clearance gates</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Dossier inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"dossiers",v:String(s.clearance_dossier_count_returned??0)},{k:"blocked",v:String(s.blocked_dossier_count??0)},{k:"failed_checks",v:String(s.failed_or_attention_check_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"materialize",v:q.data.dossier_materialization_authority},{k:"approval",v:q.data.operator_approval_authority},{k:"signoff",v:q.data.signoff_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"dossier",v:String(q.data.latest?.clearance_dossier_id??"—")},{k:"posture",v:String(q.data.latest?.review_posture??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")},{k:"candidate",v:String(q.data.latest?.candidate_for_operator_clearance_review??"—")}]}/></Pane></PaneGrid><Pane title="Clearance dossiers"><table className="term-table"><thead><tr><th>#</th><th>posture</th><th>status</th><th>priority</th><th>checks</th><th>brief</th></tr></thead><tbody>{q.data.clearance_dossiers.map((r,i)=><tr key={`${r.clearance_dossier_id}:${i}`}><td><code>{r.ordinal}</code></td><td><StatusBadge raw={r.review_posture}/></td><td><StatusBadge raw={r.clearance_status}/></td><td><StatusBadge raw={r.priority}/></td><td><code>{r.failed_or_attention_check_count}/{r.review_check_count}</code></td><td>{r.operator_brief}</td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/clearance-dossier JSON" data={q.data}/></>}</div>; }
