#!/usr/bin/env python3
"""Emit frontend-readable UI facade contract artifacts from the authoritative backend snapshot.

Run from repository root after ``docs/api/ui-public-facade.snapshot.json`` is current
(typically via ``python scripts/ui_facade_contract_snapshot.py``).

Outputs:
  - ui/strategist-web/lib/generated/ui-facade-contract.json
  - ui/strategist-web/lib/generated/ui-facade-contract.ts
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_SNAPSHOT = _REPO_ROOT / "docs" / "api" / "ui-public-facade.snapshot.json"

FRONTEND_CONTRACT_SCHEMA = "ui_strategist_web_facade_contract/v1"

_TS_HEADER = """/**
 * AUTO-GENERATED by scripts/generate_frontend_ui_facade_contract.py — do not edit manually.
 * Regenerate from repo root: python scripts/generate_frontend_ui_facade_contract.py
 */
"""


def build_contract_payload(snapshot: dict[str, object]) -> dict[str, object]:
    routes = snapshot["routes"]
    if not isinstance(routes, list):
        raise ValueError("snapshot.routes must be a list")
    return {
        "schema_version": FRONTEND_CONTRACT_SCHEMA,
        "source_snapshot_schema_version": snapshot["schema_version"],
        "source_schema_version": snapshot["source_schema_version"],
        "read_plane_only": snapshot["read_plane_only"],
        "mutation_route": snapshot["mutation_route"],
        "route_count": snapshot["route_count"],
        "routes_sha256": snapshot["routes_sha256"],
        "routes": routes,
    }


def _emit_ts() -> str:
    return (
        _TS_HEADER
        + "import type { UiFacadeRoute } from \"../api/types\";\n"
        + "import contractJson from \"./ui-facade-contract.json\";\n\n"
        + "export interface UiStrategistWebFacadeContract {\n"
        + "  schema_version: string;\n"
        + "  source_snapshot_schema_version: string;\n"
        + "  source_schema_version: string;\n"
        + "  read_plane_only: boolean;\n"
        + "  mutation_route: string;\n"
        + "  route_count: number;\n"
        + "  routes_sha256: string;\n"
        + "  routes: UiFacadeRoute[];\n"
        + "}\n\n"
        + "export const uiFacadeContract = contractJson as UiStrategistWebFacadeContract;\n\n"
        + "export function listUiFacadeRoutes(): readonly UiFacadeRoute[] {\n"
        + "  return uiFacadeContract.routes;\n"
        + "}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate ui/strategist-web/lib/generated/ui-facade-contract.*")
    parser.add_argument("--snapshot", type=Path, default=_DEFAULT_SNAPSHOT, help="Path to ui-public-facade.snapshot.json")
    parser.add_argument("--repo-root", type=Path, default=_REPO_ROOT, help="Repository root")
    args = parser.parse_args(argv)

    repo = args.repo_root.resolve()
    snap_path = args.snapshot if args.snapshot.is_absolute() else repo / args.snapshot
    if not snap_path.is_file():
        print(f"missing snapshot: {snap_path}", file=sys.stderr)
        return 1

    snapshot = json.loads(snap_path.read_text(encoding="utf-8"))
    payload = build_contract_payload(snapshot)

    out_json = repo / "ui" / "strategist-web" / "lib" / "generated" / "ui-facade-contract.json"
    out_ts = repo / "ui" / "strategist-web" / "lib" / "generated" / "ui-facade-contract.ts"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    out_ts.write_text(_emit_ts(), encoding="utf-8")
    print(str(out_json))
    print(str(out_ts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
