#!/usr/bin/env python3
"""Merge provider secrets into deployment.env from env files and process env (no stdout secrets)."""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

DEPLOYMENT_ENV = _REPO_ROOT / "deployment.env"

# Canonical names expected by strategy_validator brokers/providers.
_ALPACA_FROM_APCA = (
    ("ALPACA_API_KEY", ("ALPACA_API_KEY", "APCA_API_KEY_ID")),
    ("ALPACA_API_SECRET", ("ALPACA_API_SECRET", "APCA_API_SECRET_KEY", "ALPACA_API_SECRET_KEY")),
)

_PROVIDER_KEYS = (
    "ALPACA_API_KEY",
    "ALPACA_API_SECRET",
    "ALPACA_BASE_URL",
    "ALPACA_DATA_BASE_URL",
    "ALPACA_DATA_FEED",
    "ALPACA_TRADING_MODE",
    "POLYGON_API_KEY",
    "FRED_API_KEY",
    "BLS_API_KEY",
    "ALPHA_VANTAGE_API_KEY",
    "FINNHUB_API_KEY",
)

_DEFAULTS = {
    "ALPACA_BASE_URL": "https://paper-api.alpaca.markets",
    "ALPACA_DATA_BASE_URL": "https://data.alpaca.markets",
    "ALPACA_DATA_FEED": "iex",
    "ALPACA_TRADING_MODE": "paper",
}

_PLACEHOLDER = re.compile(
    r"^(CHANGEME|REPLACE_ME|YOUR_KEY_HERE|.*NOT_A_REAL.*)$",
    re.IGNORECASE,
)


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        if re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            values[key] = value
    return values


def _usable(value: str) -> bool:
    v = value.strip()
    return bool(v) and not _PLACEHOLDER.match(v)


def _collect_sources(extra_paths: list[Path]) -> dict[str, str]:
    merged: dict[str, str] = {}
    for path in extra_paths:
        for key, value in _parse_env_file(path).items():
            if key.startswith("NEXT_PUBLIC"):
                continue
            if _usable(value):
                merged[key] = value.strip()
    proc = dict(os.environ)
    for canonical, aliases in _ALPACA_FROM_APCA:
        for name in aliases:
            raw = proc.get(name, "").strip()
            if _usable(raw):
                merged[canonical] = raw
                break
    for key in _PROVIDER_KEYS:
        raw = proc.get(key, "").strip()
        if _usable(raw):
            merged[key] = raw
    return merged


def _read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def _merge_into_deployment(*, dest: Path, incoming: dict[str, str], dry_run: bool) -> list[str]:
    lines = _read_lines(dest) if dest.is_file() else []
    existing_keys = set()
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            existing_keys.add(key)
            if key in incoming:
                out.append(f"{key}={incoming.pop(key)}")
                continue
        out.append(line)

    if not existing_keys and not lines:
        out = ["# Generated by scripts/merge_secrets_into_deployment_env.py", ""]

    added: list[str] = []
    to_append = {**{k: v for k, v in _DEFAULTS.items() if k not in existing_keys}, **incoming}
    if to_append:
        if out and out[-1].strip():
            out.append("")
        out.append("# --- Provider secrets (merged; gitignored via deployment.env) ---")
        for key in _PROVIDER_KEYS:
            if key not in to_append:
                continue
            out.append(f"{key}={to_append[key]}")
            added.append(key)

    if not dry_run:
        dest.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    return added


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deployment-env", type=Path, default=DEPLOYMENT_ENV)
    parser.add_argument(
        "--from",
        dest="from_paths",
        action="append",
        default=[],
        type=Path,
        help="Extra env files to merge (e.g. ui/strategist-web/.env.local)",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    default_sources = [
        _REPO_ROOT / ".env.local",
        _REPO_ROOT / ".env",
        Path(r"c:\Users\jpkem\OneDrive\Desktop\strategist\ui\strategist-web\.env.local"),
        Path(r"c:\Users\jpkem\OneDrive\Desktop\New folder (11)\ui\strategist-web\.env.local"),
        Path(r"c:\Users\jpkem\OneDrive\Desktop\New folder (12)\ui\strategist-web\.env.local"),
        Path(r"c:\Users\jpkem\OneDrive\Desktop\sports_betting\.env"),
        Path(r"c:\Users\jpkem\OneDrive\Desktop\Strategist\deployment.env"),
    ]
    paths = [p for p in (*default_sources, *args.from_paths) if p.is_file()]
    incoming = _collect_sources(paths)
    if not incoming:
        print("No provider secrets found in process env or source files.", file=sys.stderr)
        return 1

    added = _merge_into_deployment(dest=args.deployment_env, incoming=incoming, dry_run=args.dry_run)
    action = "would add/update" if args.dry_run else "added/updated"
    print(f"{action} keys in {args.deployment_env.name}: {', '.join(added)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
