#!/usr/bin/env python3
"""Create deployment.env, durable directories, migrate the ledger, and seed Next.js API config.

Production-style (default): STRATEGY_VALIDATOR_MODE=PRODUCTION with paths under
``/var/lib/strategy-validator`` and ``/var/backups/strategy-validator`` (on Windows these
resolve under the current drive, e.g. ``C:\\var\\lib\\...``). Runs
``strategy-validator-deployment-env-check --require-valid`` and
``strategy-validator-migrate``.

Dev shortcut (``--dev``): MODE=DEV with repo-local ``.local/`` paths; skips the strict
deployment checker (paths are not under the generated container roots).

Never prints generated tokens. Use ``--force`` to replace an existing deployment.env.
"""
from __future__ import annotations

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEPLOYMENT_ENV = REPO_ROOT / "deployment.env"
WEB_ENV_EXAMPLE = REPO_ROOT / "ui" / "strategist-web" / ".env.example"
WEB_ENV_LOCAL = REPO_ROOT / "ui" / "strategist-web" / ".env.local"


def _token() -> str:
    return secrets.token_urlsafe(48)


def _ensure_tree(*paths: Path) -> None:
    for p in paths:
        p.mkdir(parents=True, exist_ok=True)


def _write_deployment_env(*, dev: bool, dest: Path) -> None:
    mutation = _token()
    research = _token()
    if dev:
        local = (REPO_ROOT / ".local").resolve()
        ledger = local / "ledger.sqlite3"
        backup = local / "backups"
        artifacts = local / "artifacts"
        lines = [
            "# Generated by scripts/setup_local_deployment.py --dev",
            "# DEV: not validated by strategy-validator-deployment-env-check (container path policy).",
            "",
            "STRATEGY_VALIDATOR_MODE=DEV",
            f"STRATEGY_VALIDATOR_API_TOKEN={mutation}",
            "STRATEGY_VALIDATOR_API_TOKEN_SCOPES=operator:command:write,operator:projection:read",
            f"STRATEGY_VALIDATOR_RESEARCH_API_TOKEN={research}",
            "",
            f"STRATEGY_VALIDATOR_LEDGER_DB_PATH={ledger}",
            f"STRATEGY_VALIDATOR_LEDGER_BACKUP_DIR={backup}",
            f"STRATEGY_VALIDATOR_ARTIFACT_ROOT={artifacts}",
            "",
            "STRATEGY_VALIDATOR_HOST_PORT=8000",
            "STRATEGY_VALIDATOR_UI_CORS_ORIGINS=http://127.0.0.1:3000,http://localhost:3000",
            "STRATEGY_VALIDATOR_API_MUTATION_RATE_LIMIT_PER_MINUTE=60",
            "",
        ]
        _ensure_tree(local, backup, artifacts)
    else:
        ledger_s = "/var/lib/strategy-validator/ledger.sqlite3"
        backup_s = "/var/backups/strategy-validator"
        artifacts_s = "/var/lib/strategy-validator/artifacts"
        ledger = Path(ledger_s).resolve()
        backup = Path(backup_s).resolve()
        artifacts = Path(artifacts_s).resolve()
        _ensure_tree(ledger.parent, backup, artifacts)
        lines = [
            "# Generated by scripts/setup_local_deployment.py",
            "",
            "STRATEGY_VALIDATOR_MODE=PRODUCTION",
            f"STRATEGY_VALIDATOR_API_TOKEN={mutation}",
            "STRATEGY_VALIDATOR_API_TOKEN_SCOPES=operator:command:write,operator:projection:read",
            f"STRATEGY_VALIDATOR_RESEARCH_API_TOKEN={research}",
            "",
            f"STRATEGY_VALIDATOR_LEDGER_DB_PATH={ledger_s}",
            f"STRATEGY_VALIDATOR_LEDGER_BACKUP_DIR={backup_s}",
            f"STRATEGY_VALIDATOR_ARTIFACT_ROOT={artifacts_s}",
            "",
            "STRATEGY_VALIDATOR_HOST_PORT=8000",
            "STRATEGY_VALIDATOR_UI_CORS_ORIGINS=http://127.0.0.1:3000,http://localhost:3000",
            "STRATEGY_VALIDATOR_API_MUTATION_RATE_LIMIT_PER_MINUTE=60",
            "",
        ]

    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            out[key] = value
    return out


def _run_with_env(argv: list[str], env: dict[str, str]) -> int:
    merged = {**os.environ, **env}
    root = str(REPO_ROOT)
    merged["PYTHONPATH"] = root if "PYTHONPATH" not in merged else f"{root}{os.pathsep}{merged['PYTHONPATH']}"
    proc = subprocess.run(argv, cwd=REPO_ROOT, env=merged, check=False)
    return int(proc.returncode)


def _seed_next_env() -> None:
    if WEB_ENV_LOCAL.exists():
        return
    if WEB_ENV_EXAMPLE.is_file():
        WEB_ENV_LOCAL.write_text(WEB_ENV_EXAMPLE.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        WEB_ENV_LOCAL.write_text(
            "NEXT_PUBLIC_STRATEGIST_API_BASE_URL=http://127.0.0.1:8000\n",
            encoding="utf-8",
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dev", action="store_true", help="DEV mode + repo .local/ paths; skip deployment-env-check")
    parser.add_argument("--force", action="store_true", help="Overwrite existing deployment.env")
    parser.add_argument("--skip-migrate", action="store_true", help="Do not run strategy-validator-migrate")
    args = parser.parse_args(argv)

    if DEPLOYMENT_ENV.exists() and not args.force:
        print(f"Refusing to overwrite {DEPLOYMENT_ENV}; pass --force", file=sys.stderr)
        return 1

    _write_deployment_env(dev=args.dev, dest=DEPLOYMENT_ENV)
    env_map = _load_env_file(DEPLOYMENT_ENV)
    _seed_next_env()

    print(f"Wrote {DEPLOYMENT_ENV.relative_to(REPO_ROOT)}")
    print(f"Seeded {WEB_ENV_LOCAL.relative_to(REPO_ROOT)} (if it was missing)")

    if not args.dev:
        check = _run_with_env(
            [sys.executable, "-m", "strategy_validator.cli.deployment_env_check", str(DEPLOYMENT_ENV), "--require-valid"],
            env_map,
        )
        if check != 0:
            print("deployment env check failed", file=sys.stderr)
            return check
        print("deployment env check: OK")

    if not args.skip_migrate:
        mig = _run_with_env([sys.executable, "-m", "strategy_validator.cli.migrate", "--json"], env_map)
        if mig != 0:
            print("ledger migrate failed", file=sys.stderr)
            return mig
        print("ledger migrate: OK")

    print("\nNext steps:")
    print("  PowerShell (API):")
    print(f"    cd \"{REPO_ROOT}\"")
    print("    Get-Content .\\deployment.env | ForEach-Object { if ($_ -match '^([^#][^=]+)=(.*)$') { Set-Item -Path env:$($matches[1]) -Value $matches[2] } }")
    print("    strategy-validator-api --host 127.0.0.1 --port 8000")
    print("  Then UI: cd ui\\strategist-web && npm install && npm run dev")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
