"use client";
import { JsonDetails } from "@/components/operator/JsonDetails";
import { StatusBadge } from "@/components/operator/StatusBadge";
import { Pane } from "@/components/terminal/Pane";
import { PaneGrid } from "@/components/terminal/PaneGrid";
import { TermKV } from "@/components/terminal/TermKV";
import { useUiSemanticValidatorHandoffActionQueue } from "@/hooks/useUiSemanticValidatorHandoffActionQueue";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/config/public-config";
export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffActionQueue({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF ACTION QUEUE</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF ACTION QUEUE</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/action-queue · read-only flattened audit-packet actions</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Queue inventory" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"actions",v:String(s.action_count_returned??0)},{k:"blocked",v:String(s.blocked_count??0)},{k:"external",v:String(s.external_artifact_required_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"action_execute",v:q.data.action_execution_authority},{k:"artifact_write",v:q.data.external_artifact_write_authority},{k:"submit",v:q.data.validator_submission_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"action",v:String(q.data.latest?.action_id??"—")},{k:"state",v:String(q.data.latest?.queue_state??"—")},{k:"experiment",v:String(q.data.latest?.experiment_id??"—")},{k:"priority",v:String(q.data.latest?.priority??"—")}]}/></Pane></PaneGrid><Pane title="Action rows"><table className="term-table"><thead><tr><th>state</th><th>priority</th><th>trust</th><th>experiment</th><th>action</th><th>route</th></tr></thead><tbody>{q.data.action_rows.map((r,i)=><tr key={`${r.action_id}:${i}`}><td><StatusBadge raw={r.queue_state}/></td><td><StatusBadge raw={r.priority}/></td><td><StatusBadge raw={r.trust_banner}/></td><td><code>{r.experiment_id??"—"}</code></td><td><code>{r.operator_action}</code></td><td><code>{r.route}</code></td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/action-queue JSON" data={q.data}/></>}</div>; }
