"use client";
import { JsonDetails } from "@/components/JsonDetails";
import { Pane, PaneGrid } from "@/components/Pane";
import { StatusBadge } from "@/components/StatusBadge";
import { TermKV } from "@/components/TermKV";
import { useUiSemanticValidatorHandoffClearanceEvidenceMatrix } from "@/hooks/useUiSemanticValidatorHandoffClearanceEvidenceMatrix";
import { tryGetPublicStrategistApiBaseUrl } from "@/lib/env";

export default function Page(){ const config=tryGetPublicStrategistApiBaseUrl(); const q=useUiSemanticValidatorHandoffClearanceEvidenceMatrix({limit:200}); if(!config.ok) return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE EVIDENCE MATRIX</h1><p className="muted">{config.error.message}</p></div>; const s=q.data?.summary??{}; return <div className="term-page"><h1 className="term-page__title">SEMANTIC · VALIDATOR HANDOFF CLEARANCE EVIDENCE MATRIX</h1><p className="muted" style={{fontSize:"10px"}}>GET /ui/semantic-validator-handoff/clearance-evidence-matrix · read-only evidence coverage matrix derived from clearance checklist rows</p>{q.isLoading&&<p className="muted">Loading…</p>}{q.isError&&<p className="term-error">{q.error.message}</p>}{q.data&&<><PaneGrid cols={3}><Pane title="Evidence coverage" badge={<StatusBadge raw={q.data.degraded?.length?"DEGRADED":"OK"}/>}><TermKV rows={[{k:"schema",v:q.data.schema_version},{k:"rows",v:String(s.evidence_matrix_row_count_returned??0)},{k:"cells",v:String(s.matrix_cell_count??0)},{k:"attention",v:String(s.attention_required_count??0)}]}/></Pane><Pane title="Authority"><TermKV rows={[{k:"read_plane",v:String(q.data.read_plane_only)},{k:"attest",v:q.data.evidence_attestation_authority},{k:"override",v:q.data.evidence_override_authority},{k:"approval",v:q.data.operator_approval_authority},{k:"execute",v:q.data.execution_authority}]}/></Pane><Pane title="Latest"><TermKV rows={[{k:"row",v:String(q.data.latest?.evidence_matrix_row_id??"—")},{k:"lane",v:String(q.data.latest?.evidence_lane??"—")},{k:"state",v:String(q.data.latest?.evidence_state??"—")},{k:"check",v:String(q.data.latest?.check_id??"—")}]}/></Pane></PaneGrid><Pane title="Matrix cells"><table className="term-table"><thead><tr><th>lane</th><th>state</th><th>coverage</th><th>rows</th><th>blocked</th><th>external</th></tr></thead><tbody>{q.data.matrix_cells.map((r,i)=><tr key={`${r.cell_id}:${i}`}><td><code>{r.evidence_lane}</code></td><td><StatusBadge raw={r.evidence_state}/></td><td><StatusBadge raw={r.coverage_state}/></td><td><code>{r.row_count}</code></td><td><code>{r.blocks_clearance_count}</code></td><td><code>{r.requires_external_artifact_count}</code></td></tr>)}</tbody></table></Pane><Pane title="Evidence rows"><table className="term-table"><thead><tr><th>#</th><th>lane</th><th>state</th><th>check</th><th>priority</th><th>instruction</th></tr></thead><tbody>{q.data.evidence_rows.map((r,i)=><tr key={`${r.evidence_matrix_row_id}:${i}`}><td><code>{r.ordinal}</code></td><td><code>{r.evidence_lane}</code></td><td><StatusBadge raw={r.evidence_state}/></td><td><code>{r.check_id??"—"}</code></td><td><StatusBadge raw={r.priority}/></td><td>{r.operator_instruction}</td></tr>)}</tbody></table></Pane><JsonDetails summary="Drilldown: /ui/semantic-validator-handoff/clearance-evidence-matrix JSON" data={q.data}/></>}</div>; }
