"""Application-layer service façades.

This package is the transport-neutral use-case surface for CLI and API code.
The root package resolves public helpers lazily so importing
``strategy_validator.application`` does not eagerly pull the full service graph.
"""

from __future__ import annotations

from importlib import import_module

_EXPORT_MAP = {
    'generate_host_fingerprint_payload': 'strategy_validator.application.rollout_operations',
    'generate_snapshot_signing_keypair_payload': 'strategy_validator.application.rollout_operations',
    'build_rollout_bundle_payload': 'strategy_validator.application.rollout_operations',
    'parse_analyze_summary_payload': 'strategy_validator.application.rollout_operations',
    'default_startup_json_bundle_payload': 'strategy_validator.application.rollout_operations',
    'load_controlled_rollout_rules_payload': 'strategy_validator.application.rollout_operations',
    'build_daily_checklist_payload': 'strategy_validator.application.rollout_operations',
    'review_runtime_evidence_payload': 'strategy_validator.application.rollout_operations',
    'build_closure_snapshot_payload': 'strategy_validator.application.rollout_operations',
    'verify_closure_snapshot_payload': 'strategy_validator.application.rollout_operations',
    'build_governed_exception_memo_payload': 'strategy_validator.application.rollout_operations',
    'verify_governed_exception_memo_payload': 'strategy_validator.application.rollout_operations',
    'render_governed_exception_markdown_payload': 'strategy_validator.application.rollout_operations',
    'build_closure_release_attestation_payload': 'strategy_validator.application.rollout_operations',
    'render_final_release_signoff_markdown_payload': 'strategy_validator.application.rollout_operations',
    'render_decision_reconciliation_markdown_payload': 'strategy_validator.application.rollout_operations',
    'build_oracle_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'load_oracle_input_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'verify_oracle_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'load_sensor_ingestion_input_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'load_fusion_report_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'build_strategic_stack_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'verify_strategic_stack_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'build_strategic_artifact_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'verify_strategic_artifact_evidence_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'load_strategic_narrative_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_memory_horizon_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_verified_strategic_stack_history_bundle_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'load_contradiction_resolution_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_intervention_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_tension_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_research_priority_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_thesis_graph_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_campaign_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_campaign_execution_input_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategic_campaign_execution_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_thesis_memory_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_scenario_plan_input_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_strategy_cohort_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_doctrine_adaptation_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_investigation_outcome_input_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'load_research_execution_memory_report_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'trust_infer_repo_root_from_artifact_path_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_maybe_verify_oracle_lineage_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_oracle_trust_banner_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_banner_for_constitutional_gate_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_banner_for_derived_view_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_banner_for_event_checkpoint_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_banner_for_legacy_surface_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'trust_banner_for_lineage_verification_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_checkpoint_from_paths_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_constitutional_gate_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_derived_view_trust_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_event_checkpoint_trust_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_lineage_verification_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'explain_report_from_path_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_oracle_explanation_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'emit_event_view_projection_registry_payload': 'strategy_validator.application.oracle_event_surfaces',
    'emit_event_checkpoint_projection_registry_payload': 'strategy_validator.application.oracle_event_surfaces',
    'inspect_compacted_state_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'rebuild_compacted_state_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_compacted_state_inspection_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_compacted_state_rebuild_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_strategic_tension_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_strategic_tension_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_thesis_graph_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_thesis_graph_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_research_priority_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_research_priority_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_strategic_intervention_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_strategic_intervention_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_contradiction_resolution_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_contradiction_resolution_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_regime_transition_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_regime_transition_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'render_strategy_health_posterior_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_strategy_health_posterior_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'append_event_log_entry_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'append_temporal_canonicalization_to_event_log_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'render_incident_pack_html_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_incident_pack_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'materialize_incident_pack_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'build_incident_pack_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_status_pack_html_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_status_pack_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'materialize_status_pack_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'build_status_pack_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_operator_diagnostic_markdown_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'build_operator_diagnostic_from_report_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'build_operator_diagnostic_from_checkpoint_payload': 'strategy_validator.application.oracle_advisory_surfaces',
    'render_strategic_fusion_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'build_strategic_fusion_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_sensor_ingestion_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'normalize_sensor_ingestion_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_morning_attestation_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'build_morning_attestation_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'build_briefing_pack_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'build_replay_audit_payload': 'strategy_validator.application.oracle_operational_surfaces',
'render_strategic_narrative_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_strategic_narrative_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_strategy_cohort_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_strategy_cohort_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_opportunity_queue_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_opportunity_queue_payload': 'strategy_validator.application.oracle_strategy_surfaces',
    'build_strategic_memory_horizon_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_strategic_campaign_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_strategic_campaign_execution_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_thesis_memory_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_scenario_lab_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_doctrine_adaptation_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_research_execution_memory_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'build_strategic_briefing_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'emit_briefing_pack_projection_registry_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'materialize_briefing_pack_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_briefing_pack_html_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_briefing_pack_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_replay_audit_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'render_strategic_memory_horizon_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_strategic_campaign_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_strategic_campaign_execution_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_thesis_memory_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_scenario_lab_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_doctrine_adaptation_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_research_execution_memory_markdown_payload': 'strategy_validator.application.oracle_strategy_surfaces',
'render_strategic_briefing_markdown_payload': 'strategy_validator.application.oracle_operational_surfaces',
    'append_annual_review_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_constitutional_digest_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_doctrine_drift_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_memory_review_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_monthly_digest_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_quarterly_review_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_semiannual_audit_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'append_state_transition_to_lane_payload': 'strategy_validator.application.oracle_reporting',
    'build_annual_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_annual_review_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_constitutional_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_constitutional_digest_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_constitutional_gate_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_derived_view_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_doctrine_drift_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_doctrine_drift_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_doctrine_lineage_index_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_event_checkpoint_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_horizon_view_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_memory_lane_summary_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_memory_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_memory_review_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_monthly_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_monthly_digest_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_quarterly_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_quarterly_review_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_rolling_review_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_semiannual_audit_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_semiannual_audit_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_state_transition_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_state_transition_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_weekly_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'build_weekly_digest_payload': 'strategy_validator.application.oracle_event_surfaces',
    'compare_weekly_digest_payloads': 'strategy_validator.application.oracle_event_surfaces',
    'legacy_compatibility_banner_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_annual_review_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_constitutional_digest_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_constitutional_gate_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_derived_view_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_doctrine_drift_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_doctrine_lineage_index_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_doctrine_lineage_verification_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_event_checkpoint_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_memory_lane_summary_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_memory_review_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_monthly_digest_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_quarterly_review_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_rolling_review_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_semiannual_audit_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_state_transition_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'render_weekly_digest_markdown_payload': 'strategy_validator.application.oracle_event_surfaces',
    'resolve_horizon_window_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_annual_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_constitutional_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_doctrine_drift_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_doctrine_lineage_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_event_checkpoint_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_memory_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_monthly_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_quarterly_review_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_semiannual_audit_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_state_transition_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'verify_weekly_digest_evidence_bundle_payload': 'strategy_validator.application.oracle_event_surfaces',
    'run_oracle_adjudication': 'strategy_validator.application.adjudication',
    'summarize_burnin_artifact': 'strategy_validator.application.burnin',
    'summarize_burnin_set': 'strategy_validator.application.burnin',
    'compute_payload_digest': 'strategy_validator.application.evidence_verification',
    'verify_event_envelope': 'strategy_validator.application.evidence_verification',
    'verify_projection_snapshot': 'strategy_validator.application.evidence_verification',
    'build_governance_queue_state': 'strategy_validator.application.governance_surface',
    'build_workboard_action_contract_payload': 'strategy_validator.application.governance_surface',
    'build_pack_assignment_payload': 'strategy_validator.application.operator_pack_assembly',
    'build_pack_claim_lifecycle_payload': 'strategy_validator.application.operator_pack_assembly',
    'build_pack_claim_lease_payload': 'strategy_validator.application.operator_pack_assembly',
    'build_pack_claim_operability_payload': 'strategy_validator.application.operator_pack_assembly',
    'build_pack_escalation_payload': 'strategy_validator.application.operator_pack_assembly',
    'build_queue_snapshot': 'strategy_validator.application.operator_queue_commands',
    'build_queue_query_payload': 'strategy_validator.application.operator_queue_commands',
    'build_workboard_payload': 'strategy_validator.application.operator_queue_commands',
    'build_transition_policy_payload': 'strategy_validator.application.operator_queue_commands',
    'build_operator_pack_navigation_payload': 'strategy_validator.application.operator_pack_queries',
    'build_operator_pack_query_payload': 'strategy_validator.application.operator_pack_queries',
    'build_operator_pack_timeline_payload': 'strategy_validator.application.operator_pack_queries',
    'build_operator_pack_workbench_payload': 'strategy_validator.application.operator_pack_queries',
    'build_ui_workboard_payload': 'strategy_validator.application.ui_views',
    'build_ui_runtime_status_payload': 'strategy_validator.application.ui_views',
    'build_ui_burnin_payload': 'strategy_validator.application.ui_views',
    'build_ui_pack_detail_payload': 'strategy_validator.application.ui_views',
    'build_ui_tribunal_payload': 'strategy_validator.application.ui_views',
    'build_ui_evidence_payload': 'strategy_validator.application.ui_views',
    'build_ui_operator_command_receipt_payload': 'strategy_validator.application.operator_mutations',
    'publish_operator_terminal_record_payload': 'strategy_validator.application.operator_pack_queries',
    'materialize_briefing_operator_pack': 'strategy_validator.application.operator_packs',
    'materialize_incident_operator_pack': 'strategy_validator.application.operator_packs',
    'materialize_status_operator_pack': 'strategy_validator.application.operator_packs',
    'build_governance_queue': 'strategy_validator.application.operator_queue',
    'query_operator_queue': 'strategy_validator.application.operator_queue',
    'backfill_all_registered_projections': 'strategy_validator.application.projection_backfill',
    'backfill_projection_family': 'strategy_validator.application.projection_backfill',
    'build_operator_pack_query_request': 'strategy_validator.application.projection_queries',
    'build_projection_query_request': 'strategy_validator.application.projection_queries',
    'query_operator_packs': 'strategy_validator.application.projection_queries',
    'query_projection_artifacts': 'strategy_validator.application.projection_queries',
    'select_latest_operator_pack': 'strategy_validator.application.projection_queries',
    'select_latest_projection_artifact': 'strategy_validator.application.projection_queries',
    'get_readiness_health_payload': 'strategy_validator.application.readiness',
    'publish_release_bundle_from_paths': 'strategy_validator.application.readiness',
    'rebuild_projection_artifacts': 'strategy_validator.application.rebuild',
    'publish_release_readiness_bundle': 'strategy_validator.application.release_publication',
    'normalize_proposal_for_adjudication': 'strategy_validator.application.research_ingress',
    'extract_temporal_semantic_batch_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'build_temporal_semantic_batch_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'verify_temporal_semantic_batch_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'materialize_temporal_semantic_sensor_payloads': 'strategy_validator.application.oracle_temporal_surfaces',
    'fetch_openbb_temporal_sensor_inputs_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'canonicalize_temporal_semantic_batch_with_openbb_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'canonicalize_temporal_semantic_batch_payload': 'strategy_validator.application.oracle_temporal_surfaces',
    'summarize_temporal_lane_payload': 'strategy_validator.application.oracle_temporal_surfaces',
}

__all__ = sorted(_EXPORT_MAP)


def __getattr__(name: str):
    module_name = _EXPORT_MAP.get(name)
    if module_name is None:
        raise AttributeError(name)
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
