"""Evidence lifecycle payload key registry."""
from __future__ import annotations

from typing import Any, Mapping

_VALUE_KEYS = (
    "evidence_bundles",
    "latest_evidence_bundle",
    "evidence_bundle_verifications",
    "latest_evidence_bundle_verification",
    "evidence_bundle_drifts",
    "latest_evidence_bundle_drift",
    "evidence_bundle_rotations",
    "latest_evidence_bundle_rotation",
    "evidence_bundle_rotation_executions",
    "latest_evidence_bundle_rotation_execution",
    "evidence_bundle_attestations",
    "latest_evidence_bundle_attestation",
    "evidence_bundle_attestation_verifications",
    "latest_evidence_bundle_attestation_verification",
    "evidence_bundle_closures",
    "latest_evidence_bundle_closure",
    "evidence_bundle_closure_verifications",
    "latest_evidence_bundle_closure_verification",
    "evidence_bundle_export_manifests",
    "latest_evidence_bundle_export_manifest",
    "evidence_bundle_export_verifications",
    "latest_evidence_bundle_export_verification",
    "evidence_bundle_retention_receipts",
    "latest_evidence_bundle_retention_receipt",
    "evidence_bundle_retention_verifications",
    "latest_evidence_bundle_retention_verification",
    "evidence_bundle_retention_signoffs",
    "latest_evidence_bundle_retention_signoff",
    "evidence_bundle_retention_signoff_verifications",
    "latest_evidence_bundle_retention_signoff_verification",
    "evidence_bundle_retention_handoffs",
    "latest_evidence_bundle_retention_handoff",
    "evidence_bundle_retention_handoff_verifications",
    "latest_evidence_bundle_retention_handoff_verification",
    "evidence_bundle_retention_handoff_acceptances",
    "latest_evidence_bundle_retention_handoff_acceptance",
    "evidence_bundle_retention_handoff_acceptance_verifications",
    "latest_evidence_bundle_retention_handoff_acceptance_verification",
    "evidence_bundle_retention_custody_registers",
    "latest_evidence_bundle_retention_custody_register",
    "evidence_bundle_retention_custody_register_verifications",
    "latest_evidence_bundle_retention_custody_register_verification",
    "evidence_bundle_retention_custody_seals",
    "latest_evidence_bundle_retention_custody_seal",
    "evidence_bundle_retention_custody_seal_verifications",
    "latest_evidence_bundle_retention_custody_seal_verification",
    "evidence_bundle_retention_custody_audits",
    "latest_evidence_bundle_retention_custody_audit",
    "evidence_bundle_retention_custody_audit_verifications",
    "latest_evidence_bundle_retention_custody_audit_verification",
    "evidence_bundle_retention_custody_continuities",
    "latest_evidence_bundle_retention_custody_continuity",
    "evidence_bundle_retention_custody_continuity_verifications",
    "latest_evidence_bundle_retention_custody_continuity_verification",
    "evidence_bundle_retention_custody_reviews",
    "latest_evidence_bundle_retention_custody_review",
    "evidence_bundle_retention_custody_review_verifications",
    "latest_evidence_bundle_retention_custody_review_verification",
    "evidence_bundle_retention_custody_renewals",
    "latest_evidence_bundle_retention_custody_renewal",
    "evidence_bundle_retention_custody_renewal_verifications",
    "latest_evidence_bundle_retention_custody_renewal_verification",
    "evidence_bundle_retention_custody_schedules",
    "latest_evidence_bundle_retention_custody_schedule",
    "evidence_bundle_retention_custody_schedule_verifications",
    "latest_evidence_bundle_retention_custody_schedule_verification",
    "evidence_bundle_retention_custody_notices",
    "latest_evidence_bundle_retention_custody_notice",
    "evidence_bundle_retention_custody_notice_verifications",
    "latest_evidence_bundle_retention_custody_notice_verification",
    "evidence_bundle_retention_custody_acknowledgments",
    "latest_evidence_bundle_retention_custody_acknowledgment",
    "evidence_bundle_retention_custody_acknowledgment_verifications",
    "latest_evidence_bundle_retention_custody_acknowledgment_verification",
    "evidence_bundle_retention_custody_completions",
    "latest_evidence_bundle_retention_custody_completion",
    "evidence_bundle_retention_custody_completion_verifications",
    "latest_evidence_bundle_retention_custody_completion_verification",
    "evidence_bundle_retention_custody_closeouts",
    "latest_evidence_bundle_retention_custody_closeout",
    "evidence_bundle_retention_custody_closeout_verifications",
    "latest_evidence_bundle_retention_custody_closeout_verification",
    "evidence_bundle_retention_custody_archives",
    "latest_evidence_bundle_retention_custody_archive",
    "evidence_bundle_retention_custody_archive_verifications",
    "latest_evidence_bundle_retention_custody_archive_verification",
    "evidence_bundle_retention_custody_retrievals",
    "latest_evidence_bundle_retention_custody_retrieval",
    "evidence_bundle_retention_custody_retrieval_verifications",
    "latest_evidence_bundle_retention_custody_retrieval_verification",
    "evidence_bundle_retention_custody_returns",
    "latest_evidence_bundle_retention_custody_return",
    "evidence_bundle_retention_custody_return_verifications",
    "latest_evidence_bundle_retention_custody_return_verification",
    "evidence_bundle_retention_custody_redeposits",
    "latest_evidence_bundle_retention_custody_redeposit",
    "evidence_bundle_retention_custody_redeposit_verifications",
    "latest_evidence_bundle_retention_custody_redeposit_verification",
    "evidence_bundle_retention_custody_inventories",
    "latest_evidence_bundle_retention_custody_inventory",
    "evidence_bundle_retention_custody_inventory_verifications",
    "latest_evidence_bundle_retention_custody_inventory_verification",
    "evidence_bundle_retention_custody_reconciliations",
    "latest_evidence_bundle_retention_custody_reconciliation",
    "evidence_bundle_retention_custody_reconciliation_verifications",
    "latest_evidence_bundle_retention_custody_reconciliation_verification",
    "evidence_bundle_retention_custody_certifications",
    "latest_evidence_bundle_retention_custody_certification",
    "evidence_bundle_retention_custody_certification_verifications",
    "latest_evidence_bundle_retention_custody_certification_verification",
    "evidence_bundle_retention_custody_attestations",
    "latest_evidence_bundle_retention_custody_attestation",
    "evidence_bundle_retention_custody_attestation_verifications",
    "latest_evidence_bundle_retention_custody_attestation_verification",
)


def _require_complete_values(values: Mapping[str, Any]) -> None:
    """Fail fast if the lifecycle collector and projection helpers drift."""
    missing = [key for key in _VALUE_KEYS if key not in values]
    if missing:
        raise KeyError(f"Missing evidence lifecycle projection values: {', '.join(missing)}")

__all__ = ["_VALUE_KEYS", "_require_complete_values"]
