from __future__ import annotations

import hashlib, json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from strategy_validator.application.ui_semantic_validator_handoff_escalation_board import build_ui_semantic_validator_handoff_escalation_board_payload
_SCHEMA_VERSION='ui_semantic_validator_handoff_resolution_plan/v1'; _LIMIT_MAX=1000
_PHASE={'BLOCKER_TRIAGE':0,'EXTERNAL_ARTIFACT_COLLECTION':1,'OPERATOR_REVIEW':2,'MONITORING':3}; _PRIORITY={'P0':0,'P1':1,'P2':2,'P3':3}; _SEV={'CRITICAL':0,'HIGH':1,'BLOCKED':1,'WARN':2,'MEDIUM':2,'LOW':3,'INFO':4}
def _utc_now(): return datetime.now(timezone.utc).isoformat()
def _s(v): return str(v or '').strip()
def _norm(v): return _s(v).upper()
def _as_list(v): return [str(x) for x in v if str(x).strip()] if isinstance(v,(list,tuple,set)) else []
def _norm_set(v): return {_norm(x) for x in (v or ()) if _s(x)}
def _contains(v,n): return True if not n else n.strip().lower() in str(v or '').lower()
def _digest(o): return hashlib.sha256(json.dumps(o,sort_keys=True,separators=(',',':'),default=str).encode()).hexdigest()
def _counts(rows:Iterable[dict[str,Any]], field:str): c=Counter(_s(r.get(field)) or 'UNKNOWN' for r in rows); return dict(sorted(c.items()))
def _authority(): return {'read_plane_only':True,'plan_materialization_allowed':False,'step_acknowledgment_allowed':False,'repair_execution_allowed':False,'external_artifact_write_allowed':False,'artifact_mutation_allowed':False,'validator_submission_allowed':False,'adjudication_allowed':False,'promotion_allowed':False,'execution_allowed':False,'authority_boundary':'read_plane_only_resolution_plan_visibility_no_ack_no_write_no_submit_no_execute'}
def _phase(c):
    lane=_s(c.get('escalation_lane'))
    return 'BLOCKER_TRIAGE' if lane=='IMMEDIATE_BLOCKER' else 'EXTERNAL_ARTIFACT_COLLECTION' if lane=='EXTERNAL_ARTIFACT_NEEDED' else 'OPERATOR_REVIEW' if lane=='OPERATOR_REVIEW' else 'MONITORING'
def _state(ph,c): return 'BLOCKING_HUMAN_TRIAGE_REQUIRED' if ph=='BLOCKER_TRIAGE' else 'WAITING_EXTERNAL_ARTIFACT' if ph=='EXTERNAL_ARTIFACT_COLLECTION' else 'HUMAN_REVIEW_REQUIRED' if ph=='OPERATOR_REVIEW' else 'MONITOR_ONLY'
def _instruction(ph,c):
    route=_s(c.get('route')) or '/ui/semantic-validator-handoff/escalation-board'
    if ph=='BLOCKER_TRIAGE': return f'Open {route}, inspect blocker evidence, and resolve outside this read-plane before trusting handoff closure.'
    if ph=='EXTERNAL_ARTIFACT_COLLECTION': return f'Create or attach the required external artifact outside this read-plane, then re-open {route} to verify the gap disappears.'
    if ph=='OPERATOR_REVIEW': return f'Open {route}, review the operator action, and only proceed via governed channels outside this projection.'
    return f'Monitor {route} for drift; no repair action is indicated by this read-plane step.'
def _gate(ph): return {'BLOCKER_TRIAGE':'BLOCKING_ESCALATION_REMOVED_OR_DOWNGRADED_IN_SOURCE_READ_PLANE','EXTERNAL_ARTIFACT_COLLECTION':'EXTERNAL_ARTIFACT_GAP_REMOVED_FROM_EVIDENCE_GAPS_AND_ACTION_QUEUE','OPERATOR_REVIEW':'OPERATOR_REVIEW_ACTION_NO_LONGER_PRESENT_IN_ACTION_QUEUE'}.get(ph,'NO_NEW_ESCALATION_OR_TRUST_DRIFT_PRESENT')
def _step(c, ordinal):
    ph=_phase(c); pr=_s(c.get('priority')) or 'P2'; sev=_s(c.get('severity')) or 'WARN'; state=_state(ph,c); issues=_as_list(c.get('issue_codes'))
    return {'resolution_step_id':'semantic-validator-handoff-resolution-step-'+_digest({'schema_version':_SCHEMA_VERSION,'phase':ph,'ordinal':ordinal,'escalation':c.get('escalation_id'),'digest':c.get('audit_packet_digest')})[:20],'schema_version':_SCHEMA_VERSION,'ordinal':ordinal,'phase':ph,'phase_rank':_PHASE.get(ph,99),'step_state':state,'blocks_handoff_clearance':ph in {'BLOCKER_TRIAGE','EXTERNAL_ARTIFACT_COLLECTION'} or bool(c.get('blocked')),'requires_external_artifact':bool(c.get('external_artifact_required')),'requires_human_review':ph!='MONITORING','experiment_id':c.get('experiment_id'),'continuity_id':c.get('continuity_id'),'chain_id':c.get('chain_id'),'chain_digest':c.get('chain_digest'),'audit_packet_id':c.get('audit_packet_id'),'audit_packet_digest':c.get('audit_packet_digest'),'action_id':c.get('action_id'),'escalation_id':c.get('escalation_id'),'escalation_lane':c.get('escalation_lane'),'escalation_reason':c.get('escalation_reason'),'owner_hint':c.get('owner_hint') or 'human_operator_review_owner','priority':pr,'severity':sev,'trust_banner':c.get('trust_banner') or 'TRUST_RESTRICTED','queue_state':c.get('queue_state'),'packet_status':c.get('packet_status'),'source':c.get('source') or 'escalation_board','source_id':c.get('source_id'),'operator_action':c.get('operator_action') or 'INSPECT_SEMANTIC_VALIDATOR_HANDOFF_ESCALATION','source_route':c.get('route') or '/ui/semantic-validator-handoff/escalation-board','resolution_route':c.get('route') or '/ui/semantic-validator-handoff/escalation-board','issue_codes':issues,'issue_count':len(issues),'safe_instruction':_instruction(ph,c),'completion_gate':_gate(ph),'verification_hint':'Refresh the action queue, escalation board, and resolution plan after out-of-band remediation; this projection does not record acknowledgment.','acknowledgment_authority':'none_read_plane','repair_execution_authority':'none_read_plane','external_artifact_write_authority':'none_read_plane','validator_submission_authority':'none_read_plane','execution_authority':'none_read_plane','authority':_authority(),'source_escalation_card':c,'summary_line':f'{ordinal}. {ph} · {c.get("experiment_id")} · {pr}/{sev} · {state} · ack=false repair=false submit=false execute=false'}
def _sort(s): return (int(s.get('phase_rank') or 99),_PRIORITY.get(_norm(s.get('priority')),9),_SEV.get(_norm(s.get('severity')),9),_s(s.get('experiment_id')),_s(s.get('resolution_step_id')))
def _hay(s): return '\n'.join([_s(s.get(k)) for k in ('experiment_id','resolution_step_id','phase','step_state','owner_hint','priority','severity','trust_banner','source','source_id','operator_action','safe_instruction','completion_gate','summary_line')]+_as_list(s.get('issue_codes')))
def _matches(s,*,experiment_id_contains=None,issue_contains=None,phase=set(),step_state=set(),priority=set(),severity=set(),trust_banner=set(),owner_hint=set(),requires_external_artifact=None,blocks_handoff_clearance=None): return _contains(s.get('experiment_id'),experiment_id_contains) and (not issue_contains or _contains(_hay(s),issue_contains)) and (not phase or _norm(s.get('phase')) in phase) and (not step_state or _norm(s.get('step_state')) in step_state) and (not priority or _norm(s.get('priority')) in priority) and (not severity or _norm(s.get('severity')) in severity) and (not trust_banner or _norm(s.get('trust_banner')) in trust_banner) and (not owner_hint or _norm(s.get('owner_hint')) in owner_hint) and (requires_external_artifact is None or bool(s.get('requires_external_artifact')) is requires_external_artifact) and (blocks_handoff_clearance is None or bool(s.get('blocks_handoff_clearance')) is blocks_handoff_clearance)
def build_ui_semantic_validator_handoff_resolution_plan_payload(*, repo_root: str|Path|None=None, search_root: str|Path|None=None, experiment_id_contains: str|None=None, issue_contains: str|None=None, phase: tuple[str,...]=(), step_state: tuple[str,...]=(), priority: tuple[str,...]=(), severity: tuple[str,...]=(), trust_banner: tuple[str,...]=(), owner_hint: tuple[str,...]=(), requires_external_artifact: bool|None=None, blocks_handoff_clearance: bool|None=None, limit:int=200):
    capped=max(1,min(int(limit or 200),_LIMIT_MAX)); bp=build_ui_semantic_validator_handoff_escalation_board_payload(repo_root=repo_root,search_root=search_root,experiment_id_contains=experiment_id_contains,issue_contains=issue_contains,priority=priority,severity=severity,trust_banner=trust_banner,external_artifact_required=requires_external_artifact,limit=_LIMIT_MAX)
    cards=[c for c in bp.get('escalation_cards',[]) if isinstance(c,dict)]; steps=sorted([_step(c,i+1) for i,c in enumerate(sorted(cards,key=lambda x:int(x.get('escalation_rank') or 0)))],key=_sort); filt=[s for s in steps if _matches(s,experiment_id_contains=experiment_id_contains,issue_contains=issue_contains,phase=_norm_set(phase),step_state=_norm_set(step_state),priority=_norm_set(priority),severity=_norm_set(severity),trust_banner=_norm_set(trust_banner),owner_hint=_norm_set(owner_hint),requires_external_artifact=requires_external_artifact,blocks_handoff_clearance=blocks_handoff_clearance)]; ret=filt[:capped]; latest=ret[0] if ret else None
    src=_as_list(bp.get('degraded')); deg=[]
    if src: deg.append('SOURCE_SEMANTIC_VALIDATOR_HANDOFF_ESCALATION_BOARD_DEGRADED')
    if not cards and int((bp.get('summary') or {}).get('source_action_count_total') or 0)==0: deg.append('NO_SEMANTIC_VALIDATOR_HANDOFF_ESCALATIONS_FOUND')
    if any(s.get('phase')=='BLOCKER_TRIAGE' for s in filt): deg.append('BLOCKING_SEMANTIC_VALIDATOR_HANDOFF_RESOLUTION_STEP_PRESENT')
    if any(s.get('phase')=='EXTERNAL_ARTIFACT_COLLECTION' for s in filt): deg.append('EXTERNAL_ARTIFACT_SEMANTIC_VALIDATOR_HANDOFF_RESOLUTION_STEP_PRESENT')
    return {'schema_version':_SCHEMA_VERSION,'generated_at_utc':_utc_now(),'read_plane_only':True,'mutation_authority':'none_read_plane','plan_materialization_authority':'none_read_plane','step_acknowledgment_authority':'none_read_plane','repair_execution_authority':'none_read_plane','external_artifact_write_authority':'none_read_plane','artifact_mutation_authority':'none_read_plane','validator_submission_authority':'none_read_plane','adjudication_authority':'none_read_plane','promotion_authority':'none_read_plane','execution_authority':'none_read_plane','source_schema_version':bp.get('schema_version'),'search_root':bp.get('search_root'),'filters':{'experiment_id_contains':experiment_id_contains,'issue_contains':issue_contains,'limit':capped},'summary':{'source_escalation_count_total':len(cards),'resolution_step_count_total':len(steps),'resolution_step_count_filtered':len(filt),'resolution_step_count_returned':len(ret),'blocker_triage_count':sum(1 for s in filt if s.get('phase')=='BLOCKER_TRIAGE'),'external_artifact_collection_count':sum(1 for s in filt if s.get('phase')=='EXTERNAL_ARTIFACT_COLLECTION'),'operator_review_count':sum(1 for s in filt if s.get('phase')=='OPERATOR_REVIEW'),'monitoring_count':sum(1 for s in filt if s.get('phase')=='MONITORING'),'blocks_handoff_clearance_count':sum(1 for s in filt if s.get('blocks_handoff_clearance')),'requires_external_artifact_count':sum(1 for s in filt if s.get('requires_external_artifact')),'requires_human_review_count':sum(1 for s in filt if s.get('requires_human_review')),'p0_count':sum(1 for s in filt if s.get('priority')=='P0'),'p1_count':sum(1 for s in filt if s.get('priority')=='P1'),'step_acknowledgment_allowed_count':0,'repair_execution_allowed_count':0,'validator_submission_allowed_count':0,'promotion_allowed_count':0,'execution_allowed_count':0,'latest_resolution_step_id':None if latest is None else latest.get('resolution_step_id')},'phase_counts':_counts(filt,'phase'),'step_state_counts':_counts(filt,'step_state'),'priority_counts':_counts(filt,'priority'),'severity_counts':_counts(filt,'severity'),'owner_hint_counts':_counts(filt,'owner_hint'),'trust_banner_counts':_counts(filt,'trust_banner'),'route_counts':_counts(filt,'resolution_route'),'source_counts':_counts(filt,'source'),'source_degraded':src,'degraded':deg,'guardrails':['read_plane_only_resolution_plan_no_acknowledgment_or_repair_is_performed_here','external_artifacts_must_be_created_outside_this_projection','no_validator_submission_adjudication_promotion_or_execution_authority'],'routes':{'resolution_plan':'/ui/semantic-validator-handoff/resolution-plan','escalation_board':'/ui/semantic-validator-handoff/escalation-board','action_queue':'/ui/semantic-validator-handoff/action-queue','audit_packet':'/ui/semantic-validator-handoff/audit-packet'},'latest':latest,'resolution_steps':ret}
def build_ui_semantic_validator_handoff_resolution_plan_latest_payload(*, repo_root: str|Path|None=None, search_root: str|Path|None=None): return build_ui_semantic_validator_handoff_resolution_plan_payload(repo_root=repo_root,search_root=search_root,limit=1)
__all__=['build_ui_semantic_validator_handoff_resolution_plan_payload','build_ui_semantic_validator_handoff_resolution_plan_latest_payload']
