from __future__ import annotations

import hashlib, json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from strategy_validator.application.ui_semantic_validator_handoff_action_queue import build_ui_semantic_validator_handoff_action_queue_payload
_SCHEMA_VERSION='ui_semantic_validator_handoff_escalation_board/v1'; _LIMIT_MAX=1000
_LANE_ORDER={'IMMEDIATE_BLOCKER':0,'EXTERNAL_ARTIFACT_NEEDED':1,'OPERATOR_REVIEW':2,'MONITOR_ONLY':3}; _PRIORITY={'P0':0,'P1':1,'P2':2,'P3':3}; _SEV={'CRITICAL':0,'HIGH':1,'BLOCKED':1,'WARN':2,'MEDIUM':2,'LOW':3,'INFO':4}
def _utc_now(): return datetime.now(timezone.utc).isoformat()
def _s(v): return str(v or '').strip()
def _norm(v): return _s(v).upper()
def _as_list(v): return [str(x) for x in v if str(x).strip()] if isinstance(v,(list,tuple,set)) else []
def _norm_set(v): return {_norm(x) for x in (v or ()) if _s(x)}
def _contains(v,n): return True if not n else n.strip().lower() in str(v or '').lower()
def _digest(o): return hashlib.sha256(json.dumps(o,sort_keys=True,separators=(',',':'),default=str).encode()).hexdigest()
def _counts(rows:Iterable[dict[str,Any]], field:str): c=Counter(_s(r.get(field)) or 'UNKNOWN' for r in rows); return dict(sorted(c.items()))
def _authority(): return {'read_plane_only':True,'escalation_acknowledgment_allowed':False,'action_execution_allowed':False,'external_artifact_write_allowed':False,'artifact_mutation_allowed':False,'validator_submission_allowed':False,'adjudication_allowed':False,'promotion_allowed':False,'execution_allowed':False,'authority_boundary':'read_plane_only_escalation_visibility_no_ack_no_write_no_submit_no_execute'}
def _lane(a):
    qs=_s(a.get('queue_state'))
    if bool(a.get('blocked')) or qs=='BLOCKED_ACTION_REQUIRED' or _norm(a.get('severity')) in {'CRITICAL','HIGH','BLOCKED'}: return 'IMMEDIATE_BLOCKER'
    if bool(a.get('external_artifact_required')) or qs=='EXTERNAL_ARTIFACT_REQUIRED': return 'EXTERNAL_ARTIFACT_NEEDED'
    if bool(a.get('operator_attention_required')) or qs=='OPERATOR_ACTION_REQUIRED': return 'OPERATOR_REVIEW'
    return 'MONITOR_ONLY'
def _owner(lane): return {'IMMEDIATE_BLOCKER':'human_operator_blocker_owner','EXTERNAL_ARTIFACT_NEEDED':'external_operator_artifact_owner','OPERATOR_REVIEW':'human_operator_review_owner'}.get(lane,'read_plane_monitor')
def _reason(lane): return {'IMMEDIATE_BLOCKER':'blocked_or_high_severity_action_requires_human_review_before_handoff_can_be_trusted','EXTERNAL_ARTIFACT_NEEDED':'missing_external_artifact_must_be_created_outside_this_read_plane','OPERATOR_REVIEW':'operator_attention_required_but_no_write_or_execution_authority_is_granted_here'}.get(lane,'no_escalation_required_monitor_for_drift')
def _card(a, idx):
    lane=_lane(a); pr=_s(a.get('priority')) or 'P2'; sev=_s(a.get('severity')) or 'WARN'
    return {'escalation_id':'semantic-validator-handoff-escalation-'+_digest({'schema_version':_SCHEMA_VERSION,'lane':lane,'action':a.get('action_id'),'digest':a.get('audit_packet_digest'),'idx':idx})[:20],'schema_version':_SCHEMA_VERSION,'escalation_lane':lane,'escalation_rank':_LANE_ORDER.get(lane,99)*10000+_PRIORITY.get(_norm(pr),9)*1000+_SEV.get(_norm(sev),9)*100+idx,'escalation_reason':_reason(lane),'owner_hint':_owner(lane),'action_id':a.get('action_id'),'audit_packet_id':a.get('audit_packet_id'),'audit_packet_digest':a.get('audit_packet_digest'),'experiment_id':a.get('experiment_id'),'continuity_id':a.get('continuity_id'),'chain_id':a.get('chain_id'),'chain_digest':a.get('chain_digest'),'packet_status':a.get('packet_status'),'packet_lane':a.get('packet_lane'),'queue_state':a.get('queue_state'),'priority':pr,'severity':sev,'trust_banner':a.get('trust_banner') or 'TRUST_RESTRICTED','source':a.get('source') or 'audit_packet','source_id':a.get('source_id'),'operator_action':a.get('operator_action') or 'INSPECT_SEMANTIC_VALIDATOR_HANDOFF_ACTION','route':a.get('route') or '/ui/semantic-validator-handoff/action-queue','issue_codes':_as_list(a.get('issue_codes')),'issue_count':len(_as_list(a.get('issue_codes'))),'blocked':bool(a.get('blocked')),'external_artifact_required':bool(a.get('external_artifact_required')),'safe_next_step':a.get('safe_next_step') or 'OPEN_READ_PLANE_ROUTE_AND_REVIEW','acknowledgment_authority':'none_read_plane','action_execution_authority':'none_read_plane','external_artifact_write_authority':'none_read_plane','validator_submission_authority':'none_read_plane','execution_authority':'none_read_plane','authority':_authority(),'source_action_row':a,'summary_line':f"{a.get('experiment_id')} · {lane} · {pr}/{sev} · {a.get('operator_action')} · ack=false submit=false execute=false"}
def _sort(c): return (_LANE_ORDER.get(_s(c.get('escalation_lane')),99),_PRIORITY.get(_norm(c.get('priority')),9),_SEV.get(_norm(c.get('severity')),9),_s(c.get('experiment_id')),_s(c.get('escalation_id')))
def _hay(c): return '\n'.join([_s(c.get(k)) for k in ('experiment_id','audit_packet_id','action_id','escalation_id','escalation_lane','owner_hint','queue_state','priority','severity','trust_banner','source','source_id','operator_action','route','summary_line')]+_as_list(c.get('issue_codes')))
def _matches(c,*,experiment_id_contains=None,issue_contains=None,escalation_lane=set(),priority=set(),severity=set(),trust_banner=set(),source=set(),external_artifact_required=None,blocked=None): return _contains(c.get('experiment_id'),experiment_id_contains) and (not issue_contains or _contains(_hay(c),issue_contains)) and (not escalation_lane or _norm(c.get('escalation_lane')) in escalation_lane) and (not priority or _norm(c.get('priority')) in priority) and (not severity or _norm(c.get('severity')) in severity) and (not trust_banner or _norm(c.get('trust_banner')) in trust_banner) and (not source or _norm(c.get('source')) in source) and (external_artifact_required is None or bool(c.get('external_artifact_required')) is external_artifact_required) and (blocked is None or bool(c.get('blocked')) is blocked)
def build_ui_semantic_validator_handoff_escalation_board_payload(*, repo_root: str|Path|None=None, search_root: str|Path|None=None, experiment_id_contains: str|None=None, issue_contains: str|None=None, escalation_lane: tuple[str,...]=(), priority: tuple[str,...]=(), severity: tuple[str,...]=(), trust_banner: tuple[str,...]=(), source: tuple[str,...]=(), external_artifact_required: bool|None=None, blocked: bool|None=None, limit:int=200):
    capped=max(1,min(int(limit or 200),_LIMIT_MAX)); ap=build_ui_semantic_validator_handoff_action_queue_payload(repo_root=repo_root,search_root=search_root,experiment_id_contains=experiment_id_contains,issue_contains=issue_contains,priority=priority,severity=severity,trust_banner=trust_banner,source=source,external_artifact_required=external_artifact_required,blocked=blocked,limit=_LIMIT_MAX)
    acts=[a for a in ap.get('action_rows',[]) if isinstance(a,dict)]; cards=sorted([_card(a,i) for i,a in enumerate(acts)],key=_sort); filt=[c for c in cards if _matches(c,experiment_id_contains=experiment_id_contains,issue_contains=issue_contains,escalation_lane=_norm_set(escalation_lane),priority=_norm_set(priority),severity=_norm_set(severity),trust_banner=_norm_set(trust_banner),source=_norm_set(source),external_artifact_required=external_artifact_required,blocked=blocked)]; ret=filt[:capped]; latest=ret[0] if ret else None
    src_deg=_as_list(ap.get('degraded')); deg=[]
    if src_deg: deg.append('SOURCE_SEMANTIC_VALIDATOR_HANDOFF_ACTION_QUEUE_DEGRADED')
    if any(c.get('escalation_lane')=='IMMEDIATE_BLOCKER' for c in filt): deg.append('IMMEDIATE_SEMANTIC_VALIDATOR_HANDOFF_BLOCKER_PRESENT')
    if any(c.get('escalation_lane')=='EXTERNAL_ARTIFACT_NEEDED' for c in filt): deg.append('EXTERNAL_ARTIFACT_SEMANTIC_VALIDATOR_HANDOFF_ESCALATION_PRESENT')
    return {'schema_version':_SCHEMA_VERSION,'generated_at_utc':_utc_now(),'read_plane_only':True,'mutation_authority':'none_read_plane','escalation_acknowledgment_authority':'none_read_plane','action_execution_authority':'none_read_plane','external_artifact_write_authority':'none_read_plane','artifact_mutation_authority':'none_read_plane','validator_submission_authority':'none_read_plane','adjudication_authority':'none_read_plane','promotion_authority':'none_read_plane','execution_authority':'none_read_plane','source_schema_version':ap.get('schema_version'),'search_root':ap.get('search_root'),'filters':{'experiment_id_contains':experiment_id_contains,'issue_contains':issue_contains,'limit':capped},'summary':{'source_action_count_total':len(acts),'escalation_count_total':len(cards),'escalation_count_filtered':len(filt),'escalation_count_returned':len(ret),'immediate_blocker_count':sum(1 for c in filt if c.get('escalation_lane')=='IMMEDIATE_BLOCKER'),'external_artifact_needed_count':sum(1 for c in filt if c.get('escalation_lane')=='EXTERNAL_ARTIFACT_NEEDED'),'operator_review_count':sum(1 for c in filt if c.get('escalation_lane')=='OPERATOR_REVIEW'),'monitor_only_count':sum(1 for c in filt if c.get('escalation_lane')=='MONITOR_ONLY'),'blocked_count':sum(1 for c in filt if c.get('blocked')),'external_artifact_required_count':sum(1 for c in filt if c.get('external_artifact_required')),'p0_count':sum(1 for c in filt if c.get('priority')=='P0'),'p1_count':sum(1 for c in filt if c.get('priority')=='P1'),'acknowledgment_allowed_count':0,'execution_allowed_count':0,'latest_escalation_id':None if latest is None else latest.get('escalation_id')},'escalation_lane_counts':_counts(filt,'escalation_lane'),'priority_counts':_counts(filt,'priority'),'severity_counts':_counts(filt,'severity'),'source_counts':_counts(filt,'source'),'route_counts':_counts(filt,'route'),'trust_banner_counts':_counts(filt,'trust_banner'),'queue_state_counts':_counts(filt,'queue_state'),'owner_hint_counts':_counts(filt,'owner_hint'),'source_degraded':src_deg,'degraded':deg,'guardrails':['read_plane_only_escalation_board_no_acknowledgment_or_repair_is_performed_here','external_artifacts_must_be_created_outside_this_projection','no_validator_submission_adjudication_promotion_or_execution_authority'],'routes':{'escalation_board':'/ui/semantic-validator-handoff/escalation-board','action_queue':'/ui/semantic-validator-handoff/action-queue','audit_packet':'/ui/semantic-validator-handoff/audit-packet'},'latest':latest,'escalation_cards':ret}
def build_ui_semantic_validator_handoff_escalation_board_latest_payload(*, repo_root: str|Path|None=None, search_root: str|Path|None=None): return build_ui_semantic_validator_handoff_escalation_board_payload(repo_root=repo_root,search_root=search_root,limit=1)
__all__=['build_ui_semantic_validator_handoff_escalation_board_payload','build_ui_semantic_validator_handoff_escalation_board_latest_payload']
